import type{HistoricalConfidence,RetrospectiveSample}from"./historical-calibration";
export const HISTORICAL_ANALYSIS_CACHE_VERSION=3;
export interface AnalysisSnapshot{version:number;userId:string;fingerprint:string;generatedAt:string;baseline:{value:number|null;sampleCount:number;confidence:HistoricalConfidence};samples:RetrospectiveSample[];buckets:{bucket:string;sampleCount:number;medianGridImportKwhDay:number;medianGridImportAboveBaselineKwhDay:number}[]}
const memory=new Map<string,AnalysisSnapshot>();const DB="wattmerleg-analysis",STORE="snapshots";
export function snapshotMemoryGet(userId:string){return memory.get(userId)??null}export function snapshotMemorySet(snapshot:AnalysisSnapshot){memory.set(snapshot.userId,snapshot)}export function clearSnapshotMemory(){memory.clear()}
export function analysisFingerprint(input:{userId:string;readingCount:number;latestReadingAt:string|null;latestUpdatedAt:string|null;seasonStart:string;seasonEnd:string;locationKey:string;profileValues:(string|number|boolean|null|undefined)[];version?:number}){const raw=[input.version??HISTORICAL_ANALYSIS_CACHE_VERSION,input.userId,input.readingCount,input.latestReadingAt??"",input.latestUpdatedAt??"",input.seasonStart,input.seasonEnd,input.locationKey,...input.profileValues].join("|");let hash=2166136261;for(let i=0;i<raw.length;i++){hash^=raw.charCodeAt(i);hash=Math.imul(hash,16777619)}return`historical-analysis:v${input.version??HISTORICAL_ANALYSIS_CACHE_VERSION}:${input.userId}:${(hash>>>0).toString(16)}`}
export function canUseSnapshot(snapshot:AnalysisSnapshot|null,fingerprint:string,manualRefresh=false){return !manualRefresh&&snapshot?.version===HISTORICAL_ANALYSIS_CACHE_VERSION&&snapshot.fingerprint===fingerprint}
export function readingFingerprintMetadata(readings:ReadonlyArray<{reading_at:string;updated_at:string|null|undefined}>){let latestReadingAt:string|null=null,latestUpdatedAt:string|null=null;for(const reading of readings){if(!latestReadingAt||reading.reading_at>latestReadingAt)latestReadingAt=reading.reading_at;if(reading.updated_at&&(!latestUpdatedAt||reading.updated_at>latestUpdatedAt))latestUpdatedAt=reading.updated_at}return{readingCount:readings.length,latestReadingAt,latestUpdatedAt}}
export function consumeManualRefreshToken(requested:number,consumed:number){const forceRefresh=requested>consumed;return{forceRefresh,consumed:forceRefresh?requested:consumed}}
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORE))request.result.createObjectStore(STORE,{keyPath:"userId"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
export async function loadAnalysisSnapshot(userId:string):Promise<AnalysisSnapshot|null>{const hot=snapshotMemoryGet(userId);if(hot)return hot;if(typeof indexedDB==="undefined")return null;try{const db=await openDb();const value=await new Promise<AnalysisSnapshot|undefined>((resolve,reject)=>{const request=db.transaction(STORE,"readonly").objectStore(STORE).get(userId);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});db.close();if(!value||value.version!==HISTORICAL_ANALYSIS_CACHE_VERSION)return null;snapshotMemorySet(value);return value}catch{return null}}
export async function saveAnalysisSnapshot(snapshot:AnalysisSnapshot){snapshotMemorySet(snapshot);if(typeof indexedDB==="undefined")return;try{const db=await openDb();await new Promise<void>((resolve,reject)=>{const request=db.transaction(STORE,"readwrite").objectStore(STORE).put(snapshot);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)});db.close()}catch{/* A gyorsítótár hibája nem törheti el az elemzést. */}}
export const serializedSnapshotBytes=(snapshot:AnalysisSnapshot)=>new TextEncoder().encode(JSON.stringify(snapshot)).byteLength;
