import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";const source=readFileSync("scripts/test-heating-analysis-db.ts","utf8"),pkg=JSON.parse(readFileSync("package.json","utf8"));
describe("heating DB integration runner",()=>{
 it("is fail-closed and localhost-only",()=>{expect(source).toContain("HEATING_ANALYSIS_DB_TEST_NOT_CONFIGURED");expect(source).toContain("HEATING_ANALYSIS_DB_TEST_REQUIRES_LOCAL_DATABASE");expect(source).toContain('"localhost","127.0.0.1","::1"')});
 it("has safe categorized stage errors and success marker",()=>{expect(source).toContain("HEATING_ANALYSIS_DB_TEST_FAILED:${stage}:PSQL_SPAWN_ERROR:${code}");expect(source).toContain("HEATING_ANALYSIS_DB_TEST_FAILED:${stage}:PSQL_EXIT_ERROR:");expect(source).not.toContain("result.stderr");expect(source).toContain("HEATING_ANALYSIS_DB_INTEGRATION_OK")});
 it("uses the same finite output buffer for stdin SQL and file execution",()=>{expect(source).toContain("const PSQL_MAX_BUFFER_BYTES=32*1024*1024");expect(source).toContain("maxBuffer:PSQL_MAX_BUFFER_BYTES");expect(source).toContain('spawnSync("psql",[...psqlBase,...args],psqlSpawnOptions)');expect(source).toContain('spawnSync("psql",psqlBase,{...psqlSpawnOptions,input:`${sql}\\n`})')});
 it("passes dynamic SQL through stdin and keeps file execution separate",()=>{expect(source).not.toContain('[...psqlBase,"-c",sql]');expect(source).toContain('executeArgs(["-f",resolve("supabase/migrations/014_eon_heating_analysis.sql")]')});
 it("checks a large intact stdin JSON payload and fail-closed SQL errors",()=>{for(const marker of["STDIN_LARGE_PAYLOAD","STDIN_PAYLOAD_CORRUPTED","STDIN_SQL_FAILURE","STDIN_SQL_NOT_FAIL_CLOSED","stdinPayload.length>=100_000"])expect(source).toContain(marker)});
 it("checks large stdout and maps its finite-limit failure safely",()=>{for(const marker of["STDOUT_LARGE_PAYLOAD","STDOUT_PAYLOAD_CORRUPTED","STDOUT_LIMIT","STDOUT_LIMIT_NOT_FAIL_CLOSED","PSQL_OUTPUT_LIMIT_EXCEEDED"])expect(source).toContain(marker);expect(source).toContain("2*1024*1024")});
 it("runs the real rebuild service and covers security/state invariants",()=>{for(const marker of["runHeatingAnalysisRebuild","PARALLEL_CLAIM_NOT_BLOCKED","AUTHENTICATED_WRITER_ALLOWED","SERVICE_WRITER_DENIED","MISSING_PV_GRID_CYCLE_LOST","UNKNOWN_DAILY_ESTIMATE_CREATED","UNKNOWN_HEATING_EXCESS_NOT_NULL","MIXED_INTERVAL_DETECTION_FAILED","MANUAL_SEASON_SIGNAL_MISSING","PHYSICAL_70_KWH_EXCESS_FAILED","MANUAL_CONFIRMATION_COUNTED_AS_EXCLUDED","FALL_100_DAY_FAILED","FALL_96_DAY_NOT_EXCLUDED","STALE_FEATURE_NOT_REMOVED","RLS_FAILED"])expect(source).toContain(marker)});
 it("is exposed as package script",()=>expect(pkg.scripts["test:heating-analysis-db"]).toBe("tsx scripts/test-heating-analysis-db.ts"));
});
