import { addCalendarDays,localDayWindow,localIsoDate } from "@/lib/weather/date";
export type Confidence="low"|"medium"|"high";export type OperationState="definitely_off"|"available"|"mixed"|"unknown";
export type OperationPeriod={enabledAt:string;disabledAt:string|null};export type DayValidation={localDate:string;label:"definitely_on"|"definitely_off"|"uncertain"};
export type QuarterHour={at:string;localDate?:string;importKwh:number;exportKwh:number;localSlot?:number;localWeekend?:boolean;localHour?:number};export type WeatherHour={at:string;temperatureC:number;windSpeedKmh?:number|null;shortwaveRadiationWm2?:number|null;cloudCoverPercent?:number|null;source?:"open_meteo_archive"|"open_meteo_forecast"};
export type BaselinePoint={slot:number;weekend:boolean;kwh:number;sampleCount:number;confidence:Confidence};
export type DayQuality={availableIntervals:number;expectedIntervals:number;coveragePercent:number;provisional:boolean;warnings:string[];usableForTraining:boolean};
export type HeatingDayFeature={localDate:string;gridImportKwh:number;gridExportKwh:number;pvProductionKwh:number|null;totalHomeConsumptionKwh:number|null;baselineKwh:number|null;gridImportBaselineKwh?:number|null;excessKwh:number|null;detectedGridHeatingKwh?:number;dailyHeatingExcessKwh?:number|null;estimatedHeatingKwh:number|null;averageTemperatureC:number|null;minimumTemperatureC:number|null;maximumTemperatureC:number|null;heatingDegreeHours:number|null;weatherCoveragePercent:number;availableIntervals:number;expectedIntervals:number;coveragePercent:number;provisional:boolean;detectedCycleCount:number;confidence:Confidence;warnings:string[];isHeatingRelevant:boolean;operationState:OperationState};
export const median=(xs:number[])=>{const a=[...xs].sort((x,y)=>x-y);return a.length?a[Math.floor(a.length/2)]:null};
const formatterCache=new Map<string,Intl.DateTimeFormat>();
const zonedFormatter=(timeZone:string)=>{let formatter=formatterCache.get(timeZone);if(!formatter){formatter=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",weekday:"short",hourCycle:"h23"});formatterCache.set(timeZone,formatter)}return formatter};
const zonedParts=(at:string,timeZone:string)=>{const parts=Object.fromEntries(zonedFormatter(timeZone).formatToParts(new Date(at)).filter(x=>x.type!=="literal").map(x=>[x.type,x.value]));return{localDate:`${parts.year}-${parts.month}-${parts.day}`,slot:Number(parts.hour)*4+Math.floor(Number(parts.minute)/15),weekend:parts.weekday==="Sat"||parts.weekday==="Sun",hour:Number(parts.hour)}};
export function indexQuarterHours(rows:QuarterHour[],timeZone="Europe/Budapest"):QuarterHour[]{return rows.map(row=>{const parts=zonedParts(row.at,timeZone);return{...row,localDate:row.localDate??parts.localDate,localSlot:parts.slot,localWeekend:parts.weekend,localHour:parts.hour}})}
const rowParts=(row:QuarterHour,timeZone:string)=>row.localSlot===undefined||row.localWeekend===undefined||row.localHour===undefined?zonedParts(row.at,timeZone):{localDate:row.localDate??localIsoDate(new Date(row.at),timeZone),slot:row.localSlot,weekend:row.localWeekend,hour:row.localHour};
const baselineKey=(slot:number,weekend:boolean)=>`${slot}:${weekend}`;
export function baselineLookup(points:BaselinePoint[]){return new Map(points.map(point=>[baselineKey(point.slot,point.weekend),point.kwh]))}
export function operationState(at:string,periods:OperationPeriod[]):OperationState{if(!periods.length)return"unknown";const time=Date.parse(at);if(!Number.isFinite(time))return"unknown";return periods.some(p=>time>=Date.parse(p.enabledAt)&&(p.disabledAt===null||time<Date.parse(p.disabledAt)))?"available":"definitely_off"}
export function dayOperationState(localDate:string,periods:OperationPeriod[],timeZone="Europe/Budapest"):OperationState{if(!periods.length)return"unknown";const{start,end}=localDayWindow(localDate,timeZone),overlaps=periods.filter(p=>Date.parse(p.enabledAt)<end&&(p.disabledAt===null||Date.parse(p.disabledAt)>start));if(!overlaps.length)return"definitely_off";return overlaps.some(p=>Date.parse(p.enabledAt)<=start&&(p.disabledAt===null||Date.parse(p.disabledAt)>=end))?"available":"mixed"}
export function totalHomeConsumption(importKwh:number,exportKwh:number,pvKwh:number|null){if(![importKwh,exportKwh].every(Number.isFinite)||pvKwh===null||!Number.isFinite(pvKwh))return{value:null,warning:"MISSING_OR_INCOMPLETE_PV"};const value=importKwh+pvKwh-exportKwh;return value<0?{value:null,warning:"NEGATIVE_HOME_CONSUMPTION"}:{value,warning:null}}
export function assessEonDay(localDate:string,rows:QuarterHour[],referenceDate:string,timeZone="Europe/Budapest"):DayQuality{const expected=localDayWindow(localDate,timeZone).durationHours*4,available=new Set(rows.map(x=>x.at)).size,provisional=localDate>=referenceDate,warnings:string[]=[];if(provisional)warnings.push("PROVISIONAL_DAY");if(expected===100&&available===96)warnings.push("DST_FALLBACK_SOURCE_96");else if(available<expected)warnings.push("INCOMPLETE_EON_DAY");return{availableIntervals:available,expectedIntervals:expected,coveragePercent:Math.round(1000*Math.min(available,expected)/expected)/10,provisional,warnings,usableForTraining:!provisional&&available===expected&&!warnings.length}}
export function trainBaseline(rows:QuarterHour[],periods:OperationPeriod[],qualities:Map<string,DayQuality>,timeZone="Europe/Budapest"):BaselinePoint[]{const groups=new Map<string,number[]>(),operationByDate=new Map<string,OperationState>();for(const row of rows){const p=rowParts(row,timeZone),date=row.localDate??p.localDate,q=qualities.get(date);let operation=operationByDate.get(date);if(!operation){operation=dayOperationState(date,periods,timeZone);operationByDate.set(date,operation)}if(operation!=="definitely_off"||!q?.usableForTraining||row.importKwh<0||row.exportKwh<0)continue;const key=baselineKey(p.slot,p.weekend),values=groups.get(key);if(values)values.push(row.importKwh);else groups.set(key,[row.importKwh])}return[...groups].map(([key,values])=>{const[slot,weekend]=key.split(":");const count=values.length;return{slot:Number(slot),weekend:weekend==="true",kwh:median(values)!,sampleCount:count,confidence:Number(slot)<24||Number(slot)>=88?(count>=3?"high":"medium"):(count>=3?"medium":"low")}})}
export function detectHeatingCycles(rows:QuarterHour[],periods:OperationPeriod[],baseline:BaselinePoint[],timeZone="Europe/Budapest",validation?:DayValidation,lookup=baselineLookup(baseline)){let cycleCount=0,runEnergy=0,runLength=0,estimated=0,daytime=false,lastAt:number|null=null;const flush=()=>{if(runLength>=4){cycleCount++;estimated+=runEnergy}runLength=0;runEnergy=0};for(const row of rows){const timestamp=Date.parse(row.at);if(lastAt!==null&&timestamp-lastAt!==900000)flush();lastAt=timestamp;const p=rowParts(row,timeZone),b=lookup.get(baselineKey(p.slot,p.weekend))??0,power=Math.max(0,row.importKwh-b)*4,allowed=operationState(row.at,periods)==="available"&&validation?.label!=="definitely_off";if(allowed&&power>=5.5&&power<=7.5){runLength++;runEnergy+=Math.max(0,row.importKwh-b);daytime ||= p.hour>=7&&p.hour<19}else flush()}flush();const confidence:Confidence=cycleCount===0?"low":daytime?"medium":"high";return{cycleCount,estimatedHeatingKwh:Math.round(estimated*1e6)/1e6,confidence,warnings:baseline.length?[]:["BASELINE_UNAVAILABLE"]}}
export type WeatherByLocalDate=Map<string,WeatherHour[]>;
export function groupWeatherByLocalDate(rows:WeatherHour[],timeZone="Europe/Budapest",dateFor=(row:WeatherHour)=>localIsoDate(new Date(row.at),timeZone)):WeatherByLocalDate{const grouped:WeatherByLocalDate=new Map();for(const row of rows){const date=dateFor(row),day=grouped.get(date);if(day)day.push(row);else grouped.set(date,[row])}return grouped}
export function dailyWeatherFromGroup(localDate:string,grouped:WeatherByLocalDate,targetC=21,timeZone="Europe/Budapest"){return aggregateDailyWeather(localDate,grouped.get(localDate)??[],targetC,timeZone)}
function aggregateDailyWeather(localDate:string,rows:WeatherHour[],targetC:number,timeZone:string){const values=rows.map(x=>x.temperatureC).filter(Number.isFinite),expected=localDayWindow(localDate,timeZone).durationHours,coverage=Math.round(1000*values.length/expected)/10;if(!values.length)return{average:null,minimum:null,maximum:null,heatingDegreeHours:null,coveragePercent:0};return{average:values.reduce((a,b)=>a+b,0)/values.length,minimum:Math.min(...values),maximum:Math.max(...values),heatingDegreeHours:values.reduce((sum,x)=>sum+Math.max(0,targetC-x),0),coveragePercent:Math.min(100,coverage)}}
export function dailyWeather(localDate:string,rows:WeatherHour[],targetC=21,timeZone="Europe/Budapest"){return aggregateDailyWeather(localDate,rows.filter(x=>localIsoDate(new Date(x.at),timeZone)===localDate),targetC,timeZone)}
export function recognizeHeatingSeason(days:HeatingDayFeature[],minimumConsecutiveDays=3){const ordered=[...days].sort((a,b)=>a.localDate.localeCompare(b.localDate)),candidate=(d:HeatingDayFeature)=>d.operationState!=="definitely_off"&&(d.averageTemperatureC??99)<16&&((d.estimatedHeatingKwh??0)>0||d.warnings.includes("MANUAL_HEATING_CONFIRMED")),runs:{start:number;end:number}[]=[];let start:number|null=null;for(let i=0;i<=ordered.length;i++){const continuous=i===0||i===ordered.length||addCalendarDays(ordered[i-1].localDate,1)===ordered[i].localDate,active=i<ordered.length&&candidate(ordered[i]);if(active&&(!continuous||start===null)){if(start!==null&&i-start>=minimumConsecutiveDays)runs.push({start,end:i-1});start=i}else if((!active||!continuous)&&start!==null){if(i-start>=minimumConsecutiveDays)runs.push({start,end:i-1});start=null}}return runs.length?{start:ordered[runs[0].start].localDate,end:ordered[runs.at(-1)!.end].localDate}:{start:null,end:null}}
export function seasonDifference(detected:{start:string|null;end:string|null},manual:OperationPeriod[]){const first=manual[0],date=(x:string|null|undefined)=>x?.slice(0,10)??null,diff=(a:string|null,b:string|null)=>a&&b?Math.round((Date.parse(a)-Date.parse(b))/86400000):null;return{manualStart:date(first?.enabledAt),manualEnd:date(first?.disabledAt),startDays:diff(detected.start,date(first?.enabledAt)),endDays:diff(detected.end,date(first?.disabledAt))}}
