import type { MeterReading, TariffSettings } from "@/lib/types";
import type { DailyWeather } from "@/lib/weather/types";
import { addCalendarDays, localDayWindow, localIsoDate } from "@/lib/weather/date";
export type HistoricalConfidence="low"|"medium"|"high";
export interface MeterIntervalSample{start:string;end:string;durationHours:number;durationDays:number;observedGridImportKwh:number;observedDailyGridImportKwh:number;productionDeltaKwh:number|null;dataWarning:string|null;}
export interface RetrospectiveSample extends MeterIntervalSample{sampleType:"retrospective";weatherMeanTempC:number;weatherMinTempC:number;weatherMaxTempC:number;estimatedBaseGridImportKwhDay:number;gridImportAboveBaselineKwhDay:number;confidence:HistoricalConfidence;weatherDayCount:number;weatherCoverageRatio:number;}
export function measurementIntervals(readings:MeterReading[]):MeterIntervalSample[]{const sorted=[...readings].sort((a,b)=>Date.parse(a.reading_at)-Date.parse(b.reading_at));const result:MeterIntervalSample[]=[];for(let i=1;i<sorted.length;i++){const previous=sorted[i-1],current=sorted[i],hours=(Date.parse(current.reading_at)-Date.parse(previous.reading_at))/3_600_000;if(!(hours>0))continue;const consumption=current.consumption_meter_kwh-previous.consumption_meter_kwh;const production=current.production_meter_kwh-previous.production_meter_kwh;if(consumption<0){result.push({start:previous.reading_at,end:current.reading_at,durationHours:hours,durationDays:hours/24,observedGridImportKwh:0,observedDailyGridImportKwh:0,productionDeltaKwh:production>=0?production:null,dataWarning:"Negatív fogyasztási mérődelta; training mintából kizárva."});continue}result.push({start:previous.reading_at,end:current.reading_at,durationHours:hours,durationDays:hours/24,observedGridImportKwh:consumption,observedDailyGridImportKwh:consumption/(hours/24),productionDeltaKwh:production>=0?production:null,dataWarning:production<0?"Negatív termelési delta; a termelési kontextus kihagyva.":null})}return result}
export interface IntervalWeatherSummary{meanC:number;minC:number;maxC:number;dayCount:number;coveredDurationHours:number;coverageRatio:number}
export function intervalWeather(interval:MeterIntervalSample,weather:DailyWeather[],timeZone="Europe/Budapest"):IntervalWeatherSummary|null{const start=Date.parse(interval.start),end=Date.parse(interval.end),seen=new Set<string>();let weighted=0,total=0,min=Infinity,max=-Infinity,count=0;for(const day of weather){if(seen.has(day.date))continue;seen.add(day.date);const window=localDayWindow(day.date,timeZone),overlap=Math.max(0,Math.min(end,window.end)-Math.max(start,window.start));if(overlap>0){weighted+=day.meanC*overlap;total+=overlap;min=Math.min(min,day.minC);max=Math.max(max,day.maxC);count++}}const duration=end-start;if(total<=0||duration<=0)return null;return{meanC:weighted/total,minC:min,maxC:max,dayCount:count,coveredDurationHours:total/3_600_000,coverageRatio:Math.min(total/duration,1)}}
export function median(values:number[]):number|null{if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2}
function monthDay(date:string){return date.slice(5,10)}
export function isHeatingSeasonDate(date:string,tariff:TariffSettings){const value=monthDay(date),start=`${String(tariff.heating_season_start_month).padStart(2,"0")}-${String(tariff.heating_season_start_day).padStart(2,"0")}`,end=`${String(tariff.heating_season_end_month).padStart(2,"0")}-${String(tariff.heating_season_end_day).padStart(2,"0")}`;return start<=end?value>=start&&value<=end:value>=start||value<=end}
export function intervalOverlapsHeatingSeason(interval:MeterIntervalSample,tariff:TariffSettings,timeZone="Europe/Budapest"):boolean{const start=Date.parse(interval.start),end=Date.parse(interval.end);let date=localIsoDate(new Date(start),timeZone),guard=0;while(guard++<4000){const window=localDayWindow(date,timeZone),overlap=Math.max(0,Math.min(end,window.end)-Math.max(start,window.start));if(overlap>0&&isHeatingSeasonDate(date,tariff))return true;if(window.end>=end)return false;date=addCalendarDays(date,1)}return true}
export function estimateBaseGridImport(intervals:MeterIntervalSample[],tariff:TariffSettings,timeZone="Europe/Budapest"){const valid=intervals.filter(x=>!x.dataWarning?.startsWith("Negatív fogyasztási")&&!intervalOverlapsHeatingSeason(x,tariff,timeZone)).map(x=>x.observedDailyGridImportKwh);return{value:median(valid),sampleCount:valid.length,confidence:(valid.length>=8?"high":valid.length>=3?"medium":"low") as HistoricalConfidence}}
export function historicalConfidence(interval:MeterIntervalSample,weatherComplete:boolean,baselineSamples:number):HistoricalConfidence{if(!weatherComplete||interval.dataWarning||interval.durationDays>14||baselineSamples<3)return"low";if(interval.durationDays>7||interval.productionDeltaKwh!=null&&interval.productionDeltaKwh>interval.observedGridImportKwh)return"low";return interval.durationDays<=3&&baselineSamples>=8?"medium":"low"}
export function buildRetrospectiveSamples(intervals:MeterIntervalSample[],weather:DailyWeather[],baseline:number,baselineSamples:number,timeZone="Europe/Budapest"):RetrospectiveSample[]{return intervals.flatMap(interval=>{if(interval.dataWarning?.startsWith("Negatív fogyasztási"))return[];const summary=intervalWeather(interval,weather,timeZone);if(!summary||summary.coverageRatio<0.99)return[];const aboveBaseline=Math.max(interval.observedDailyGridImportKwh-baseline,0);return[{...interval,sampleType:"retrospective" as const,weatherMeanTempC:summary.meanC,weatherMinTempC:summary.minC,weatherMaxTempC:summary.maxC,estimatedBaseGridImportKwhDay:baseline,gridImportAboveBaselineKwhDay:aboveBaseline,confidence:historicalConfidence(interval,true,baselineSamples),weatherDayCount:summary.dayCount,weatherCoverageRatio:summary.coverageRatio}]})}
export const temperatureBucket=(value:number)=>value>10?"> 10 °C":value>5?"5–10 °C":value>0?"0–5 °C":value>-5?"−5–0 °C":"< −5 °C";
