import type { BucketAnalysis } from "./period-analysis";
import type { HeatSource, HeatingLog, HeatingProfile, HeatingRecommendation, RecommendationConfidence } from "./types";

export interface OptimizationTrial {parameter:"power"|"flow"|null;currentFlowC:number|null;proposedFlowC:number|null;currentPowerKw:number;proposedPowerKw:number;durationHours:number;confidence:RecommendationConfidence;reason:string;reasons:string[];sourcePriority:"actual_log"|"retrospective"|"physical_model"|"insufficient_data"}
const roundHalf=(value:number)=>Math.round(value*2)/2;
export function optimizationTrial(profile:HeatingProfile,source:HeatSource,logs:HeatingLog[],recommendation:HeatingRecommendation,context:BucketAnalysis|null,outdoorC:number):OptimizationTrial{
  const currentPower=source.maximum_configurable_power_kw,currentFlow=source.current_flow_temperature_c??null,comfortable=logs.filter(log=>log.comfort_result==="comfortable"&&log.outdoor_temperature_mean_c!=null&&Math.abs(log.outdoor_temperature_mean_c-outdoorC)<=3),failed=logs.filter(log=>log.comfort_result==="too_cold"&&log.outdoor_temperature_mean_c!=null&&Math.abs(log.outdoor_temperature_mean_c-outdoorC)<=3);
  const loadEquivalent=context?.averageElectricalLoadEquivalentKw??null,demand=recommendation.estimatedHeatDemandKw,required=Math.max(demand??0,loadEquivalent==null?0:loadEquivalent*1.5,source.minimum_configurable_power_kw??0.5),candidate=Math.max(required,roundHalf(currentPower*.7));
  const powerTarget=Math.min(currentPower,roundHalf(candidate));
  const blocked=failed.some(log=>log.boiler_max_power_kw>=powerTarget&&log.flow_temperature_c>=(currentFlow??log.flow_temperature_c));
  const referenceMatchesCurrentFlow=recommendation.referenceLog!=null&&currentFlow!=null&&Math.abs(recommendation.referenceLog.flow_temperature_c-currentFlow)<=0.25;
  if(comfortable.length&&recommendation.referenceLog&&referenceMatchesCurrentFlow&&recommendation.referenceLog.boiler_max_power_kw<currentPower&&!blocked)return{parameter:"power",currentFlowC:currentFlow,proposedFlowC:currentFlow,currentPowerKw:currentPower,proposedPowerKw:recommendation.referenceLog.boiler_max_power_kw,durationHours:24,confidence:recommendation.confidence,reason:"Azonos előremenő mellett már sikeres tényleges teljesítménykorlátot próbálunk meg.",reasons:[`${comfortable.length} hasonló megfelelő komfortú tényleges log.`,"A referencia előremenője megegyezik a jelenlegi beállítással, ezért nem jön létre nem tesztelt konfigurációpár."],sourcePriority:"actual_log"};
  if(powerTarget<currentPower&&required<currentPower*.65&&!blocked)return{parameter:"power",currentFlowC:currentFlow,proposedFlowC:currentFlow,currentPowerKw:currentPower,proposedPowerKw:powerTarget,durationHours:24,confidence:context?.confidence??"low",reason:"A becsült terhelési kontextus a jelenlegi korlátnál alacsonyabb; egyetlen kontrollált teljesítménylépés próbálható.",reasons:[loadEquivalent==null?"Nincs közvetlen retrospektív terhelési minta.":`A tartomány átlagos villamos terhelési megfelelője ${loadEquivalent.toFixed(1)} kW.`,"Az előremenő változatlan marad.","A PA02 értéket a felhasználónak kell manuálisan beállítania; nincs feltételezett kW/fűtőrúd átváltás."],sourcePriority:context?"retrospective":"physical_model"};
  if(recommendation.referenceLog&&recommendation.recommendedFlowTemperatureC!=null&&currentFlow!=null&&recommendation.recommendedFlowTemperatureC<currentFlow)return{parameter:"flow",currentFlowC:currentFlow,proposedFlowC:recommendation.recommendedFlowTemperatureC,currentPowerKw:currentPower,proposedPowerKw:currentPower,durationHours:24,confidence:recommendation.confidence,reason:"A tényleges sikeres referencia alapján kis előremenő-lépés próbálható, változatlan teljesítménykorláttal.",reasons:["Egyszerre csak az előremenő változik."],sourcePriority:"actual_log"};
  return{parameter:null,currentFlowC:currentFlow,proposedFlowC:currentFlow,currentPowerKw:currentPower,proposedPowerKw:currentPower,durationHours:24,confidence:"low",reason:blocked?"Hasonló vagy kedvezőbb körülmények között ez a lefelé lépés már elégtelen komfortot adott; nem ismételjük meg.":"Nincs elegendő adat biztonságos következő lefelé optimalizálási próbához.",reasons:[blocked?"A too_cold eredmény tiltja az azonos vagy gyengébb konfiguráció újbóli próbáját.":"További tényleges fűtési megfigyelés szükséges."],sourcePriority:"insufficient_data"};
}
export const trialSucceeded=(log:HeatingLog)=>log.comfort_result==="comfortable"&&(log.actual_indoor_min_temp_c==null||log.actual_indoor_min_temp_c>=log.target_indoor_temperature_c-0.5);
