import type { SettlementPeriod, TariffSettings } from "@/lib/types";
import { heatingSeasonForDate } from "@/lib/seasonal-forecast";
import { localIsoDate } from "@/lib/weather/date";
import type { HeatingLog } from "./types";
import { median, temperatureBucket, type MeterIntervalSample, type RetrospectiveSample, type HistoricalConfidence } from "./historical-calibration";

export interface AssignedInterval<T extends MeterIntervalSample = RetrospectiveSample> { sample:T; periodId:string|null; crossPeriod:boolean }
export const periodLabel=(period:SettlementPeriod)=>`${new Date(period.start_date).getFullYear()}/${period.end_date?new Date(period.end_date).getFullYear():new Date(period.start_date).getFullYear()+1}`;
function periodAt(date:string,periods:SettlementPeriod[]){return [...periods].filter(p=>p.start_date<=date&&(!p.end_date||date<=p.end_date)).sort((a,b)=>b.start_date.localeCompare(a.start_date))[0]??null}
const localCalendarDate=(timestamp:string,timeZone:string)=>{const [year,month,day]=localIsoDate(new Date(timestamp),timeZone).split("-").map(Number);return new Date(year,month-1,day,12)};
export function logsForSettlementPeriod(logs:HeatingLog[],period:SettlementPeriod,timeZone="Europe/Budapest"){return logs.filter(log=>{const date=/^\d{4}-\d{2}-\d{2}$/.test(log.log_date)?log.log_date:localIsoDate(new Date(log.log_date),timeZone);return period.start_date<=date&&(!period.end_date||date<=period.end_date)})}
export function assignIntervalsToPeriods<T extends MeterIntervalSample>(samples:T[],periods:SettlementPeriod[],timeZone="Europe/Budapest"):AssignedInterval<T>[]{return samples.map(sample=>{const start=periodAt(localIsoDate(new Date(sample.start),timeZone),periods),end=periodAt(localIsoDate(new Date(sample.end),timeZone),periods),crossPeriod=!!start&&!!end&&start.id!==end.id;return{sample,periodId:crossPeriod?null:start?.id===end?.id?start?.id??null:null,crossPeriod}})}
export const filterAssignedIntervals=<T extends MeterIntervalSample>(assigned:AssignedInterval<T>[],periodId:string|null)=>periodId?assigned.filter(x=>x.periodId===periodId):assigned;
const average=(values:number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
export interface AggregateHistoricalConfidence{confidence:HistoricalConfidence;usableCount:number;warningCount:number;highCount:number;mediumCount:number;lowCount:number;reason:string}
export function aggregateHistoricalConfidence(samples:RetrospectiveSample[]):AggregateHistoricalConfidence{const warningCount=samples.filter(x=>!!x.dataWarning).length,usable=samples.filter(x=>!x.dataWarning),highCount=usable.filter(x=>x.confidence==="high").length,mediumCount=usable.filter(x=>x.confidence==="medium").length,lowCount=usable.filter(x=>x.confidence==="low").length;let confidence:HistoricalConfidence="low";if(usable.length>=5&&mediumCount>=3&&highCount+mediumCount>=Math.ceil(usable.length*2/3)&&lowCount<=Math.floor(usable.length/3)&&warningCount===0)confidence="high";else if(usable.length>=2&&highCount+mediumCount>=1)confidence="medium";const distribution=`${samples.length} retrospektív minta: ${highCount} magas, ${mediumCount} közepes, ${lowCount} alacsony megbízhatóságú${warningCount?`, ${warningCount} warning miatt nem erősítő minta`:""}.`,reason=confidence==="high"?`${distribution} Sok, egymással összhangban lévő, megfelelő minőségű retrospektív minta támasztja alá a trendet; ez nem jelenti a korabeli kazánbeállítás vagy komfort ismeretét.`:distribution;return{confidence,usableCount:usable.length,warningCount,highCount,mediumCount,lowCount,reason}}
export interface AnalysisSummary{sampleCount:number;usableSampleCount:number;meanOutdoorC:number|null;medianGridImportKwhDay:number|null;meanGridImportKwhDay:number|null;medianHeatingExcessKwhDay:number|null;meanHeatingExcessKwhDay:number|null;coldest:RetrospectiveSample|null;warningCount:number;confidence:HistoricalConfidence;confidenceReason:string}
export function analysisSummary(all:AssignedInterval<MeterIntervalSample>[],usable:AssignedInterval<RetrospectiveSample>[]):AnalysisSummary{const rows=usable.map(x=>x.sample),aggregate=aggregateHistoricalConfidence(rows);return{sampleCount:all.length,usableSampleCount:rows.length,meanOutdoorC:average(rows.map(x=>x.weatherMeanTempC)),medianGridImportKwhDay:median(rows.map(x=>x.observedDailyGridImportKwh)),meanGridImportKwhDay:average(rows.map(x=>x.observedDailyGridImportKwh)),medianHeatingExcessKwhDay:median(rows.map(x=>x.estimatedHeatingExcessKwhDay)),meanHeatingExcessKwhDay:average(rows.map(x=>x.estimatedHeatingExcessKwhDay)),coldest:rows.length?[...rows].sort((a,b)=>a.weatherMeanTempC-b.weatherMeanTempC)[0]:null,warningCount:aggregate.warningCount,confidence:aggregate.confidence,confidenceReason:aggregate.reason}}
export interface BucketAnalysis{bucket:string;sampleCount:number;actualLogCount:number;medianGridImportKwhDay:number|null;medianHeatingExcessKwhDay:number|null;averageElectricalLoadEquivalentKw:number|null;confidence:HistoricalConfidence;confidenceReason:string}
export const BUCKETS=["> 10 °C","5–10 °C","0–5 °C","−5–0 °C","< −5 °C"];
export function bucketAnalysis(samples:RetrospectiveSample[],logs:HeatingLog[]=[]):BucketAnalysis[]{return BUCKETS.map(bucket=>{const rows=samples.filter(x=>temperatureBucket(x.weatherMeanTempC)===bucket),actual=logs.filter(x=>x.outdoor_temperature_mean_c!=null&&temperatureBucket(x.outdoor_temperature_mean_c)===bucket).length,excess=median(rows.map(x=>x.estimatedHeatingExcessKwhDay)),aggregate=aggregateHistoricalConfidence(rows);return{bucket,sampleCount:rows.length,actualLogCount:actual,medianGridImportKwhDay:median(rows.map(x=>x.observedDailyGridImportKwh)),medianHeatingExcessKwhDay:excess,averageElectricalLoadEquivalentKw:excess==null?null:excess/24,confidence:aggregate.confidence,confidenceReason:aggregate.reason}})}
export interface PeriodAnalysis{period:SettlementPeriod;label:string;summary:AnalysisSummary;buckets:BucketAnalysis[];samples:RetrospectiveSample[]}
export function periodAnalyses(intervals:MeterIntervalSample[],samples:RetrospectiveSample[],periods:SettlementPeriod[],logs:HeatingLog[]=[],timeZone="Europe/Budapest"):PeriodAnalysis[]{const all=assignIntervalsToPeriods(intervals,periods,timeZone),usable=assignIntervalsToPeriods(samples,periods,timeZone);return [...periods].sort((a,b)=>b.start_date.localeCompare(a.start_date)).map(period=>{const periodAll=all.filter(x=>x.periodId===period.id),periodUsable=usable.filter(x=>x.periodId===period.id),periodLogs=logsForSettlementPeriod(logs,period,timeZone);return{period,label:periodLabel(period),summary:analysisSummary(periodAll,periodUsable),buckets:bucketAnalysis(periodUsable.map(x=>x.sample),periodLogs),samples:periodUsable.map(x=>x.sample)}})}
export interface WeatherNormalizedComparison{olderLabel:string;newerLabel:string;comparableBucketCount:number;gridImportChangePercent:number|null;heatingExcessChangePercent:number|null;confidence:HistoricalConfidence}
export function weatherNormalizedComparison(older:PeriodAnalysis,newer:PeriodAnalysis):WeatherNormalizedComparison{const pairs=BUCKETS.map(bucket=>[older.buckets.find(x=>x.bucket===bucket)!,newer.buckets.find(x=>x.bucket===bucket)!]).filter(([a,b])=>a.confidence!=="low"&&b.confidence!=="low"&&a.sampleCount>=2&&b.sampleCount>=2&&a.medianGridImportKwhDay!=null&&a.medianGridImportKwhDay>0&&b.medianGridImportKwhDay!=null),changes=pairs.map(([a,b])=>(b.medianGridImportKwhDay!-a.medianGridImportKwhDay!)/a.medianGridImportKwhDay!*100),heat=pairs.filter(([a,b])=>a.medianHeatingExcessKwhDay!=null&&a.medianHeatingExcessKwhDay>0&&b.medianHeatingExcessKwhDay!=null).map(([a,b])=>(b.medianHeatingExcessKwhDay!-a.medianHeatingExcessKwhDay!)/a.medianHeatingExcessKwhDay!*100);return{olderLabel:older.label,newerLabel:newer.label,comparableBucketCount:pairs.length,gridImportChangePercent:pairs.length>=2?average(changes):null,heatingExcessChangePercent:heat.length>=2?average(heat):null,confidence:pairs.length>=3?"high":pairs.length>=2?"medium":"low"}}
export interface HeatingSeasonAnalysis{label:string;sampleCount:number;meanOutdoorC:number|null;observedGridImportKwh:number;estimatedBaseGridImportKwh:number;estimatedHeatingExcessKwh:number;coldest:RetrospectiveSample|null;confidence:HistoricalConfidence;warningCount:number;confidenceReason:string}
export interface AssignedHeatingSeason{sample:RetrospectiveSample;seasonLabel:string|null;crossSeason:boolean}
export function assignIntervalsToHeatingSeasons(samples:RetrospectiveSample[],tariff:TariffSettings,timeZone="Europe/Budapest"):AssignedHeatingSeason[]{return samples.map(sample=>{const start=localCalendarDate(sample.start,timeZone),end=localCalendarDate(sample.end,timeZone),startRange=heatingSeasonForDate(start,tariff),endRange=heatingSeasonForDate(end,tariff),inside=startRange.label===endRange.label&&start>=startRange.start&&end<=startRange.end;return{sample,seasonLabel:inside?startRange.label:null,crossSeason:!inside}})}
export function heatingSeasonAnalyses(samples:RetrospectiveSample[],tariff:TariffSettings,timeZone="Europe/Budapest"):HeatingSeasonAnalysis[]{const grouped=new Map<string,RetrospectiveSample[]>();for(const assigned of assignIntervalsToHeatingSeasons(samples,tariff,timeZone)){if(assigned.crossSeason||!assigned.seasonLabel)continue;grouped.set(assigned.seasonLabel,[...(grouped.get(assigned.seasonLabel)??[]),assigned.sample])}return[...grouped].map(([label,rows])=>{const aggregate=aggregateHistoricalConfidence(rows);return{label,sampleCount:rows.length,meanOutdoorC:average(rows.map(x=>x.weatherMeanTempC)),observedGridImportKwh:rows.reduce((s,x)=>s+x.observedGridImportKwh,0),estimatedBaseGridImportKwh:rows.reduce((s,x)=>s+x.estimatedBaseGridImportKwhDay*x.durationDays,0),estimatedHeatingExcessKwh:rows.reduce((s,x)=>s+x.estimatedHeatingExcessKwhDay*x.durationDays,0),coldest:[...rows].sort((a,b)=>a.weatherMeanTempC-b.weatherMeanTempC)[0]??null,confidence:aggregate.confidence,warningCount:aggregate.warningCount,confidenceReason:aggregate.reason}}).sort((a,b)=>b.label.localeCompare(a.label))}
