import { describe, expect, it } from "vitest";
import { estimatedBuildingHeatDemand, heatingRecommendation, interpolateTemperature, isValidBoschPa02, isValidBoschPa03, similarHeatingLogs, validateHeatingLog } from "./recommendation";
import type { HeatSource, HeatingLog, HeatingProfile } from "./types";
const profile: HeatingProfile={target_indoor_temperature_c:21,design_heat_loss_kw:7,design_indoor_temperature_c:21,design_outdoor_temperature_c:-13,heat_distribution_type:"radiators",weather_timezone:"Europe/Budapest",optimization_enabled:true};
const source: HeatSource={manufacturer:"Bosch",model:"Tronic Heat 3500",heat_source_type:"electric_boiler",nominal_power_kw:15,maximum_configurable_power_kw:7,has_buffer_tank:false};
const log=(overrides:Partial<HeatingLog>={}):HeatingLog=>({log_date:"2026-01-01",outdoor_temperature_mean_c:4,temperature_source:"manual",target_indoor_temperature_c:21,flow_temperature_c:43,boiler_max_power_kw:7,thermostat_switching_sensitivity_c:0.2,comfort_result:"comfortable",...overrides});
describe("heating optimization",()=>{
 it("lineáris hőigényt számol",()=>expect(estimatedBuildingHeatDemand(7,21,-13,21,4)).toBeCloseTo(3.5));
 it("külön kezeli a tervezési és cél beltéri hőmérsékletet",()=>expect(estimatedBuildingHeatDemand(7,21,-13,20,4)).toBeCloseTo(7*16/34));
 it("tervezési külső hőmérséklet nélkül nem számol",()=>expect(estimatedBuildingHeatDemand(7,21,null,20,4)).toBeNull());
 it("min/max értékből interpolál",()=>expect(interpolateTemperature(2,8)).toBe(5));
 it("hasonló napokat választ",()=>expect(similarHeatingLogs([log(),log({outdoor_temperature_mean_c:-5})],5,21,15)).toHaveLength(1));
 it("kis lépésű előremenőt ajánl",()=>expect(heatingRecommendation(profile,source,[log()],5).recommendedFlowTemperatureC).toBe(42));
 it("a teljesítményt a konfigurált maximumra korlátozza",()=>expect(heatingRecommendation({...profile,design_heat_loss_kw:30},source,[],0).recommendedBoilerPowerKw).toBe(7));
 it("1-2 referencia medium, legalább 3 konzisztens high",()=>{expect(heatingRecommendation(profile,source,[log()],4).confidence).toBe("medium"); expect(heatingRecommendation(profile,source,[log(),log(),log()],4).confidence).toBe("high")});
 it("gyenge beltéri minimum nem emel high confidence-re",()=>expect(heatingRecommendation(profile,source,[log({actual_indoor_min_temp_c:19}),log(),log()],4).confidence).toBe("medium"));
 it("hiányzó adatoknál nem talál ki előremenőt",()=>expect(heatingRecommendation({...profile,design_heat_loss_kw:null},source,[],4).recommendedFlowTemperatureC).toBeNull());
 it("hibás logot kizár",()=>expect(similarHeatingLogs([log({flow_temperature_c:120})],4,21,15)).toHaveLength(0));
 it("a too cold megfigyelés nem engedi vissza ugyanazt vagy gyengébb párt",()=>expect(heatingRecommendation(profile,source,[log({flow_temperature_c:42}),log({flow_temperature_c:44,comfort_result:"too_cold"})],4).recommendedFlowTemperatureC).toBeNull());
 it("elutasítja a névleges teljesítmény túllépését",()=>expect(validateHeatingLog(log({boiler_max_power_kw:16}),15)).not.toHaveLength(0));
 it("elutasítja a konfigurált maximum túllépését",()=>expect(validateHeatingLog(log({boiler_max_power_kw:8}),15,7)).not.toHaveLength(0));
 it("nem kombinál külön logokból nem tesztelt minimumokat",()=>{const result=heatingRecommendation(profile,source,[log({flow_temperature_c:42,boiler_max_power_kw:7}),log({flow_temperature_c:44,boiler_max_power_kw:5})],4);expect(["42/7","44/5"]).toContain(`${result.recommendedFlowTemperatureC}/${result.recommendedBoilerPowerKw}`)});
 it("egy lépésben csak egy paraméter csökken",()=>{const result=heatingRecommendation(profile,source,[log({outdoor_temperature_mean_c:4,flow_temperature_c:43,boiler_max_power_kw:7})],5);expect(result.recommendedFlowTemperatureC).toBe(42);expect(result.recommendedBoilerPowerKw).toBe(7)});
 it("azonos erősségű too cold párt nem ajánl",()=>expect(heatingRecommendation(profile,source,[log({flow_temperature_c:44,boiler_max_power_kw:7,comfort_result:"too_cold"})],4).recommendedFlowTemperatureC).toBeNull());
 it("44/5 too cold nem tiltja a 44/7 comfortable párt",()=>expect(heatingRecommendation(profile,source,[log({flow_temperature_c:44,boiler_max_power_kw:5,comfort_result:"too_cold"}),log({flow_temperature_c:44,boiler_max_power_kw:7})],4).recommendedFlowTemperatureC).toBe(44));
 it("kapacitásfigyelmeztetést ad configured max felett",()=>expect(heatingRecommendation({...profile,design_heat_loss_kw:30},source,[],0).capacityWarning).not.toBeNull());
 it("configured max fölötti régi successful logot nem clampel referenciává",()=>{const result=heatingRecommendation(profile,source,[log({flow_temperature_c:42,boiler_max_power_kw:10})],4);expect(result.recommendedFlowTemperatureC).toBeNull();expect(result.referenceLog).toBeNull();expect(result.recommendedBoilerPowerKw).not.toBe(10)});
 it("outdoor >= target esetén nincs fűtési igény",()=>{const result=heatingRecommendation(profile,source,[],21);expect(result.noHeatingDemand).toBe(true);expect(result.estimatedHeatDemandKw).toBe(0)});
 it("PA02 csak 1–6",()=>{expect(isValidBoschPa02(1)).toBe(true);expect(isValidBoschPa02(6)).toBe(true);expect(isValidBoschPa02(7)).toBe(false)});
 it("PA03 csak 0–4",()=>{expect(isValidBoschPa03(0)).toBe(true);expect(isValidBoschPa03(4)).toBe(true);expect(isValidBoschPa03(5)).toBe(false)});
});
