import{describe,expect,it,vi}from"vitest";import{backfillHistoricalWeather,contiguousRanges,missingWeatherDates,weatherRanges}from"./weather-backfill";import{localDayWindow,zonedMidnightUtc}from"@/lib/weather/date";
const archive=(start:string,hours:number)=>({ok:true,json:async()=>({hourly:{time:Array.from({length:hours},(_,i)=>new Date(Date.parse(start)+i*3600000).toISOString().slice(0,16)),temperature_2m:Array(hours).fill(2),wind_speed_10m:Array(hours).fill(3),shortwave_radiation:Array(hours).fill(0),cloud_cover:Array(hours).fill(50)}})}),args=(date:string,saveRows=vi.fn().mockResolvedValue(undefined),fetcher=vi.fn())=>({saveRows,stored:[],start:date,end:date,referenceDate:"2026-08-05",latitude:47,longitude:19,timeZone:"Europe/Budapest",fetcher});
describe("heating hourly weather backfill",()=>{
 it("does not refetch a complete day",()=>{const stored=Array.from({length:24},(_,i)=>({observed_at:`2026-01-01T${String(i).padStart(2,"0")}:00:00Z`,quality_status:"complete"}));expect(missingWeatherDates("2026-01-01","2026-01-01",stored,"UTC")).toEqual([])});
 it("groups missing dates into 29-day ranges so UTC expansion stays within 31 dates",()=>{const values=Array.from({length:30},(_,i)=>`2026-01-${String(i+1).padStart(2,"0")}`);expect(contiguousRanges(values).map(x=>[x.start,x.end])).toEqual([["2026-01-01","2026-01-29"],["2026-01-30","2026-01-30"]])});
 it("uses forecast for yesterday and archive for older dates",()=>{expect(weatherRanges(["2026-08-04"],"2026-08-05")[0].source).toBe("open_meteo_forecast");expect(weatherRanges(["2026-01-01"],"2026-08-05")[0].source).toBe("open_meteo_archive")});
 it.each([["2026-01-10",24],["2026-07-10",24],["2026-03-29",23],["2025-10-26",25]] as const)("stores exactly the Budapest local day %s (%i hours)",async(date,hours)=>{const start=zonedMidnightUtc(date,"Europe/Budapest").getTime()-86400000,saveRows=vi.fn().mockResolvedValue(undefined),fetcher=vi.fn().mockResolvedValue(archive(new Date(start).toISOString(),72)),result=await backfillHistoricalWeather(args(date,saveRows,fetcher));expect(result.savedHours).toBe(hours);expect(saveRows.mock.calls[0][0]).toHaveLength(hours);expect(saveRows.mock.calls[0][0].every((x:{source:string})=>x.source==="open_meteo_archive")).toBe(true);expect(localDayWindow(date,"Europe/Budapest").durationHours).toBe(hours)});
 it("uses forecast past_days for yesterday",async()=>{const start=zonedMidnightUtc("2026-08-04","Europe/Budapest").getTime()-86400000,saveRows=vi.fn().mockResolvedValue(undefined),fetcher=vi.fn().mockResolvedValue(archive(new Date(start).toISOString(),72));await backfillHistoricalWeather(args("2026-08-04",saveRows,fetcher));const url=new URL(fetcher.mock.calls[0][0]);expect(url.hostname).toBe("api.open-meteo.com");expect(url.searchParams.get("past_days")).toBe("7");expect(saveRows.mock.calls[0][0].every((x:{source:string})=>x.source==="open_meteo_forecast")).toBe(true)});
 it("uses an expanded UTC archive request and never stores outside hours",async()=>{const saveRows=vi.fn().mockResolvedValue(undefined),fetcher=vi.fn().mockResolvedValue(archive("2025-12-31T00:00:00Z",72));await backfillHistoricalWeather(args("2026-01-01",saveRows,fetcher));const url=new URL(fetcher.mock.calls[0][0]);expect(url.searchParams.get("start_date")).toBe("2025-12-31");expect(url.searchParams.get("end_date")).toBe("2026-01-02");expect(saveRows.mock.calls[0][0][0].at).toBe("2025-12-31T23:00:00.000Z")});
 it("second rebuild does not request a now-complete day",async()=>{const start=zonedMidnightUtc("2026-01-01","Europe/Budapest").getTime(),stored=Array.from({length:24},(_,i)=>({observed_at:new Date(start+i*3600000).toISOString(),quality_status:"complete"})),fetcher=vi.fn();expect(await backfillHistoricalWeather({...args("2026-01-01",vi.fn(),fetcher),stored})).toMatchObject({requestedDays:0,requestedRanges:0,savedHours:0});expect(fetcher).not.toHaveBeenCalled()});
});
