import {NextResponse} from "next/server";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {addCalendarDays,zonedMidnightUtc} from "@/lib/weather/date";
import {runHeatingAnalysisRebuild,type HeatingAnalysisRepository,type HeatingSource} from "@/lib/heating/rebuild-service";
import {HEATING_MODEL_VERSION} from "@/lib/heating/analysis-service";
import type {WeatherHour} from "@/lib/heating/eon-analysis";
export const runtime="nodejs";export const maxDuration=300;
const headers={"Cache-Control":"private, no-store, max-age=0, must-revalidate"};type Admin=NonNullable<ReturnType<typeof createAdminClient>>;
type EonRow={interval_start_utc:string;local_date:string;import_kwh:number|string;export_kwh:number|string};type PvRow={local_date:string;energy_kwh:number|string;quality_status:string};type PeriodRow={enabled_at:string;disabled_at:string|null};type ValidationRow={local_date:string;label:"definitely_on"|"definitely_off"|"uncertain"};type WeatherRow={observed_at:string;temperature_c:number|string;wind_speed_kmh:number|string|null;shortwave_radiation_wm2:number|string|null;cloud_cover_percent:number|string|null;quality_status:string};
async function pages<T>(load:(from:number)=>PromiseLike<{data:T[]|null;error:unknown}>){const rows:T[]=[];for(let from=0;;from+=1000){const result=await load(from);if(result.error)throw new Error("INPUT_READ_FAILED");rows.push(...(result.data??[]));if(!result.data||result.data.length<1000)return rows}}
function repository(admin:Admin):HeatingAnalysisRepository{let cachedTimeZone:string|null=null;const profile=async(userId:string)=>{const[profileResult,sourceResult]=await Promise.all([admin.from("heating_profiles").select("weather_latitude,weather_longitude,weather_timezone,target_indoor_temperature_c").eq("user_id",userId).single(),admin.from("heat_sources").select("nominal_power_kw,maximum_configurable_power_kw,heat_source_type").eq("user_id",userId).maybeSingle()]);if(profileResult.error||!profileResult.data||sourceResult.error)throw new Error("INPUT_READ_FAILED");const data=profileResult.data,source=sourceResult.data,timeZone=String(data.weather_timezone||"Europe/Budapest");cachedTimeZone=timeZone;const configured=source?.maximum_configurable_power_kw??source?.nominal_power_kw;return{latitude:data.weather_latitude==null?null:Number(data.weather_latitude),longitude:data.weather_longitude==null?null:Number(data.weather_longitude),timeZone,targetIndoorC:Number(data.target_indoor_temperature_c),heatSourceType:source?.heat_source_type??null,maximumElectricPowerKw:configured==null?null:Number(configured)}};const weatherRows=async(userId:string,start:string,end:string)=>{const timeZone=cachedTimeZone??(await profile(userId)).timeZone,from=zonedMidnightUtc(start,timeZone).toISOString(),to=zonedMidnightUtc(addCalendarDays(end,1),timeZone).toISOString();return pages<WeatherRow>(n=>admin.from("heating_weather_hourly").select("observed_at,temperature_c,wind_speed_kmh,shortwave_radiation_wm2,cloud_cover_percent,quality_status").eq("user_id",userId).gte("observed_at",from).lt("observed_at",to).order("observed_at").range(n,n+999))};const mapWeather=(rows:WeatherRow[])=>rows.map(x=>({at:x.observed_at,temperatureC:Number(x.temperature_c),windSpeedKmh:x.wind_speed_kmh==null?null:Number(x.wind_speed_kmh),shortwaveRadiationWm2:x.shortwave_radiation_wm2==null?null:Number(x.shortwave_radiation_wm2),cloudCoverPercent:x.cloud_cover_percent==null?null:Number(x.cloud_cover_percent)})) as WeatherHour[];const weather=async(userId:string,start:string,end:string)=>mapWeather(await weatherRows(userId,start,end));return{
 async claim(userId){const{data,error}=await admin.rpc("claim_heating_analysis",{target_user_id:userId});if(error)throw new Error("ANALYSIS_LOCK_FAILED");return data===true},async release(userId){await admin.rpc("release_heating_analysis",{target_user_id:userId})},profile,
 async source(userId,start,end){const[eon,pv,periods,validations,weatherData]=await Promise.all([pages<EonRow>(n=>admin.from("eon_interval_readings").select("interval_start_utc,local_date,import_kwh,export_kwh").eq("user_id",userId).gte("local_date",start).lte("local_date",end).order("interval_start_utc").range(n,n+999)),pages<PvRow>(n=>admin.from("growatt_daily_energy").select("local_date,energy_kwh,quality_status").eq("user_id",userId).gte("local_date",start).lte("local_date",end).range(n,n+999)),pages<PeriodRow>(n=>admin.from("heating_operation_periods").select("enabled_at,disabled_at").eq("user_id",userId).order("enabled_at").range(n,n+999)),pages<ValidationRow>(n=>admin.from("heating_day_validations").select("local_date,label").eq("user_id",userId).gte("local_date",start).lte("local_date",end).range(n,n+999)),weatherRows(userId,start,end)]);return{eon:eon.map(x=>({at:x.interval_start_utc,localDate:x.local_date,importKwh:Number(x.import_kwh),exportKwh:Number(x.export_kwh)})),pv:pv.map(x=>({localDate:x.local_date,energyKwh:Number(x.energy_kwh),qualityStatus:x.quality_status})),periods:periods.map(x=>({enabledAt:x.enabled_at,disabledAt:x.disabled_at})),validations:validations.map(x=>({localDate:x.local_date,label:x.label})),storedWeather:weatherData.map(x=>({observed_at:x.observed_at,quality_status:x.quality_status})),weather:mapWeather(weatherData)} as HeatingSource},
 async saveWeather(userId,rows){const{error}=await admin.rpc("save_heating_weather_hourly",{target_user_id:userId,rows:rows.map(x=>({observed_at:x.at,temperature_c:x.temperatureC,wind_speed_kmh:x.windSpeedKmh,shortwave_radiation_wm2:x.shortwaveRadiationWm2,cloud_cover_percent:x.cloudCoverPercent,source:x.source}))});if(error)throw new Error("HEATING_WEATHER_WRITE_FAILED")},weather,
 async saveAnalysis(userId,features,model){const{data,error}=await admin.rpc("save_heating_analysis",{target_user_id:userId,target_model_version:HEATING_MODEL_VERSION,features,model});if(error)throw new Error("ANALYSIS_WRITE_FAILED");return data}
}}
export async function POST(){const client=await createClient();if(!client)return NextResponse.json({error:{code:"UNAUTHORIZED"}},{status:401,headers});const{data:{user}}=await client.auth.getUser();if(!user)return NextResponse.json({error:{code:"UNAUTHORIZED"}},{status:401,headers});const admin=createAdminClient();if(!admin)return NextResponse.json({error:{code:"ANALYSIS_NOT_CONFIGURED"}},{status:503,headers});try{const result=await runHeatingAnalysisRebuild({repository:repository(admin),userId:user.id});return NextResponse.json(result,{headers})}catch(error){const code=error instanceof Error?error.message:"HEATING_ANALYSIS_REBUILD_FAILED",status=code==="ANALYSIS_ALREADY_RUNNING"?409:code==="ANALYSIS_RANGE_TOO_LARGE"?413:503;return NextResponse.json({error:{code}},{status,headers})}}
