import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { analyzeSolarMonth, summarizeSolarPeriod, type SolarMonthInput } from "@/lib/solar/consumption-analysis";
import { SolarConsumptionAnalysisContent, SolarMonthDetails } from "./consumption-analysis-section";

const input = (overrides: Partial<SolarMonthInput> = {}): SolarMonthInput => ({ yearMonth: "2026-07", currentYearMonth: "2026-08", meterTimezone: "Europe/Budapest", pvTimezone: "Europe/Budapest", gridImportKwh: 600, gridExportKwh: 400, meterDataQuality: "complete", pvProductionKwh: 1000, pvExpectedDays: 31, pvStoredDays: 31, pvCompleteDays: 31, pvProvisionalDays: 0, pvMissingDays: 0, pvInvalidDays: 0, pvPeriodStartLocalDate: "2026-07-01", pvPeriodEndLocalDate: "2026-07-31", meterCoverageStartAt: "2026-06-30T22:00:00.000Z", meterCoverageEndAt: "2026-07-31T22:00:00.000Z", meterCoverageStartLocalDate: "2026-07-01", meterCoverageEndLocalDate: "2026-08-01", meterCoversRequiredStart: true, meterCoversRequiredEnd: true, ...overrides });
const render = (...months: ReturnType<typeof analyzeSolarMonth>[]) => renderToStaticMarkup(<SolarConsumptionAnalysisContent months={months} summary={summarizeSolarPeriod(months)}/>);

describe("napelem és házfogyasztás UI", () => {
  it("teljes hónapnál becsült címkéket, mutatókat és csukott képletmagyarázatot ad", () => { const html = render(analyzeSolarMonth(input())); expect(html).toContain("Teljes adatsor"); expect(html).toContain("Becsült · helyben felhasználva"); expect(html).toContain("Hogyan számoljuk?"); expect(html).toContain("becslés marad"); expect(html).not.toContain("<details open"); });
  it("folyamatban lévő és időarányos hónapot megkülönböztet", () => { const html = render(analyzeSolarMonth(input({ yearMonth: "2026-08", pvExpectedDays: 3, pvStoredDays: 3, pvCompleteDays: 2, pvProvisionalDays: 1 })), analyzeSolarMonth(input({ yearMonth: "2026-06", meterDataQuality: "estimated", pvExpectedDays: 30, pvStoredDays: 30, pvCompleteDays: 30 }))); expect(html).toContain("Folyamatban"); expect(html).toContain("Becsült villanyórás felosztás"); expect(html).toContain("becsült, időarányos villanyórás adatok alapján"); });
  it("hiányos és ellentmondásos hónapnál nem jelenít számított százalékot", () => { const html = render(analyzeSolarMonth(input({ pvStoredDays: 30 })), analyzeSolarMonth(input({ yearMonth: "2026-06", gridExportKwh: 1100, pvExpectedDays: 30, pvStoredDays: 30, pvCompleteDays: 30 }))); expect(html).toContain("Hiányos inverteradat"); expect(html).toContain("Az adatok nem vethetők össze megbízhatóan"); expect(html).toContain("Nem számítható"); });
  it("a havi sor alapból csukott, részlete period mismatchnél mindkét coverage-et mutatja", () => { const month = analyzeSolarMonth(input({ yearMonth: "2026-08", pvPeriodStartLocalDate: "2026-08-01", pvPeriodEndLocalDate: "2026-08-03", meterCoverageStartAt: "2026-07-31T22:00:00.000Z", meterCoverageEndAt: "2026-08-02T08:00:00.000Z", meterCoversRequiredEnd: false })), html = render(month), details = renderToStaticMarkup(<SolarMonthDetails month={month}/>); expect(html).toContain('aria-expanded="false"'); expect(html).toContain("Az adatforrások időszaka nem egyezik"); expect(details).toContain("Growatt:"); expect(details).toContain("Villanyóra:"); expect(details).toContain("nem készül önfogyasztási becslés"); });
});
