import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";
import { SolarMonthlySnapshotHistory, type BackfillResult, type PublicSolarSnapshot } from "./monthly-snapshot-history";
const snapshot = (overrides: Partial<PublicSolarSnapshot> = {}): PublicSolarSnapshot => ({ year_month: "2026-07", timezone: "Europe/Budapest", grid_import_kwh: 500, grid_export_kwh: 180, pv_production_kwh: 1000, self_consumed_pv_kwh: 820, total_home_consumption_kwh: 1320, pv_self_consumption_ratio: .82, pv_coverage_ratio: .62, analysis_status: "complete", meter_data_quality: "complete", meter_source: "manual_readings", pv_expected_days: 31, pv_stored_days: 31, pv_complete_days: 31, pv_provisional_days: 0, pv_invalid_days: 0, meter_coverage_start_at: "2026-06-30T22:00:00Z", meter_coverage_end_at: "2026-07-31T22:00:00Z", algorithm_version: 1, calculated_at: "2026-08-01T10:00:00Z", ...overrides });
const render = (rows: PublicSolarSnapshot[], result: BackfillResult | null = null, open: string | null = null) => renderToStaticMarkup(<SolarMonthlySnapshotHistory startMonth="2025-01" endMonth="2026-07" active={false} initialRows={rows} initialResult={result} initiallyOpenMonth={open}/>);
describe("MonthlySnapshotHistory", () => {
  it("shows percentage and kWh plus all three highlights", () => { const html = render([snapshot()]); expect(html).toContain("82%"); expect(html).toContain("820 kWh"); expect(html).toContain("Legjobb arány"); expect(html).toContain("Legalacsonyabb arány"); expect(html).toContain("Legtöbb helyben felhasznált PV"); });
  it("has a default one-month selector and disabled P1 views", () => { const html = render([]); expect(html).toContain('<option value="1" selected="">1 lezárt hónap</option>'); expect(html.match(/disabled=""/g)?.length).toBeGreaterThanOrEqual(2); expect(html).toContain("P1 Meter szükséges"); });
  it("shows monthly and prior-year comparisons, coverage and Budapest recalculation time", () => { const html = render([snapshot({ year_month: "2025-07", pv_self_consumption_ratio: .7 }), snapshot()], null, "2026-07"); expect(html).toContain("Előző hónaphoz:"); expect(html).toContain("Előző év azonos hónapjához:"); expect(html).toContain("+12 százalékpont"); expect(html).toContain("Villanyóra coverage kezdete"); expect(html).toContain("31/31 nap"); expect(html).toContain("Complete/provisional/invalid: 31/0/0"); expect(html).toContain("12:00"); });
  it("renders skipped and failed backfill details in Hungarian", () => { const result: BackfillResult = { createdOrUpdatedMonths: 1, unchangedMonths: 2, skippedMonths: 1, failedMonths: 1, details: [{ yearMonth: "2026-05", status: "skipped", reason: "missing_pv_data" }, { yearMonth: "2026-06", status: "failed", reason: "database_write_failed" }] }; const html = render([], result); expect(html).toContain("1 mentett/frissített"); expect(html).toContain("Kihagyott és sikertelen"); expect(html).toContain("Hiányzik a Growatt-termelési adat"); expect(html).toContain("adatbázisba mentése nem sikerült"); });
  it("excludes zero-production months from every highlight", () => { const html = render([snapshot({ year_month: "2026-06", pv_production_kwh: 0, self_consumed_pv_kwh: 0, grid_export_kwh: 0, pv_self_consumption_ratio: null }), snapshot()]); expect(html).not.toContain("2026. június ·"); expect(html).toContain("2026. július · 82% · 820 kWh"); });
});
