"use client";
import React, { useCallback, useEffect, useRef, useState } from "react";
import { defaultGrowattSyncRange, getGrowattHistory, syncGrowattHistoryRange, type GrowattHistoryResponse, type GrowattSyncResponse } from "@/lib/growatt/history-ui";
import { inclusiveDays, validIsoDate } from "@/lib/growatt/historical";
import { suppressGrowattLatestRefresh } from "@/lib/growatt/ui";

export function GrowattHistoricalSyncCard() {
  const initial = defaultGrowattSyncRange(), [startDate, setStartDate] = useState(initial.startDate), [endDate, setEndDate] = useState(initial.endDate), [history, setHistory] = useState<GrowattHistoryResponse | null>(null), [result, setResult] = useState<GrowattSyncResponse | null>(null), [error, setError] = useState(""), [loading, setLoading] = useState(true), [syncing, setSyncing] = useState(false), running = useRef(false);
  const load = useCallback(async () => { setLoading(true); try { setHistory(await getGrowattHistory(startDate, endDate)); setError(""); } catch { setError("A historikus Growatt-adatok nem tölthetők be."); } finally { setLoading(false); } }, [startDate, endDate]);
  useEffect(() => { void load(); }, [load]);
  const days = validIsoDate(startDate) && validIsoDate(endDate) && startDate <= endDate ? inclusiveDays(startDate, endDate) : 0;
  async function sync() { if (running.current || days < 1 || days > 28) return; running.current = true; setSyncing(true); setError(""); try { const next = await syncGrowattHistoryRange(startDate, endDate); suppressGrowattLatestRefresh(); setResult(next); await load(); } catch (value) { setError(value instanceof Error && value.message === "SYNC_ALREADY_RUNNING" ? "Már fut egy historikus szinkron." : value instanceof Error && value.message === "HISTORY_DATABASE_WRITE_FAILED" ? "Az inverteradatok lekérése sikerült, de az adatbázisba mentés nem sikerült." : "A historikus szinkron nem fejeződött be. A korábban sikeresen mentett blokkok megmaradtak."); } finally { setSyncing(false); running.current = false; } }
  const rows = history?.rows ?? [], missing = days ? Math.max(0, days - rows.length) : 0;
  return <section className="mt-4 rounded-2xl border border-slate-200 p-4"><h3 className="font-black">Historikus termelési adatok</h3><p className="mt-1 text-xs text-slate-500">Kézi, legfeljebb 28 napos Growatt invertertermelés-szinkron. Nem módosít villanyórás adatot.</p>
    {loading && !history && <p role="status" className="mt-3 text-sm">Historikus adatok betöltése…</p>}
    {history && <dl className="mt-3 grid grid-cols-2 gap-2 text-sm sm:grid-cols-4"><Metric label="Legkorábbi eltárolt nap" value={history.summary?.earliestDate ?? "Nincs adat"}/><Metric label="Legutóbbi eltárolt nap" value={history.summary?.latestDate ?? "Nincs adat"}/><Metric label="Eltárolt napok" value={String(history.summary?.storedDays ?? rows.length)}/><Metric label="Hiányzó nap a tartományban" value={String(missing)}/><Metric label="Utolsó szinkron" value={history.summary?.lastSyncAt ? new Date(history.summary.lastSyncAt).toLocaleString("hu-HU") : "Nincs adat"}/></dl>}
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Kezdődátum<input className="field mt-1" type="date" value={startDate} onChange={event => setStartDate(event.target.value)}/></label><label className="text-sm font-bold">Záródátum<input className="field mt-1" type="date" value={endDate} onChange={event => setEndDate(event.target.value)}/></label></div><p className={`mt-2 text-xs ${days > 28 || days < 1 ? "text-red-700" : "text-slate-500"}`}>{days || 0} nap kiválasztva · maximum 28 nap</p><button className="primary mt-3 w-full sm:w-auto" disabled={syncing || days < 1 || days > 28} onClick={() => void sync()}>{syncing ? "Szinkronizálás…" : "Historikus adatok szinkronizálása"}</button>
    {result && <GrowattSyncResultPanel result={result}/>} {error && <p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}
  </section>;
}
export function GrowattSyncResultPanel({ result }: { result: GrowattSyncResponse }) { return <div role="status" className={`mt-3 rounded-xl p-3 text-sm ${result.partial ? "bg-amber-50 text-amber-900" : "bg-emerald-50 text-emerald-900"}`}><b>{result.partial ? "Részleges szinkron" : "Sikeres szinkron"}</b><p>{result.upsertedDays} nap mentve · {result.receivedValidDays} érvényes nap érkezett · {result.missingDays} nap hiányzik · {result.successfulChunks}/{result.chunks} blokk sikeres.</p>{result.invalidRecords > 0 && <p>{result.invalidRecords} hibás rekord kihagyva.</p>}{result.duplicateRecords > 0 && <p>{result.duplicateRecords} duplikált rekord összevonva.</p>}{result.retryRanges.length > 0 && <p>Újrapróbálható tartomány: {result.retryRanges.map(range => `${range.startDate}–${range.endDate}`).join(", ")}</p>}</div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl bg-slate-50 p-3"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words font-bold">{value}</dd></div>; }
