"use client";
import React, { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { EmptyState } from "@/components/ui";
import { budapestDate, getGrowattHistory, historyStatusLabel } from "@/lib/growatt/history-ui";
import { summarizeGrowattMonth, type GrowattDailyEnergyRow } from "@/lib/growatt/historical";
import { formatKwh } from "@/components/format";

export function GrowattPvHistorySection() {
  const today = budapestDate(), month = today.slice(0, 7), startDate = `${month}-01`, calendarEnd = new Date(Date.UTC(+month.slice(0,4), +month.slice(5,7), 0)).toISOString().slice(0,10), endDate = calendarEnd < today ? calendarEnd : today;
  const [rows, setRows] = useState<GrowattDailyEnergyRow[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  useEffect(() => { let active = true; getGrowattHistory(startDate, endDate).then(value => { if (active) { setRows(value.rows); setError(""); } }).catch(() => { if (active) setError("A Growatt PV-történet nem tölthető be."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [startDate, endDate]);
  const summary = useMemo(() => summarizeGrowattMonth(rows, startDate, endDate, today), [rows, startDate, endDate, today]);
  return <section className="card mt-5 overflow-hidden p-4 sm:p-5"><p className="text-xs font-bold text-emerald-700">KÜLÖN INVERTERADAT</p><h2 className="text-xl font-black">Napelemes invertertermelés</h2><p className="mt-1 text-xs text-slate-500">Growatt napi termelés; nem villanyórás visszatáplálás és nem önfogyasztás-számítás.</p>{loading ? <p role="status" className="mt-4">PV-adatok betöltése…</p> : error ? <p role="alert" className="mt-4 text-red-700">{error}</p> : rows.length === 0 ? <EmptyState title="Nincs historikus Growatt-adat"><Link className="font-bold text-emerald-700" href="/beallitasok#growatt-history">Szinkronizálás a Beállításokban</Link></EmptyState> : <><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5"><Metric label="Összes termelés" value={formatKwh(summary.totalEnergyKwh)}/><Metric label="Napi átlag" value={formatKwh(summary.dailyAverageKwh)}/><Metric label="Legerősebb nap" value={summary.strongestDay ? `${summary.strongestDay.localDate} · ${formatKwh(summary.strongestDay.energyKwh)}` : "Nincs adat"}/><Metric label="Lefedettség" value={`${summary.recordCount} / ${summary.expectedDays} nap`}/><Metric label="Állapot" value={historyStatusLabel(summary)}/></div>{summary.coverageRatio < 1 && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Részleges lefedettség: a havi összeg csak a rendelkezésre álló {summary.recordCount} nap termelése, nem teljes havi érték.</p>}<div className="mt-4 h-64 min-w-0 w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows} margin={{ left: -24, right: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="localDate" tickFormatter={value => String(value).slice(8)} fontSize={10}/><YAxis fontSize={10} width={48}/><Tooltip formatter={value => `${Number(value).toLocaleString("hu-HU", { maximumFractionDigits: 2 })} kWh`}/><Bar dataKey="energyKwh" name="Growatt invertertermelés" fill="#16a34a" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><p className="mt-2 text-xs text-slate-500">Complete: {summary.completeDays} nap · provisional: {summary.provisionalDays} nap · coverage: {(summary.coverageRatio * 100).toLocaleString("hu-HU", { maximumFractionDigits: 0 })}%</p></>}</section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words font-black">{value}</p></div>; }
