"use client";

import React, { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { EmptyState, SegmentedControl } from "@/components/ui";
import { budapestDate, getGrowattHistory, historyStatusLabel } from "@/lib/growatt/history-ui";
import { summarizeGrowattMonth, type GrowattDailyEnergyRow } from "@/lib/growatt/historical";
import { formatKwh } from "@/components/format";
import { addCalendarDays } from "@/lib/weather/date";
import { monthEnd } from "@/lib/solar/monthly-analysis";
import { shouldLoadStatisticsData } from "@/lib/statistics-ui";

type ChartMode = "daily" | "monthly";
async function loadRange(startDate: string, endDate: string): Promise<GrowattDailyEnergyRow[]> { const rows: GrowattDailyEnergyRow[] = []; for (let start = startDate; start <= endDate;) { const candidate = addCalendarDays(start, 365), end = candidate < endDate ? candidate : endDate, response = await getGrowattHistory(start, end); rows.push(...response.rows); start = addCalendarDays(end, 1); } return rows; }

export function GrowattPvHistorySection({ startMonth, endMonth, active = true }: { startMonth: string; endMonth: string; active?: boolean }) {
  const today = budapestDate(), startDate = `${startMonth}-01`, calendarEnd = monthEnd(endMonth), endDate = calendarEnd < today ? calendarEnd : today;
  const [rows, setRows] = useState<GrowattDailyEnergyRow[]>([]), [loading, setLoading] = useState(false), [error, setError] = useState(""), [mode, setMode] = useState<ChartMode>("daily");
  const loadedKey = useRef("");
  useEffect(() => { const key = `${startDate}:${endDate}`; if (!shouldLoadStatisticsData(active, loadedKey.current, key)) return; let mounted = true; setLoading(true); loadRange(startDate, endDate).then(value => { if (mounted) { setRows(value); setError(""); loadedKey.current = key; } }).catch(() => { if (mounted) setError("A Growatt PV-történet nem tölthető be."); }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [active, startDate, endDate]);
  const summary = useMemo(() => summarizeGrowattMonth(rows, startDate, endDate, today), [rows, startDate, endDate, today]);
  const chartRows = useMemo(() => mode === "daily" ? rows.map(row => ({ label: row.localDate, energy: row.energyKwh })) : [...rows.reduce((months, row) => { const month = row.localDate.slice(0, 7); months.set(month, (months.get(month) ?? 0) + row.energyKwh); return months; }, new Map<string, number>())].map(([label, energy]) => ({ label, energy })), [mode, rows]);
  return <section className="card overflow-hidden p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold text-emerald-700">INVERTERTERMELÉS</p><h2 className="text-xl font-black">Napelemes összefoglaló</h2></div><SegmentedControl value={mode} onChange={setMode} label="Invertergrafikon felbontása" options={[{ value: "daily", label: "Napi" }, { value: "monthly", label: "Havi" }]}/></div>{loading && rows.length === 0 ? <p role="status" className="mt-4">PV-adatok betöltése…</p> : error ? <p role="alert" className="mt-4 text-red-700">{error}</p> : rows.length === 0 ? <EmptyState title="Nincs historikus Growatt-adat"><Link className="font-bold text-emerald-700" href="/beallitasok#growatt-history">Szinkronizálás a Beállításokban</Link></EmptyState> : <><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Invertertermelés" value={formatKwh(summary.totalEnergyKwh)}/><Metric label="Napi átlag" value={formatKwh(summary.dailyAverageKwh)}/><Metric label="Legerősebb nap" value={summary.strongestDay ? `${summary.strongestDay.localDate} · ${formatKwh(summary.strongestDay.energyKwh)}` : "Nincs adat"}/><Metric label="Growatt coverage" value={`${summary.recordCount} / ${summary.expectedDays} nap · ${historyStatusLabel(summary)}`}/></div>{summary.coverageRatio < 1 && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Részleges lefedettség: a rendelkezésre álló napok összege nem teljes időszaki érték.</p>}<div className="mt-4 h-72 min-w-0 w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartRows} margin={{ left: -24, right: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tickFormatter={value => mode === "daily" ? String(value).slice(5) : String(value)} fontSize={10} minTickGap={18}/><YAxis fontSize={10} width={48}/><Tooltip formatter={value => `${Number(value).toLocaleString("hu-HU", { maximumFractionDigits: 2 })} kWh`}/><Bar dataKey="energy" name="Growatt invertertermelés" fill="#16a34a" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><p className="mt-2 break-words text-xs text-slate-500">Complete: {summary.completeDays} nap · provisional: {summary.provisionalDays} nap · coverage: {(summary.coverageRatio * 100).toLocaleString("hu-HU", { maximumFractionDigits: 0 })}%</p></>}</section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl border border-slate-100 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words font-black">{value}</p></div>; }
