"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { CartesianGrid, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from "recharts";
import { AppShell } from "@/components/app-shell";
import { ConfidenceExplanation } from "@/components/confidence-explanation";
import { HeatingNav } from "@/components/heating-nav";
import { PageHeader, SegmentedControl } from "@/components/ui";
import { confidencePresentation, retrospectiveConfidenceReasons } from "@/lib/confidence";
import { useEnergyData } from "@/lib/data";
import { analysisFingerprint, canUseSnapshot, consumeManualRefreshToken, HISTORICAL_ANALYSIS_CACHE_VERSION, loadAnalysisSnapshot, readingFingerprintMetadata, saveAnalysisSnapshot, serializedSnapshotBytes, type AnalysisSnapshot } from "@/lib/heating/analysis-snapshot";
import { useHeatingData } from "@/lib/heating/data";
import { buildRetrospectiveSamples, estimateBaseGridImport, measurementIntervals, type RetrospectiveSample } from "@/lib/heating/historical-calibration";
import { analysisSummary, analyzeHeatingRelevance, assignIntervalsToPeriods, bucketAnalysis, heatingCharacteristic, heatingSeasonAnalyses, logsForSettlementPeriod, NON_HEATING_EXPLANATION, periodAnalyses, toggleSelectedInterval, selectBestSupportedBucket, weatherNormalizedComparison, type PeriodAnalysis } from "@/lib/heating/period-analysis";
import { createClient } from "@/lib/supabase/client";
import { localIsoDate } from "@/lib/weather/date";
import { weatherLocationKey } from "@/lib/weather/historical-cache";
import { loadHistoricalWeatherCached } from "@/lib/weather/historical-loader";
import type { DailyWeather } from "@/lib/weather/types";
import type { TariffSettings } from "@/lib/types";

const fmt=(value:number|null,digits=1)=>value==null?"Nincs adat":value.toLocaleString("hu-HU",{maximumFractionDigits:digits});
export default function HistoricalHeatingAnalysis(){
  const energy=useEnergyData(),heating=useHeatingData();
  const [userId,setUserId]=useState<string|null>(null),[snapshot,setSnapshot]=useState<AnalysisSnapshot|null>(null),[snapshotChecked,setSnapshotChecked]=useState(false),[weather,setWeather]=useState<DailyWeather[]>([]),[freshReady,setFreshReady]=useState(false),[status,setStatus]=useState("Korábbi elemzés betöltése…"),[error,setError]=useState(""),[refreshToken,setRefreshToken]=useState(0),consumedRefreshToken=useRef(0),[selected,setSelected]=useState<RetrospectiveSample|null>(null),[snapshotBytes,setSnapshotBytes]=useState(0),[periodFilter,setPeriodFilter]=useState("all"),[analysisView,setAnalysisView]=useState<"analysis"|"details">("analysis"),[opened,setOpened]=useState<Set<string>>(new Set());
  useEffect(()=>{let active=true;void createClient().auth.getUser().then(async({data:{user}})=>{if(!active)return;if(!user){setSnapshotChecked(true);return}setUserId(user.id);const cached=await loadAnalysisSnapshot(user.id);if(active){setSnapshot(cached);setSnapshotBytes(cached?serializedSnapshotBytes(cached):0);setSnapshotChecked(true);setStatus(cached?"Frissítés ellenőrzése…":"Historikus időjárás betöltése…")}});return()=>{active=false}},[]);
  const intervals=useMemo(()=>measurementIntervals(energy.allReadings),[energy.allReadings]);
  const location=useMemo(()=>heating.profile?.weather_latitude!=null&&heating.profile.weather_longitude!=null?{latitude:heating.profile.weather_latitude,longitude:heating.profile.weather_longitude,timezone:heating.profile.weather_timezone}:null,[heating.profile?.weather_latitude,heating.profile?.weather_longitude,heating.profile?.weather_timezone]);
  const fingerprint=useMemo(()=>{if(!userId||!location)return null;return analysisFingerprint({userId,...readingFingerprintMetadata(energy.allReadings),seasonStart:`${energy.tariff.heating_season_start_month}-${energy.tariff.heating_season_start_day}`,seasonEnd:`${energy.tariff.heating_season_end_month}-${energy.tariff.heating_season_end_day}`,locationKey:weatherLocationKey(location),profileValues:[heating.profile?.design_heat_loss_kw,heating.profile?.design_indoor_temperature_c,heating.profile?.design_outdoor_temperature_c,heating.profile?.target_indoor_temperature_c]})},[userId,location,energy.allReadings,energy.tariff,heating.profile]);
  useEffect(()=>{if(!snapshotChecked||energy.loading||heating.loading||!fingerprint||!location||energy.allReadings.length<2)return;const refresh=consumeManualRefreshToken(refreshToken,consumedRefreshToken.current);if(canUseSnapshot(snapshot,fingerprint,refresh.forceRefresh)){setStatus("");return}consumedRefreshToken.current=refresh.consumed;let active=true;setFreshReady(false);setStatus(snapshot?"Elemzés frissítése…":"Historikus időjárás betöltése…");const start=localIsoDate(new Date(energy.allReadings[0].reading_at),location.timezone),end=localIsoDate(new Date(energy.allReadings.at(-1)!.reading_at),location.timezone);loadHistoricalWeatherCached(location,start,end,refresh.forceRefresh).then(result=>{if(!active)return;setWeather(result.weather);setError(result.complete?"":"Nem minden szükséges időjárási nap érhető el.");setStatus(`${intervals.length} mérési intervallum elemzése…`);setFreshReady(true)}).catch(caught=>{if(active){setError(caught instanceof Error?caught.message:"Az elemzés nem frissíthető.");setStatus("")}});return()=>{active=false}},[snapshotChecked,energy.loading,heating.loading,fingerprint,location,energy.allReadings,intervals.length,refreshToken,snapshot]);
  const freshBaseline=useMemo(()=>estimateBaseGridImport(intervals,energy.tariff,heating.profile?.weather_timezone),[intervals,energy.tariff,heating.profile?.weather_timezone]),freshSamples=useMemo(()=>freshReady&&freshBaseline.value!=null?buildRetrospectiveSamples(intervals,weather,freshBaseline.value,freshBaseline.sampleCount,heating.profile?.weather_timezone):[],[freshReady,intervals,weather,freshBaseline,heating.profile?.weather_timezone]),freshBuckets=useMemo(()=>bucketAnalysis(freshSamples),[freshSamples]);
  useEffect(()=>{if(!freshReady||!fingerprint||!userId)return;const next:AnalysisSnapshot={version:HISTORICAL_ANALYSIS_CACHE_VERSION,userId,fingerprint,generatedAt:new Date().toISOString(),baseline:freshBaseline,samples:freshSamples,buckets:freshBuckets.map(x=>({bucket:x.bucket,sampleCount:x.sampleCount,medianGridImportKwhDay:x.medianGridImportKwhDay??0,medianGridImportAboveBaselineKwhDay:x.medianGridImportAboveBaselineKwhDay??0}))};setSnapshot(next);setSnapshotBytes(serializedSnapshotBytes(next));setStatus("");void saveAnalysisSnapshot(next)},[freshReady,fingerprint,userId,freshBaseline,freshSamples,freshBuckets]);
  const timeZone=heating.profile?.weather_timezone??"Europe/Budapest",targetIndoorC=heating.profile?.target_indoor_temperature_c??21,baseline=snapshot?.baseline??freshBaseline,allSamples=snapshot?.samples??freshSamples,analyses=useMemo(()=>periodAnalyses(intervals,allSamples,energy.periods,heating.logs,timeZone,energy.tariff,targetIndoorC),[intervals,allSamples,energy.periods,heating.logs,timeZone,energy.tariff,targetIndoorC]),openPeriod=energy.periods.find(x=>x.status==="open")??energy.periods.at(-1),selectedPeriodId=periodFilter==="current"?openPeriod?.id:periodFilter==="all"?null:periodFilter,selectedAnalysis=selectedPeriodId?analyses.find(x=>x.period.id===selectedPeriodId):null,visibleSamples=selectedAnalysis?.samples??allSamples,visibleLogs=selectedAnalysis?logsForSettlementPeriod(heating.logs,selectedAnalysis.period,timeZone):heating.logs,visibleAssigned=assignIntervalsToPeriods(visibleSamples,energy.periods,timeZone),visibleSummary=selectedAnalysis?.summary??analysisSummary(assignIntervalsToPeriods(intervals,energy.periods,timeZone),visibleAssigned,analyzeHeatingRelevance(visibleSamples,energy.tariff,targetIndoorC,timeZone).filter(x=>x.heatingRelevance==="likely")),gridBuckets=bucketAnalysis(visibleSamples,visibleLogs),heatingBuckets=heatingCharacteristic(visibleSamples,energy.tariff,targetIndoorC,timeZone,visibleLogs),seasons=heatingSeasonAnalyses(allSamples,energy.tariff,timeZone,targetIndoorC),comparisons=analyses.slice(0,-1).map((newer,index)=>weatherNormalizedComparison(analyses[index+1],newer));
  useEffect(()=>{if(openPeriod)setOpened(current=>current.size?current:new Set([openPeriod.id]))},[openPeriod]);
  const coldLoading=!snapshot&&(energy.loading||heating.loading||!snapshotChecked||!!status),toggle=(id:string,open:boolean)=>setOpened(current=>{const next=new Set(current);if(open)next.add(id);else next.delete(id);return next});
  return <AppShell><HeatingNav/><PageHeader eyebrow="Fűtési döntéstámogatás" title="Historikus fűtési elemzés" description="Retrospektív terhelési elemzés; nem rekonstruált kazánbeállítás." actions={<button className="secondary" onClick={()=>setRefreshToken(x=>x+1)}>Historikus adatok frissítése</button>}/>{status&&<p className="mt-3 inline-block rounded-full bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-800">{status}</p>}{error&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm">{error} {snapshot&&"A korábbi eredmény továbbra is látható."}</p>}{coldLoading?<p className="card mt-5 p-6 font-black">Historikus elemzés előkészítése…</p>:<>
    <section className="card mt-5 p-4"><label className="text-sm font-bold">Elemzett elszámolási időszak<select className="field mt-2" value={periodFilter} onChange={e=>setPeriodFilter(e.target.value)}><option value="all">Összes elszámolási időszak</option>{openPeriod&&<option value="current">Aktuális időszak</option>}{analyses.filter(x=>x.period.id!==openPeriod?.id).map(x=><option key={x.period.id} value={x.period.id}>{x.label} elszámolási időszak</option>)}</select></label></section>
    <div className="mt-3"><SegmentedControl value={analysisView} onChange={setAnalysisView} label="Elemzési nézet" options={[{value:"analysis",label:"Elemzés"},{value:"details",label:"Részletes adatok"}]}/></div>
    {analysisView==="analysis"&&<>
    <section className="mt-3 grid gap-3 sm:grid-cols-4"><Metric label="Intervallum minták" value={String(visibleSummary?.sampleCount??0)}/><Metric label="Használható retrospektív minták" value={String(visibleSummary?.usableSampleCount??0)}/><Metric label="Átlagos külső hőmérséklet" value={`${fmt(visibleSummary?.meanOutdoorC??null)} °C`}/><Metric label="Medián hálózati import" value={`${fmt(visibleSummary?.medianGridImportKwhDay??null)} kWh/nap`}/></section>
    <p className="mt-2 text-xs text-slate-500">Snapshot v{HISTORICAL_ANALYSIS_CACHE_VERSION}: {fmt(snapshotBytes/1024)} KiB · {snapshot?.generatedAt?new Date(snapshot.generatedAt).toLocaleString("hu-HU"):"friss számítás"}</p>
    <LearnedSummary rows={heatingBuckets}/>
    <section className="card mt-4 p-4"><h2 className="text-xl font-black">A ház fűtési karakterisztikája</h2><p className="mt-1 text-xs text-slate-600">Csak teljes fűtési szezonon belüli, adatminőségileg használható és hőmérséklet alapján valószínű fűtési minták.</p><BucketTable rows={heatingBuckets} heating/></section>
    <section className="card mt-4 overflow-hidden p-4"><h2 className="text-xl font-black">Hőmérséklet és hálózati import</h2><div className="mt-3 h-64 min-w-0"><ResponsiveContainer><ScatterChart><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" dataKey="weatherMeanTempC" unit=" °C"/><YAxis type="number" dataKey="observedDailyGridImportKwh" width={52}/><Tooltip/><Scatter data={visibleSamples} fill="#047857"/></ScatterChart></ResponsiveContainer></div></section>
    <section className="card mt-4 overflow-x-auto p-4"><h2 className="text-xl font-black">Elszámolási időszakok összehasonlítása</h2><p className="mt-1 text-xs text-slate-600">Azonos külső hőmérséklet-tartományok medián napi importja; a mintaszám és confidence mindig látható.</p><table className="mt-3 min-w-[700px] text-left text-xs"><thead><tr><th className="p-2">Tartomány</th>{analyses.map(x=><th key={x.period.id} className="p-2">{x.label}</th>)}</tr></thead><tbody>{gridBuckets.map(row=><tr key={row.bucket} className="border-t"><th className="p-2">{row.bucket}</th>{analyses.map(period=>{const cell=period.buckets.find(x=>x.bucket===row.bucket)!;return <td key={period.period.id} className="p-2">{fmt(cell.medianGridImportKwhDay)} kWh/nap<br/>{cell.sampleCount} minta · {confidencePresentation(cell.confidence).label}<br/><span className="text-slate-500">{cell.confidenceReason}</span></td>})}</tr>)}</tbody></table>{comparisons.map(x=><p key={`${x.olderLabel}-${x.newerLabel}`} className="mt-3 rounded-xl bg-slate-50 p-3 text-sm">{x.gridImportChangePercent==null?`${x.olderLabel} és ${x.newerLabel}: nincs elegendő összehasonlítható bucket.`:`Azonos tartományokban a ${x.newerLabel} időszak átlagosan ${Math.abs(x.gridImportChangePercent).toFixed(1)}%-kal ${x.gridImportChangePercent<0?"alacsonyabb":"magasabb"} hálózati importot mutatott.`} <b>Időjárás-korrigált közelítő összehasonlítás.</b> {confidencePresentation(x.confidence).label} megbízhatóság — {confidencePresentation(x.confidence).explanation} ({x.comparableBucketCount} összehasonlítható bucket.)</p>)}</section>
    <section className="card mt-4 p-4"><h2 className="text-xl font-black">Fűtési szezonok összehasonlítása</h2><p className="mt-1 text-xs text-slate-600">A konfigurált fűtési szezon külön dimenzió az elszámolási időszaktól.</p><div className="mt-3 grid gap-3 xl:grid-cols-2">{seasons.map(x=><article key={x.label} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-lg font-black">{x.label}</h3><ConfidenceExplanation level={x.confidence} context="retrospective" compact/></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3"><MiniMetric label="Hálózati import" value={`${fmt(x.observedGridImportKwh)} kWh`}/><MiniMetric label="Becsült fűtési többlet" value={`${fmt(x.estimatedHeatingExcessKwh)} kWh`}/><MiniMetric label="Átlagos külső" value={`${fmt(x.meanOutdoorC)} °C`}/><MiniMetric label="Leghidegebb" value={`${fmt(x.coldest?.weatherMeanTempC??null)} °C`}/><MiniMetric label="Minták" value={String(x.sampleCount)}/><MiniMetric label="Figyelmeztetések" value={String(x.warningCount)}/></div><details className="mt-3 rounded-xl bg-white p-3"><summary className="cursor-pointer text-xs font-bold">Részletek és megbízhatóság</summary><p className="mt-2 text-xs text-slate-500">Becsült alapterhelés: {fmt(x.estimatedBaseGridImportKwh)} kWh. {x.confidenceReason}</p></details></article>)}</div></section>
    </>}
    {analysisView==="details"&&<>
    <p className="mt-3 text-xs text-slate-500">Snapshot v{HISTORICAL_ANALYSIS_CACHE_VERSION}: {fmt(snapshotBytes/1024)} KiB · {snapshot?.generatedAt?new Date(snapshot.generatedAt).toLocaleString("hu-HU"):"friss számítás"}</p>
    <section className="card mt-4 p-4"><h2 className="text-xl font-black">Háztartási hálózati import és külső hőmérséklet</h2><p className="mt-1 text-xs text-slate-600">Minden megfelelő historikus intervallum. Az alapterhelés feletti import önmagában nem bizonyít fűtést.</p><BucketTable rows={gridBuckets} heating={false}/></section>
    <section className="card mt-4 p-4"><h2 className="text-xl font-black">Fűtési karakterisztika részletes statisztikája</h2><BucketTable rows={heatingBuckets} heating/></section>
    <section className="mt-4"><h2 className="text-xl font-black">Intervallumok elszámolási időszakonként</h2><p className="mt-1 text-xs text-slate-600">A period- vagy szezonhatárt átlépő intervallumokat nem osztjuk fel feltételezett arányban.</p>{analyses.filter(x=>!selectedPeriodId||x.period.id===selectedPeriodId).map(period=><PeriodDetails key={period.period.id} analysis={period} open={opened.has(period.period.id)} onToggle={open=>toggle(period.period.id,open)} selected={selected} onSelect={sample=>setSelected(current=>toggleSelectedInterval(current,sample))} timeZone={timeZone} baselineSampleCount={baseline.sampleCount} profile={heating.profile} source={heating.source} logs={heating.logs} tariff={energy.tariff}/>)}</section>
    </>}
    </>}</AppShell>;
}
function Metric({label,value}:{label:string;value:string}){return <article className="card min-w-0 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words text-xl font-black">{value}</p></article>}
function LearnedSummary({rows}:{rows:ReturnType<typeof heatingCharacteristic>}){const best=selectBestSupportedBucket(rows),cold=rows.find(x=>x.bucket==="< −5 °C"),confidence=best?confidencePresentation(best.confidence):null;return <section className="card mt-4 border-2 border-emerald-200 p-4"><h2 className="text-xl font-black">Mit tanultunk a házról?</h2>{best&&confidence?<div className="mt-2 space-y-1 text-sm"><p>Legjobban alátámasztott tartomány: <b>{best.bucket}</b> — {confidence.label} megbízhatóság, {best.sampleCount} használható minta.</p><p>Ebben a tartományban a medián becsült fűtési többlet {fmt(best.medianHeatingExcessKwhDay)} kWh/nap.</p><p>−5 °C alatt jelenleg {cold?.sampleCount??0} használható fűtési minta áll rendelkezésre.</p><p>Következő értékes adat: valódi fűtési log kevéssé lefedett, hideg tartományban.</p></div>:<p className="mt-2 text-sm">Még nincs elegendő, fűtési szempontból releváns retrospektív minta. A következő értékes adat egy valódi fűtési log.</p>}</section>}
function BucketTable({rows,heating}:{rows:ReturnType<typeof bucketAnalysis>;heating:boolean}){return <div className="mt-3 grid gap-3 xl:grid-cols-2">{rows.map(row=><article key={row.bucket} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="text-lg font-black">{row.bucket}</h3><ConfidenceExplanation level={row.confidence} context="retrospective" compact/></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><MiniMetric label="Hálózati import" value={`${fmt(row.medianGridImportKwhDay)} kWh/nap`}/><MiniMetric label="Alapterhelés felett" value={`${fmt(row.medianGridImportAboveBaselineKwhDay)} kWh/nap`}/>{heating&&<MiniMetric label="Becsült fűtési többlet" value={`${fmt(row.medianHeatingExcessKwhDay)} kWh/nap`}/>}<MiniMetric label="Minták" value={String(row.sampleCount)}/></div><details className="mt-3 rounded-xl bg-white p-3"><summary className="cursor-pointer text-xs font-bold">Mi alapján készült?</summary><p className="mt-2 text-xs text-slate-600">{row.confidenceReason}</p><p className="mt-1 text-xs text-slate-500">{heating?`Átlagos villamos terhelési megfelelő: ${fmt(row.averageElectricalLoadEquivalentKw)} kW. Nem pillanatnyi kazánteljesítmény.`:NON_HEATING_EXPLANATION}</p><p className="mt-1 text-xs text-slate-500">{row.actualLogCount} valódi heating log ebben a tartományban.</p></details></article>)}</div>}
function MiniMetric({label,value}:{label:string;value:string}){return <div className="data-item"><p className="data-label">{label}</p><p className="data-value">{value}</p></div>}
function PeriodDetails({analysis,open,onToggle,onSelect,selected,timeZone,baselineSampleCount,profile,source,logs,tariff}:{analysis:PeriodAnalysis;open:boolean;onToggle:(open:boolean)=>void;onSelect:(sample:RetrospectiveSample)=>void;selected:RetrospectiveSample|null;timeZone:string;baselineSampleCount:number;profile:ReturnType<typeof useHeatingData>["profile"];source:ReturnType<typeof useHeatingData>["source"];logs:ReturnType<typeof useHeatingData>["logs"];tariff:TariffSettings}){return <details className="card mt-3 p-4" open={open} onToggle={event=>onToggle(event.currentTarget.open)}><summary className="cursor-pointer"><b>{analysis.label} elszámolási időszak</b><p className="mt-1 text-xs text-slate-600">{analysis.period.start_date} – {analysis.period.end_date??"nyitott"} · {analysis.summary.usableSampleCount} minta · {fmt(analysis.summary.observedGridImportTotalKwh)} kWh összes megfigyelt hálózati import · {fmt(analysis.summary.heatingRelatedExcessTotalKwh)} kWh releváns becsült fűtési többlet</p><p className="mt-1 text-xs text-slate-500">{analysis.summary.confidenceReason}</p></summary>{open&&<div className="mt-3 space-y-2">{analysis.samples.map((sample,index)=>{const c=confidencePresentation(sample.confidence),active=selected===sample;return <div key={`${sample.start}-${index}`}><button className="grid w-full gap-1 rounded-xl bg-slate-50 p-3 text-left text-sm sm:grid-cols-5" onClick={()=>onSelect(sample)} aria-expanded={active}><span>{localIsoDate(new Date(sample.start),timeZone)} – {localIsoDate(new Date(sample.end),timeZone)}</span><span>{fmt(sample.weatherMeanTempC)} °C</span><span>{fmt(sample.observedDailyGridImportKwh)} kWh/nap</span><span>{fmt(sample.gridImportAboveBaselineKwhDay)} kWh/nap baseline felett</span><span><b>{c.label}</b><br/><small>{c.explanation}</small></span></button>{active&&<Retrospective sample={sample} baselineSampleCount={baselineSampleCount} profile={profile} source={source} logs={logs} timeZone={timeZone} tariff={tariff}/>}</div>})}</div>}</details>}
function Retrospective({sample,profile,baselineSampleCount,timeZone,tariff}:{sample:RetrospectiveSample;timeZone:string;tariff:TariffSettings;baselineSampleCount:number;profile:ReturnType<typeof useHeatingData>["profile"];source:ReturnType<typeof useHeatingData>["source"];logs:ReturnType<typeof useHeatingData>["logs"]}){const analyzed=analyzeHeatingRelevance([sample],tariff,profile?.target_indoor_temperature_c??21,timeZone)[0],above=sample.gridImportAboveBaselineKwhDay,relevance=analyzed.heatingRelevance==="likely"?"Fűtési szempontból releváns":analyzed.heatingRelevance==="uncertain"?"Bizonytalan fűtési kontextus":"Nem fűtési kontextus",reasons=retrospectiveConfidenceReasons({durationDays:sample.durationDays,weatherDayCount:sample.weatherDayCount,weatherCoverageRatio:sample.weatherCoverageRatio,baselineSampleCount,dataWarning:sample.dataWarning,productionDeltaKwh:sample.productionDeltaKwh,observedGridImportKwh:sample.observedGridImportKwh});return <section className="mt-2 rounded-xl border-2 border-blue-200 bg-white p-4 text-sm"><p className="text-xs font-bold text-blue-700">RETROSPEKTÍV RÉSZLETEK</p><h3 className="font-black">{localIsoDate(new Date(sample.start),timeZone)} – {localIsoDate(new Date(sample.end),timeZone)}</h3><div className="mt-2 grid gap-1 sm:grid-cols-2"><p>Időtartam: {fmt(sample.durationDays)} nap</p><p>Külső mean/min/max: {fmt(sample.weatherMeanTempC)} / {fmt(sample.weatherMinTempC)} / {fmt(sample.weatherMaxTempC)} °C</p><p>Weather coverage: {(sample.weatherCoverageRatio*100).toFixed(0)}% · {sample.weatherDayCount} helyi nap</p><p>Megfigyelt hálózati import: {fmt(sample.observedGridImportKwh)} kWh</p><p>Normalizált hálózati import: {fmt(sample.observedDailyGridImportKwh)} kWh/nap</p><p>Alapterhelés: {fmt(sample.estimatedBaseGridImportKwhDay)} kWh/nap</p><p>Alapterhelés feletti hálózati import: {fmt(above)} kWh/nap</p><p>Heating relevance: {relevance}</p>{analyzed.heatingRelatedExcessKwhDay!=null&&<p>Becsült fűtési többlet: {fmt(analyzed.heatingRelatedExcessKwhDay)} kWh/nap</p>}<p>Export/termelési kontextus: {sample.productionDeltaKwh==null?"bizonytalan":`${fmt(sample.productionDeltaKwh)} kWh`}</p></div>{analyzed.heatingRelevance!=="likely"&&<div className="mt-2 rounded-lg bg-amber-50 p-3"><p>Ez az intervallum nem része a fűtési karakterisztika tanításának.</p><p>Az alapterhelés feletti fogyasztás nem bizonyítja, hogy a többletet fűtés okozta.</p></div>}<p className="mt-2 text-xs text-slate-600">A hálózati import nem azonos a teljes háztartási villamosenergia-felhasználással, mert a helyben elfogyasztott napelemes energia nem jelenik meg benne. Az akkori kazánbeállítás és komfort nem ismert.</p><div className="mt-3 rounded-xl bg-slate-50 p-3"><ConfidenceExplanation level={sample.confidence} context="retrospective" reasons={reasons}/></div></section>}
