import {localDayWindow} from "@/lib/weather/date";
const TZ="Europe/Budapest",fmt=new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"});
const parts=(date:Date)=>Object.fromEntries(fmt.formatToParts(date).filter(x=>x.type!=="literal").map(x=>[x.type,x.value]));
export type LocalParts={year:number;month:number;day:number;hour:number;minute:number;second:number};
export type LocalCellResult={kind:"valid";value:LocalParts}|{kind:"empty"|"invalid_date"|"invalid_interval"};
export function parseLocalCell(value:unknown):LocalCellResult{if(value===null||value===undefined||String(value).trim()==="")return{kind:"empty"};let p:Partial<LocalParts>|null=null;if(value instanceof Date&&!Number.isNaN(value.getTime()))p={year:value.getUTCFullYear(),month:value.getUTCMonth()+1,day:value.getUTCDate(),hour:value.getUTCHours(),minute:value.getUTCMinutes(),second:value.getUTCSeconds()};else if(typeof value==="number"&&Number.isFinite(value)){const d=new Date(Date.UTC(1899,11,30)+Math.round(value*86400000));p={year:d.getUTCFullYear(),month:d.getUTCMonth()+1,day:d.getUTCDate(),hour:d.getUTCHours(),minute:d.getUTCMinutes(),second:d.getUTCSeconds()}}else if(typeof value==="string"){const s=value.trim().replace(/\.$/,"");const m=s.match(/^(\d{4})[.\-/](\d{1,2})[.\-/](\d{1,2})[.\sT]+(\d{1,2}):(\d{2})(?::(\d{2}))?$/);if(m)p={year:+m[1],month:+m[2],day:+m[3],hour:+m[4],minute:+m[5],second:+(m[6]??0)}}if(!p||Object.values(p).some(x=>x===undefined))return{kind:"invalid_date"};const full=p as LocalParts,calendar=new Date(Date.UTC(full.year,full.month-1,full.day,full.hour,full.minute,full.second));if(calendar.getUTCFullYear()!==full.year||calendar.getUTCMonth()+1!==full.month||calendar.getUTCDate()!==full.day||calendar.getUTCHours()!==full.hour||calendar.getUTCMinutes()!==full.minute||calendar.getUTCSeconds()!==full.second)return{kind:"invalid_date"};if(full.minute%15||full.second!==0)return{kind:"invalid_interval"};return{kind:"valid",value:full}}
export const localKey=(p:LocalParts)=>`${p.year}-${String(p.month).padStart(2,"0")}-${String(p.day).padStart(2,"0")}T${String(p.hour).padStart(2,"0")}:${String(p.minute).padStart(2,"0")}:${String(p.second).padStart(2,"0")}`;
export function utcCandidates(p:LocalParts){const naive=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second),key=localKey(p),matches:string[]=[];for(let delta=-3*3600000;delta<=3*3600000;delta+=30*60000){const d=new Date(naive+delta),x=parts(d),k=`${x.year}-${x.month}-${x.day}T${x.hour}:${x.minute}:${x.second}`;if(k===key)matches.push(d.toISOString())}return[...new Set(matches)].sort()}
export function expectedIntervals(date:string){return localDayWindow(date,TZ).durationHours*4}
