import{describe,expect,it}from"vitest";import*as XLSX from"xlsx";import{localDayWindow}from"@/lib/weather/date";import{parseEonWorkbook,EON_MAX_FILE_BYTES}from"./parser";
const localText=(instant:Date)=>{const p=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Budapest",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(instant).filter(x=>x.type!=="literal").map(x=>[x.type,x.value]));return`${p.year}.${p.month}.${p.day} ${p.hour}:${p.minute}:${p.second}`};
function rowsFor(date:string,count:number,imp=.25,exp=.1):unknown[][]{const w=localDayWindow(date,"Europe/Budapest"),start=w.start;return Array.from({length:count},(_,i)=>[localText(new Date(start+i*900000)),imp,exp])}
function workbook(rows:unknown[][],options:{total?:[number,number];max?:[number,number];secondSheet?:boolean}={}){const values=rows.filter(r=>typeof r[1]==="number"&&typeof r[2]==="number"),total=options.total??[values.reduce((s,r)=>s+(r[1]as number),0),values.reduce((s,r)=>s+(r[2]as number),0)],max=options.max??[Math.max(0,...values.map(r=>r[1]as number)),Math.max(0,...values.map(r=>r[2]as number))],data=[["Dátum/Idő","+A","-A"],["MAXIMUM ÉRTÉK",...max],["ÖSSZEG",...total],...rows],wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(data),"Adatok");if(options.secondSheet)XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(data),"Másolat");return XLSX.write(wb,{type:"buffer",bookType:"xlsx"})as Buffer}
describe("E.ON XLSX parser",()=>{it.each([["2026-08-02",96],["2026-03-29",92],["2026-10-25",100]]as const)("%s teljes nap %s UTC intervallum",(date,count)=>{const x=parseEonWorkbook(workbook(rowsFor(date,count)),{referenceDate:"2026-10-26"});expect(x.days[0]).toMatchObject({expectedIntervalCount:count,validNonNullIntervalCount:count,status:"complete"});expect(new Set(x.intervals.map(r=>r.intervalStartUtc)).size).toBe(count)});
it("az őszi ismételt helyi időt két külön UTC időpontra oldja",()=>{const x=parseEonWorkbook(workbook(rowsFor("2026-10-25",100)),{referenceDate:"2026-10-26"}),repeated=x.intervals.filter(r=>new Intl.DateTimeFormat("hu-HU",{timeZone:"Europe/Budapest",hour:"2-digit",minute:"2-digit"}).format(new Date(r.intervalStartUtc))==="02:00");expect(repeated).toHaveLength(2);expect(repeated[0].intervalStartUtc).not.toBe(repeated[1].intervalStartUtc)});
it("több napot kezel",()=>{const x=parseEonWorkbook(workbook([...rowsFor("2026-08-01",96),...rowsFor("2026-08-02",96)]),{referenceDate:"2026-08-03"});expect(x.days).toHaveLength(2);expect(x.completeDays).toBe(2)});
it("az aktuális részleges nap provisional",()=>{const x=parseEonWorkbook(workbook(rowsFor("2026-08-04",20)),{referenceDate:"2026-08-04"});expect(x.days[0].status).toBe("provisional")});
it("lezárt hiányos nap incomplete",()=>{const x=parseEonWorkbook(workbook(rowsFor("2026-08-03",20)),{referenceDate:"2026-08-04"});expect(x.days[0].status).toBe("incomplete")});
it("Date cellát, Excel serialt és magyar dátumszöveget kezel",()=>{const serial=(Date.UTC(2026,7,2,0,0)-Date.UTC(1899,11,30))/86400000,rows=[[new Date(Date.UTC(2026,7,2,0,0)),"0,25",0],[serial+.25/24,0,0],["2026.08.02 00:30",0,0]];const x=parseEonWorkbook(workbook(rows),{referenceDate:"2026-08-03"});expect(x.validRows).toBe(3);expect(x.intervals[0].importKwh).toBe(.25)});
it("üres értéket nem kever a nullával vagy nullával",()=>{const rows=rowsFor("2026-08-04",3,0,0);rows[2][1]=null;const x=parseEonWorkbook(workbook(rows),{referenceDate:"2026-08-04"});expect(x.validRows).toBe(2);expect(x.intervals[0].importKwh).toBe(0)});
it("negatív értéket blokkol",()=>{const rows=rowsFor("2026-08-02",96);rows[2][1]=-1;const x=parseEonWorkbook(workbook(rows),{referenceDate:"2026-08-03"});expect(x.blockingErrors).toContain("EON_NEGATIVE_VALUE")});
it("nem 15 perces és hibás dátum nem lesz intervallum",()=>{const rows=[["2026.08.02 00:07",1,1],["hibás",1,1]];const x=parseEonWorkbook(workbook(rows),{referenceDate:"2026-08-03"});expect(x.validRows).toBe(0)});
it("összesítő egyezést és eltérést ellenőriz",()=>{expect(parseEonWorkbook(workbook(rowsFor("2026-08-02",96))).summaryValidation.totalMatches).toBe(true);const bad=parseEonWorkbook(workbook(rowsFor("2026-08-02",96),{total:[999,999]}));expect(bad.blockingErrors).toContain("EON_SUMMARY_TOTAL_MISMATCH")});
it("több megfelelő munkalapot elutasít",()=>expect(()=>parseEonWorkbook(workbook(rowsFor("2026-08-02",96),{secondSheet:true}))).toThrowError(expect.objectContaining({code:"EON_AMBIGUOUS_WORKSHEET"})));
it("hiányzó fejlécet és sérült/túl nagy fájlt elutasít",()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([["más"]]),"x");expect(()=>parseEonWorkbook(XLSX.write(wb,{type:"buffer",bookType:"xlsx"}))).toThrowError(expect.objectContaining({code:"EON_WORKSHEET_NOT_FOUND"}));expect(()=>parseEonWorkbook(Buffer.from("PKbroken"))).toThrow();const huge=Buffer.alloc(EON_MAX_FILE_BYTES+1);huge[0]=0x50;huge[1]=0x4b;expect(()=>parseEonWorkbook(huge)).toThrowError(expect.objectContaining({code:"EON_FILE_TOO_LARGE"}))})});
