import{describe,expect,it}from"vitest";import*as XLSX from"xlsx";import{localDayWindow}from"@/lib/weather/date";import{parseEonWorkbook,EON_MAX_FILE_BYTES}from"./parser";
const localText=(instant:Date)=>{const p=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Budapest",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23"}).formatToParts(instant).filter(x=>x.type!=="literal").map(x=>[x.type,x.value]));return`${p.year}.${p.month}.${p.day} ${p.hour}:${p.minute}:${p.second}`};
function rowsFor(date:string,count:number,imp=.25,exp=.1):unknown[][]{const w=localDayWindow(date,"Europe/Budapest"),start=w.start;return Array.from({length:count},(_,i)=>[localText(new Date(start+i*900000)),imp,exp])}
function springTemplate(blankIndexes=[8,9,10,11]){return Array.from({length:96},(_,i)=>[`2026.03.29 ${String(Math.floor(i/4)).padStart(2,"0")}:${String((i%4)*15).padStart(2,"0")}:00`,blankIndexes.includes(i)?null:i+1,blankIndexes.includes(i)?null:(i+1)/10])}
function workbook(rows:unknown[][],options:{total?:[number,number];max?:[number,number];secondSheet?:boolean}={}){const values=rows.filter(r=>typeof r[1]==="number"&&typeof r[2]==="number"),total=options.total??[values.reduce((s,r)=>s+(r[1]as number),0),values.reduce((s,r)=>s+(r[2]as number),0)],max=options.max??[Math.max(0,...values.map(r=>r[1]as number)),Math.max(0,...values.map(r=>r[2]as number))],data=[["Dátum/Idő","+A","-A"],["MAXIMUM ÉRTÉK",...max],["ÖSSZEG",...total],...rows],wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(data),"Adatok");if(options.secondSheet)XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(data),"Másolat");return XLSX.write(wb,{type:"buffer",bookType:"xlsx"})as Buffer}
function scheduledWorkbook(rows:unknown[][],options:{reverse?:boolean;secondPodAt?:number;badUnitAt?:number}={}){const header=["Pod","Időbélyeg","Változó","Érték","Mértékegység","Változó","Érték","Mértékegység"],data=rows.map((row,index)=>{const pod=index===options.secondPodAt?"POD-2":"POD-1",unit=index===options.badUnitAt?"Wh":"kWh",plus=["+A",row[1],unit],minus=["-A",row[2],"kWh"],pairs=options.reverse?[...minus,...plus]:[...plus,...minus];return[pod,row[0],...pairs]}),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([header,...data]),"POD_1");return XLSX.write(wb,{type:"buffer",bookType:"xlsx"})as Buffer}
describe("E.ON XLSX parser",()=>{it.each([["2026-08-02",96],["2026-03-29",92],["2026-10-25",100]]as const)("%s teljes nap %s UTC intervallum",(date,count)=>{const x=parseEonWorkbook(workbook(rowsFor(date,count)),{referenceDate:"2026-10-26"});expect(x.days[0]).toMatchObject({expectedIntervalCount:count,validNonNullIntervalCount:count,status:"complete"});expect(new Set(x.intervals.map(r=>r.intervalStartUtc)).size).toBe(count)});
it("az őszi ismételt helyi időt két külön UTC időpontra oldja",()=>{const x=parseEonWorkbook(workbook(rowsFor("2026-10-25",100)),{referenceDate:"2026-10-26"}),repeated=x.intervals.filter(r=>new Intl.DateTimeFormat("hu-HU",{timeZone:"Europe/Budapest",hour:"2-digit",minute:"2-digit"}).format(new Date(r.intervalStartUtc))==="02:00");expect(repeated).toHaveLength(2);expect(repeated[0].intervalStartUtc).not.toBe(repeated[1].intervalStartUtc)});
it("több napot kezel",()=>{const x=parseEonWorkbook(workbook([...rowsFor("2026-08-01",96),...rowsFor("2026-08-02",96)]),{referenceDate:"2026-08-03"});expect(x.days).toHaveLength(2);expect(x.completeDays).toBe(2)});
it("az ütemezett E.ON export Pod/Időbélyeg/Változó/Érték formátumát kezeli",()=>{const x=parseEonWorkbook(scheduledWorkbook(rowsFor("2026-08-02",96,.25,.1)),{referenceDate:"2026-08-03"});expect(x).toMatchObject({periodStart:"2026-08-02",periodEnd:"2026-08-02",rawRows:96,validRows:96,completeDays:1,blockingErrors:[]});expect(x.importSumKwh).toBe(24);expect(x.exportSumKwh).toBe(9.6)});
it("az ütemezett exportban a +A és -A mezőpár sorrendje felcserélhető",()=>{const x=parseEonWorkbook(scheduledWorkbook(rowsFor("2026-08-02",96,.25,.1),{reverse:true}),{referenceDate:"2026-08-03"});expect(x.blockingErrors).toEqual([]);expect(x.intervals[0]).toMatchObject({importKwh:.25,exportKwh:.1})});
it("az ütemezett export eltérő POD-ját és nem kWh mértékegységét blokkolja",()=>{const pod=parseEonWorkbook(scheduledWorkbook(rowsFor("2026-08-02",96),{secondPodAt:2}),{referenceDate:"2026-08-03"});expect(pod.blockingErrors).toContain("EON_INVALID_INTERVAL");const unit=parseEonWorkbook(scheduledWorkbook(rowsFor("2026-08-02",96),{badUnitAt:2}),{referenceDate:"2026-08-03"});expect(unit.blockingErrors).toContain("EON_INVALID_INTERVAL")});
it("az aktuális részleges nap provisional",()=>{const x=parseEonWorkbook(workbook(rowsFor("2026-08-04",20)),{referenceDate:"2026-08-04"});expect(x.days[0].status).toBe("provisional")});
it("lezárt hiányos nap incomplete",()=>{const x=parseEonWorkbook(workbook(rowsFor("2026-08-03",20)),{referenceDate:"2026-08-04"});expect(x.days[0].status).toBe("incomplete")});
it("Date cellát, Excel serialt és magyar dátumszöveget kezel",()=>{const serial=(Date.UTC(2026,7,2,0,0)-Date.UTC(1899,11,30))/86400000,rows=[[new Date(Date.UTC(2026,7,2,0,0)),"0,25",0],[serial+.25/24,0,0],["2026.08.02 00:30",0,0]];const x=parseEonWorkbook(workbook(rows),{referenceDate:"2026-08-03"});expect(x.validRows).toBe(3);expect(x.intervals[0].importKwh).toBe(.25)});
it("üres értéket nem kever a nullával vagy nullával",()=>{const rows=rowsFor("2026-08-04",3,0,0);rows[2][1]=null;const x=parseEonWorkbook(workbook(rows),{referenceDate:"2026-08-04"});expect(x.validRows).toBe(2);expect(x.intervals[0].importKwh).toBe(0)});
it("negatív értéket blokkol",()=>{const rows=rowsFor("2026-08-02",96);rows[2][1]=-1;const x=parseEonWorkbook(workbook(rows),{referenceDate:"2026-08-03"});expect(x.blockingErrors).toContain("EON_NEGATIVE_VALUE")});
it("nem 15 perces és hibás dátum nem lesz intervallum",()=>{const rows=[["2026.08.02 00:07",1,1],["hibás",1,1]];const x=parseEonWorkbook(workbook(rows),{referenceDate:"2026-08-03"});expect(x.validRows).toBe(0)});
it("összesítő egyezést és eltérést ellenőriz",()=>{expect(parseEonWorkbook(workbook(rowsFor("2026-08-02",96))).summaryValidation.totalMatches).toBe(true);const bad=parseEonWorkbook(workbook(rowsFor("2026-08-02",96),{total:[999,999]}));expect(bad.blockingErrors).toContain("EON_SUMMARY_TOTAL_MISMATCH")});
it("több megfelelő munkalapot elutasít",()=>expect(()=>parseEonWorkbook(workbook(rowsFor("2026-08-02",96),{secondSheet:true}))).toThrowError(expect.objectContaining({code:"EON_AMBIGUOUS_WORKSHEET"})));
it("hiányzó fejlécet és sérült/túl nagy fájlt elutasít",()=>{const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([["más"]]),"x");expect(()=>parseEonWorkbook(XLSX.write(wb,{type:"buffer",bookType:"xlsx"}))).toThrowError(expect.objectContaining({code:"EON_WORKSHEET_NOT_FOUND"}));expect(()=>parseEonWorkbook(Buffer.from("PKbroken"))).toThrow();const huge=Buffer.alloc(EON_MAX_FILE_BYTES+1);huge[0]=0x50;huge[1]=0x4b;expect(()=>parseEonWorkbook(huge)).toThrowError(expect.objectContaining({code:"EON_FILE_TOO_LARGE"}))})});

describe("E.ON DST templates",()=>{
  it("a szigorú 96/92/4 tavaszi sablont forrássorrendben a valódi UTC intervallumokra igazítja",()=>{const rows=springTemplate(),x=parseEonWorkbook(workbook(rows),{referenceDate:"2026-03-30"}),window=localDayWindow("2026-03-29","Europe/Budapest");expect(x).toMatchObject({rawRows:96,validRows:92,invalidRows:0,completeDays:1,blockingErrors:[]});expect(x.warnings).toContain("DST_SPRING_TEMPLATE_ALIGNED");expect(x.intervals[0]).toMatchObject({intervalStartUtc:new Date(window.start).toISOString(),importKwh:1});expect(x.intervals.at(-1)?.intervalStartUtc).toBe(new Date(window.start+91*900000).toISOString());expect(x.summaryValidation).toEqual({totalMatches:true,maximumMatches:true})});
  it.each([[8,9,10],[8,9,10,11,12]])("eltérő számú üres sor esetén blokkol",(...blank)=>{const x=parseEonWorkbook(workbook(springTemplate(blank)),{referenceDate:"2026-03-30"});expect(x.blockingErrors).toContain("EON_DST_TEMPLATE_AMBIGUOUS");expect(x.warnings).not.toContain("DST_SPRING_TEMPLATE_ALIGNED")});
  it("részleges értékpár és rendezetlen timestamp esetén blokkol",()=>{const partial=springTemplate();partial[0][2]=null;expect(parseEonWorkbook(workbook(partial),{referenceDate:"2026-03-30"}).blockingErrors).toContain("EON_DST_TEMPLATE_AMBIGUOUS");const unordered=springTemplate();[unordered[0],unordered[1]]=[unordered[1],unordered[0]];expect(parseEonWorkbook(workbook(unordered),{referenceDate:"2026-03-30"}).blockingErrors).toContain("EON_DST_TEMPLATE_AMBIGUOUS")});
  it("normál napon nem aktiválódik, az őszi 96/100 forrásnap nem kap mesterséges rekordot",()=>{expect(parseEonWorkbook(workbook(rowsFor("2026-08-02",96)),{referenceDate:"2026-08-03"}).warnings).not.toContain("DST_SPRING_TEMPLATE_ALIGNED");const fall=parseEonWorkbook(workbook(rowsFor("2026-10-25",96)),{referenceDate:"2026-10-26"});expect(fall.intervals).toHaveLength(96);expect(fall.days[0].status).toBe("incomplete");expect(fall.warnings).toContain("DST_FALLBACK_SOURCE_96")});
  it("jövőbeli pontos tavaszi sablont sem igazít vagy importál",()=>{const result=parseEonWorkbook(workbook(springTemplate()),{referenceDate:"2026-03-28"});expect(result.blockingErrors).toContain("EON_FUTURE_INTERVAL_DATE");expect(result.warnings).not.toContain("DST_SPRING_TEMPLATE_ALIGNED");expect(result.intervals).toHaveLength(0);expect(result.validRows).toBe(0);expect(result.invalidRows).toBe(96)});
});
