import "server-only";
import { GrowattError } from "./errors";
import type { GrowattHttpMethod } from "./types";

type FetchLike=(input:string|URL,init?:RequestInit)=>Promise<Response>;
export type GrowattRequest={method?:GrowattHttpMethod;path:string;query?:Record<string,string>;body?:unknown};
export class GrowattClient{
  constructor(private readonly options:{baseUrl:string;token:string;authHeader:string;authValueTemplate:string;timeoutMs?:number;fetcher?:FetchLike}){}
  get(path:string,query:Record<string,string>={}){return this.request({method:"GET",path,query})}
  async request(request:GrowattRequest):Promise<unknown>{let last:GrowattError|undefined;for(let attempt=0;attempt<2;attempt++){try{return await this.once(request)}catch(error){const normalized=error instanceof GrowattError?error:new GrowattError("GROWATT_UNAVAILABLE",503,{cause:error});last=normalized;if(attempt===1||!(new Set(["GROWATT_TIMEOUT","GROWATT_RATE_LIMITED","GROWATT_UNAVAILABLE"])).has(normalized.code))throw normalized}}throw last!}
  private async once(request:GrowattRequest){const url=new URL(request.path,this.options.baseUrl);for(const[key,value]of Object.entries(request.query??{}))url.searchParams.set(key,value);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),this.options.timeoutMs??10_000),method=request.method??"GET",headers:Record<string,string>={Accept:"application/json",[this.options.authHeader]:this.options.authValueTemplate.replaceAll("{token}",this.options.token)};if(method==="POST"&&request.body!==undefined)headers["Content-Type"]="application/json";let response:Response;try{response=await(this.options.fetcher??fetch)(url,{method,headers,body:method==="POST"&&request.body!==undefined?JSON.stringify(request.body):undefined,signal:controller.signal,cache:"no-store"})}catch(error){if(error instanceof Error&&error.name==="AbortError")throw new GrowattError("GROWATT_TIMEOUT",503,{cause:error});throw new GrowattError("GROWATT_UNAVAILABLE",503,{cause:error})}finally{clearTimeout(timer)}if(response.status===401||response.status===403)throw new GrowattError("GROWATT_AUTH_FAILED",401);if(response.status===429)throw new GrowattError("GROWATT_RATE_LIMITED",429);if(response.status>=500)throw new GrowattError("GROWATT_UNAVAILABLE",503);if(!response.ok)throw new GrowattError("GROWATT_INVALID_RESPONSE",502);try{return await response.json()}catch(error){throw new GrowattError("GROWATT_INVALID_RESPONSE",502,{cause:error})}}
}
