import "server-only";
import { GrowattError } from "./errors";
import type { GrowattDeviceConfig,GrowattDeviceFieldMap,GrowattEndpointConfig,GrowattFieldMap,GrowattHttpMethod,GrowattLatestConfig,GrowattLatestFieldMap,GrowattPlantConfig,GrowattPlantFieldMap } from "./types";

const object=(value:unknown):value is Record<string,unknown>=>typeof value==="object"&&value!==null&&!Array.isArray(value),stringAt=(value:Record<string,unknown>,key:string)=>typeof value[key]==="string"&&!!(value[key]as string).trim();
const method=(value:string|undefined):GrowattHttpMethod=>value?.toUpperCase()==="POST"?"POST":"GET";
const notConfigured=()=>{throw new GrowattError("GROWATT_NOT_CONFIGURED",503)};
function parsedMap():GrowattFieldMap{let value:unknown;try{value=JSON.parse(process.env.GROWATT_FIELD_MAP_JSON??"")}catch{return notConfigured()}if(!object(value))return notConfigured();return value as GrowattFieldMap}
function validPlantMap(value:unknown):value is GrowattPlantFieldMap{return object(value)&&stringAt(value,"plantList")&&object(value.plant)&&stringAt(value.plant,"id")}
function validDeviceMap(value:unknown):value is GrowattDeviceFieldMap{return object(value)&&stringAt(value,"deviceList")&&object(value.device)&&stringAt(value.device,"id")&&stringAt(value.device,"serialNumber")}
function validLatestMap(value:unknown):value is GrowattLatestFieldMap{return object(value)&&object(value.latest)}
function base(){const token=process.env.GROWATT_API_TOKEN?.trim(),baseUrl=process.env.GROWATT_API_BASE_URL?.trim(),authHeader=process.env.GROWATT_API_AUTH_HEADER?.trim(),authValueTemplate=process.env.GROWATT_API_AUTH_VALUE_TEMPLATE?.trim();if(!token||!baseUrl||!authHeader||!authValueTemplate||!authValueTemplate.includes("{token}"))return notConfigured();try{const url=new URL(baseUrl);if(url.protocol!=="https:")return notConfigured()}catch{return notConfigured()}return{token,baseUrl,authHeader,authValueTemplate}}
export const growattTokenConfigured=()=>!!process.env.GROWATT_API_TOKEN?.trim();
export function configFingerprint(config:{baseUrl:string;authHeader:string;authValueTemplate?:string;credentialVersion?:string;paths:string[];fieldMaps:unknown[]}){const raw=[config.baseUrl,config.authHeader,config.authValueTemplate??"",config.credentialVersion??process.env.GROWATT_CREDENTIAL_VERSION?.trim()??"",...config.paths,...config.fieldMaps.map(map=>JSON.stringify(map))].join("|");let hash=2166136261;for(let index=0;index<raw.length;index++){hash^=raw.charCodeAt(index);hash=Math.imul(hash,16777619)}return(hash>>>0).toString(16)}
export function loadGrowattStatusConfig(){const common=base(),fieldMap=parsedMap(),plantsPath=process.env.GROWATT_PLANTS_PATH?.trim();if(!plantsPath||!validPlantMap(fieldMap))return notConfigured();const plant:GrowattPlantConfig={baseUrl:common.baseUrl,authHeader:common.authHeader,authValueTemplate:common.authValueTemplate,plantsPath,plantsMethod:method(process.env.GROWATT_PLANTS_METHOD),plantMap:fieldMap};let device:GrowattDeviceConfig|undefined;const devicesPath=process.env.GROWATT_DEVICES_PATH?.trim();if(devicesPath&&validDeviceMap(fieldMap))device={devicesPath,devicesMethod:method(process.env.GROWATT_DEVICES_METHOD),deviceMap:fieldMap};return{token:common.token,plant,device,fingerprint:configFingerprint({baseUrl:common.baseUrl,authHeader:common.authHeader,authValueTemplate:common.authValueTemplate,paths:[`${plant.plantsMethod}:${plantsPath}`,...(device?[`${device.devicesMethod}:${device.devicesPath}`]:[])],fieldMaps:[plant.plantMap,...(device?[device.deviceMap]:[])]})}}
export function loadGrowattLatestConfig(){const status=loadGrowattStatusConfig(),latestPath=process.env.GROWATT_LATEST_PATH?.trim(),fieldMap=parsedMap();if(!status.device||!latestPath||!validLatestMap(fieldMap))return notConfigured();const latest:GrowattLatestConfig={latestPath,latestMethod:method(process.env.GROWATT_LATEST_METHOD),latestMap:fieldMap},api:GrowattEndpointConfig={...status.plant,...status.device,...latest};return{token:status.token,api,fingerprint:configFingerprint({baseUrl:api.baseUrl,authHeader:api.authHeader,authValueTemplate:api.authValueTemplate,paths:[`${api.plantsMethod}:${api.plantsPath}`,`${api.devicesMethod}:${api.devicesPath}`,`${api.latestMethod}:${api.latestPath}`],fieldMaps:[api.plantMap,api.deviceMap,api.latestMap]})}}
