import type { GrowattDailyEnergyRow, GrowattMonthSummary } from "./historical";

export type GrowattHistoryResponse = { startDate: string; endDate: string; rows: GrowattDailyEnergyRow[]; summary?: { earliestDate: string | null; latestDate: string | null; storedDays: number; lastSyncAt: string | null } };
export type GrowattSyncResponse = { ok: boolean; partial: boolean; requestedDays: number; receivedValidDays: number; upsertedDays: number; missingDays: number; invalidRecords: number; duplicateRecords: number; chunks: number; successfulChunks: number; retryRanges: { startDate: string; endDate: string }[]; completedAt: string };
async function body<T>(response: Response): Promise<T> { const value = await response.json().catch(() => ({})) as T & { error?: { code?: string } }; if (!response.ok && response.status !== 207) throw new Error(value.error?.code ?? "HISTORY_UNAVAILABLE"); return value; }
export async function getGrowattHistory(startDate: string, endDate: string, fetcher: typeof fetch = fetch): Promise<GrowattHistoryResponse> { return body(await fetcher(`/api/growatt/history?startDate=${encodeURIComponent(startDate)}&endDate=${encodeURIComponent(endDate)}`, { credentials: "same-origin" })); }
export async function syncGrowattHistoryRange(startDate: string, endDate: string, fetcher: typeof fetch = fetch): Promise<GrowattSyncResponse> { return body(await fetcher("/api/growatt/history/sync", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ startDate, endDate }) })); }
export function budapestDate(date = new Date()): string { return new Intl.DateTimeFormat("sv-SE", { timeZone: "Europe/Budapest", year: "numeric", month: "2-digit", day: "2-digit" }).format(date); }
export function defaultGrowattSyncRange(today = budapestDate()): { startDate: string; endDate: string } { const end = new Date(`${today}T00:00:00Z`), start = new Date(end); start.setUTCDate(start.getUTCDate() - 27); return { startDate: start.toISOString().slice(0, 10), endDate: today }; }
export function historyStatusLabel(summary: GrowattMonthSummary): string { return summary.status === "complete" ? "Teljes" : summary.status === "in_progress" ? "Folyamatban" : "Részleges"; }
