import type { GrowattDailyEnergyRow, GrowattMonthSummary } from "./historical";
import type { GrowattJobSelection, GrowattSyncJob } from "./history-jobs";

export type GrowattHistoryResponse = { startDate: string; endDate: string; rows: GrowattDailyEnergyRow[]; summary?: { earliestDate: string | null; latestDate: string | null; storedDays: number; lastSyncAt: string | null } };
export type GrowattSyncResponse = { ok: boolean; partial: boolean; requestedDays: number; alreadyStoredDays: number; alreadyCompleteDays: number; refreshedProvisionalDays: number; requestedFromGrowattDays: number; receivedValidDays: number; upsertedDays: number; missingDays: number; invalidRecords: number; duplicateRecords: number; chunks: number; successfulChunks: number; retryRanges: { startDate: string; endDate: string }[]; completedAt: string };
async function body<T>(response: Response): Promise<T> { const value = await response.json().catch(() => ({})) as T & { error?: { code?: string } }; if (!response.ok && response.status !== 207) throw new Error(value.error?.code ?? "HISTORY_UNAVAILABLE"); return value; }
export async function getGrowattHistory(startDate: string, endDate: string, fetcher: typeof fetch = fetch): Promise<GrowattHistoryResponse> { return body(await fetcher(`/api/growatt/history?startDate=${encodeURIComponent(startDate)}&endDate=${encodeURIComponent(endDate)}`, { credentials: "same-origin" })); }
export async function syncGrowattHistoryRange(startDate: string, endDate: string, fetcher: typeof fetch = fetch): Promise<GrowattSyncResponse> { return body(await fetcher("/api/growatt/history/sync", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ startDate, endDate }) })); }
export function budapestDate(date = new Date()): string { return new Intl.DateTimeFormat("sv-SE", { timeZone: "Europe/Budapest", year: "numeric", month: "2-digit", day: "2-digit" }).format(date); }
export function defaultGrowattSyncRange(today = budapestDate()): { startDate: string; endDate: string } { const end = new Date(`${today}T00:00:00Z`), start = new Date(end); start.setUTCDate(start.getUTCDate() - 27); return { startDate: start.toISOString().slice(0, 10), endDate: today }; }
export function historyStatusLabel(summary: GrowattMonthSummary): string { return summary.status === "complete" ? "Teljes" : summary.status === "in_progress" ? "Folyamatban" : "Részleges"; }
export type GrowattJobState={job:GrowattSyncJob|null;lastFinishedJob?:GrowattSyncJob|null;historyStartMonth:string;completedMonth?:string|null};
export type GrowattHistoryStartMonthDraft={value:string;initialized:boolean;dirty:boolean};
// Ten seconds keeps multi-year sequential backfills deliberately below burst-like request rates.
export const GROWATT_HISTORY_BLOCK_DELAY_MS=10_000;
export const GROWATT_HISTORY_RETRY_SAFETY_MS=50;
export function mergeGrowattHistoryStartMonth(draft:GrowattHistoryStartMonthDraft,serverValue:string):GrowattHistoryStartMonthDraft{return draft.initialized&&draft.dirty?draft:{value:serverValue,initialized:true,dirty:false}}
export function editGrowattHistoryStartMonth(draft:GrowattHistoryStartMonthDraft,value:string):GrowattHistoryStartMonthDraft{return{...draft,value,initialized:true,dirty:true}}
export function savedGrowattHistoryStartMonth(value:string):GrowattHistoryStartMonthDraft{return{value,initialized:true,dirty:false}}
export function growattRetryDelayMs(job:Pick<GrowattSyncJob,"status"|"retry_after">,now=Date.now()):number|null{if(!["rate_limited","retry_pending"].includes(job.status)||!job.retry_after)return null;const retryAt=Date.parse(job.retry_after);return Number.isFinite(retryAt)?Math.max(0,retryAt-now)+GROWATT_HISTORY_RETRY_SAFETY_MS:null}
export function growattRetryDue(job:Pick<GrowattSyncJob,"status"|"retry_after">,now=Date.now()):boolean{if(!["rate_limited","retry_pending"].includes(job.status)||!job.retry_after)return false;const retryAt=Date.parse(job.retry_after);return Number.isFinite(retryAt)&&retryAt<=now}
export function acquireGrowattProcessRunner(lock:{current:boolean}):boolean{if(lock.current)return false;lock.current=true;return true}
export async function getGrowattSyncJob(fetcher:typeof fetch=fetch):Promise<GrowattJobState>{return body(await fetcher("/api/growatt/history/jobs",{credentials:"same-origin",cache:"no-store"}))}
export async function createGrowattSyncJob(input:{selection:GrowattJobSelection;customMonth?:string;historyStartMonth:string},fetcher:typeof fetch=fetch):Promise<GrowattJobState>{return body(await fetcher("/api/growatt/history/jobs",{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)}))}
export async function processGrowattSyncJob(id:string,fetcher:typeof fetch=fetch):Promise<GrowattJobState>{const response=await fetcher("/api/growatt/history/jobs/process",{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const value=await response.json().catch(()=>({})) as GrowattJobState&{error?:{code?:string}};if(!response.ok&&!(response.status===429&&value.job))throw new Error(value.error?.code??"HISTORY_UNAVAILABLE");return value}
export async function controlGrowattSyncJob(id:string,action:"pause"|"resume"|"cancel",fetcher:typeof fetch=fetch):Promise<GrowattJobState>{return body(await fetcher("/api/growatt/history/jobs",{method:"PATCH",credentials:"same-origin",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,action})}))}
export async function refreshSolarSnapshotMonth(month:string,fetcher:typeof fetch=fetch){return fetcher("/api/solar/monthly-snapshots/backfill",{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"Content-Type":"application/json"},body:JSON.stringify({startMonth:month,endMonth:month})})}
