import { describe, expect, it, vi } from "vitest";
vi.mock("server-only",()=>({}));
import { syncGrowattHistory, type HistoricalDatabase } from "./historical-sync";

const plant=()=>({plants:[{plant_id:"private",timezone:"Europe/Budapest"}]});
function database(){const stored=new Map<string,unknown>();const upsert=vi.fn(async(rows:unknown[],options?:{onConflict:string})=>{void options;for(const row of rows as {local_date:string}[])stored.set(row.local_date,row);return{error:null}});return{stored,upsert,db:{from:()=>({upsert})}as HistoricalDatabase}}
describe("Growatt historikus sync",()=>{
  it("7 napos blokkokat szekvenciálisan upsertel és ismételve idempotens",async()=>{const d=database(),api={plantList:async()=>plant(),plantEnergyHistory:vi.fn(async(_id:string,start:string,end:string)=>({time_unit:"day",energys:[{date:start,energy:"1"},{date:end,energy:2}]}))};await syncGrowattHistory({userId:"owner",startDate:"2026-07-27",endDate:"2026-08-03",database:d.db,api,now:new Date("2026-08-03T12:00:00Z")});await syncGrowattHistory({userId:"owner",startDate:"2026-07-27",endDate:"2026-08-03",database:d.db,api,now:new Date("2026-08-03T12:00:00Z")});expect(api.plantEnergyHistory).toHaveBeenCalledTimes(4);expect(d.stored.size).toBe(3);expect(d.upsert.mock.calls[0][1]).toEqual({onConflict:"user_id,local_date"})});
  it("egy későbbi hibás blokk mellett megőrzi az elsőt és részleges eredményt ad",async()=>{const d=database(),api={plantList:async()=>plant(),plantEnergyHistory:vi.fn().mockResolvedValueOnce({time_unit:"day",energys:[{date:"2026-07-20",energy:1}]}).mockRejectedValueOnce(new Error("offline"))};const result=await syncGrowattHistory({userId:"owner",startDate:"2026-07-20",endDate:"2026-08-02",database:d.db,api,now:new Date("2026-08-03T12:00:00Z")});expect(result.partial).toBe(true);expect(result.successfulChunks).toBe(1);expect(result.retryRanges).toEqual([{startDate:"2026-07-27",endDate:"2026-08-02"}]);expect(d.stored.size).toBe(1)});
  it("az adatbázis-hibát külön kóddal adja, nyers hiba nélkül",async()=>{const db={from:()=>({upsert:async()=>({error:{message:"private database detail"}})})}as HistoricalDatabase,api={plantList:async()=>plant(),plantEnergyHistory:async()=>({time_unit:"day",energys:[{date:"2026-08-01",energy:1}]})};await expect(syncGrowattHistory({userId:"owner",startDate:"2026-08-01",endDate:"2026-08-01",database:db,api,now:new Date("2026-08-03T12:00:00Z")})).rejects.toMatchObject({code:"HISTORY_DATABASE_WRITE_FAILED"})});
  it("részleges DB-hibánál receivedValidDays és upsertedDays eltér, az API-hibakódtól megkülönböztetve",async()=>{let call=0;const db={from:()=>({upsert:async()=>++call===1?{error:null}:{error:{message:"hidden"}}})}as HistoricalDatabase,api={plantList:async()=>plant(),plantEnergyHistory:vi.fn().mockResolvedValueOnce({time_unit:"day",energys:[{date:"2026-07-20",energy:1}]}).mockResolvedValueOnce({time_unit:"day",energys:[{date:"2026-07-27",energy:2}]})};const result=await syncGrowattHistory({userId:"owner",startDate:"2026-07-20",endDate:"2026-08-02",database:db,api,now:new Date("2026-08-03T12:00:00Z")});expect(result.receivedValidDays).toBe(2);expect(result.upsertedDays).toBe(1);expect(result.failedChunks[0].code).toBe("HISTORY_DATABASE_WRITE_FAILED")});
  it("részleges Growatt API-hiba nem adatbázis-hibakód",async()=>{const d=database(),api={plantList:async()=>plant(),plantEnergyHistory:vi.fn().mockResolvedValueOnce({time_unit:"day",energys:[{date:"2026-07-20",energy:1}]}).mockRejectedValueOnce(new Error("offline"))};const result=await syncGrowattHistory({userId:"owner",startDate:"2026-07-20",endDate:"2026-08-02",database:d.db,api,now:new Date("2026-08-03T12:00:00Z")});expect(result.failedChunks[0].code).toBe("GROWATT_UNAVAILABLE");expect(result.failedChunks[0].code).not.toBe("HISTORY_DATABASE_WRITE_FAILED")});
});
