import { addLocalDays, chunkGrowattDateRange, inclusiveDays, validIsoDate } from "./historical";

export type GrowattJobSelection = "current_month"|"previous_month"|"custom_month"|"repair_incomplete"|"full_history";
export type GrowattSyncJob = {id:string;selection_type:GrowattJobSelection;start_date:string;end_date:string;cursor_date:string;status:"queued"|"running"|"rate_limited"|"paused"|"retry_pending"|"finalizing_snapshots"|"completed"|"failed"|"cancelling"|"cancelled";claim_token:string|null;lease_expires_at:string|null;current_chunk_start:string|null;current_chunk_end:string|null;total_days:number;completed_days:number;already_complete_days:number;refreshed_days:number;failed_days:number;refreshed_dates:string[];failed_dates:string[];snapshot_pending_months:string[];snapshot_refreshed_months:string[];snapshot_failed_months:string[];snapshot_month_results:Record<string,{status:"refreshed"|"skipped"|"failed";reason?:string}>;snapshot_last_error_code:string|null;history_retry_count:number;snapshot_retry_count:number;invalid_records:number;duplicate_records:number;processed_chunks:number;retry_after:string|null;last_error_code:string|null;started_at:string|null;last_activity_at:string;completed_at:string|null;created_at:string};
const monthPattern=/^(19|2\d)\d{2}-(0[1-9]|1[0-2])$/;
export const validYearMonth=(value:string)=>monthPattern.test(value);
export const monthStart=(month:string)=>`${month}-01`;
export function monthEnd(month:string):string{const date=new Date(`${month}-01T00:00:00Z`);date.setUTCMonth(date.getUTCMonth()+1);date.setUTCDate(0);return date.toISOString().slice(0,10)}
export function previousMonth(month:string):string{const date=new Date(`${month}-01T00:00:00Z`);date.setUTCMonth(date.getUTCMonth()-1);return date.toISOString().slice(0,7)}
export function growattJobRange(selection:GrowattJobSelection,currentDate:string,customMonth:string|undefined,historyStartMonth:string):{startDate:string;endDate:string}{if(!validIsoDate(currentDate)||!validYearMonth(historyStartMonth))throw new Error("INVALID_RANGE");const currentMonth=currentDate.slice(0,7);if(selection==="current_month")return{startDate:monthStart(currentMonth),endDate:currentDate};if(selection==="previous_month"){const month=previousMonth(currentMonth);return{startDate:monthStart(month),endDate:monthEnd(month)}}if(selection==="custom_month"){if(!customMonth||!validYearMonth(customMonth)||customMonth>currentMonth)throw new Error("INVALID_RANGE");return{startDate:monthStart(customMonth),endDate:customMonth===currentMonth?currentDate:monthEnd(customMonth)}}if(historyStartMonth>currentMonth)throw new Error("INVALID_RANGE");return{startDate:monthStart(historyStartMonth),endDate:currentDate}}
export function nextGrowattJobChunk(cursorDate:string,endDate:string,completeDates:Iterable<string>){const complete=new Set(completeDates);let cursor=cursorDate;while(cursor<=endDate&&complete.has(cursor))cursor=addLocalDays(cursor,1);if(cursor>endDate)return null;let end=cursor;const currentMonthEnd=monthEnd(cursor.slice(0,7));while(end<endDate&&end<currentMonthEnd&&!complete.has(addLocalDays(end,1))&&inclusiveDays(cursor,addLocalDays(end,1))<=7)end=addLocalDays(end,1);return chunkGrowattDateRange(cursor,end,7)[0]}
export const jobProgress=(job:Pick<GrowattSyncJob,"completed_days"|"total_days">)=>job.total_days?Math.min(100,Math.round(job.completed_days/job.total_days*100)):0;
export type JobCoverage={localDate:string;qualityStatus:"complete"|"provisional"|"missing"|"invalid"};
export function satisfiedCoverageDates(rows:JobCoverage[],currentLocalDate:string){return new Set(rows.filter(row=>row.qualityStatus==="complete"||row.localDate===currentLocalDate&&row.qualityStatus==="provisional").map(row=>row.localDate))}
export function firstUnsettledDate(startDate:string,endDate:string,satisfied:Iterable<string>):string|null{const done=new Set(satisfied);for(let date=startDate;date<=endDate;date=addLocalDays(date,1))if(!done.has(date))return date;return null}
export function completeClosedMonths(startDate:string,endDate:string,currentLocalDate:string,satisfied:Iterable<string>):string[]{const done=new Set(satisfied),months:string[]=[];for(let month=startDate.slice(0,7);month<=endDate.slice(0,7);){const start=monthStart(month),end=monthEnd(month);if(end<currentLocalDate&&start>=monthStart(startDate.slice(0,7))&&end<=endDate){let complete=true;for(let date=start;date<=end;date=addLocalDays(date,1))if(!done.has(date)){complete=false;break}if(complete)months.push(month)}const next=new Date(`${month}-01T00:00:00Z`);next.setUTCMonth(next.getUTCMonth()+1);month=next.toISOString().slice(0,7)}return months}
export function publicGrowattJob(job: Record<string, unknown> | null) { if (!job) return null; const publicJob = { ...job }; delete publicJob.claim_token; delete publicJob.lease_expires_at; delete publicJob.user_id; return publicJob; }
export type SnapshotMonthOutcome={status:"refreshed"|"skipped"|"failed";reason?:string};
export function classifySnapshotBackfill(month:string,responseOk:boolean,body:Record<string,unknown>):SnapshotMonthOutcome{const details=Array.isArray(body.details)?body.details:[],detail=details.length===1&&typeof details[0]==="object"&&details[0]!==null&&(details[0]as Record<string,unknown>).yearMonth===month?details[0]as Record<string,unknown>:null,created=Number(body.createdOrUpdatedMonths??0),unchanged=Number(body.unchangedMonths??0),skipped=Number(body.skippedMonths??0),failed=Number(body.failedMonths??0);if(responseOk&&created+unchanged===1&&skipped===0&&failed===0&&detail&&["created_or_updated","unchanged"].includes(String(detail.status)))return{status:"refreshed"};if(responseOk&&skipped===1&&failed===0&&detail?.status==="skipped")return{status:"skipped",reason:typeof detail.reason==="string"?detail.reason:"adatminőségi_feltétel"};return{status:"failed",reason:"SNAPSHOT_REFRESH_FAILED"}}
const retryDelays=[30,120,300,900,3600] as const;
export function retryDecision(previousCount:number,now=Date.now()){const count=Math.max(0,previousCount)+1;return{count,failed:count>=5,delaySeconds:retryDelays[Math.min(count-1,retryDelays.length-1)],retryAt:new Date(now+retryDelays[Math.min(count-1,retryDelays.length-1)]*1000).toISOString()}}
