import { GrowattError } from "./errors";
import type { GrowattDeviceFieldMap,GrowattDeviceSummary,GrowattLatestEnergy,GrowattLatestFieldMap,GrowattPlantFieldMap,GrowattPlantSummary } from "./types";
type JsonObject=Record<string,unknown>;
const object=(value:unknown):value is JsonObject=>typeof value==="object"&&value!==null&&!Array.isArray(value);
export function valueAt(root:unknown,path:string|undefined):unknown{if(!path)return undefined;return path.split(".").reduce<unknown>((value,key)=>object(value)?value[key]:undefined,root)}
const text=(value:unknown)=>typeof value==="string"&&value.trim()?value.trim():typeof value==="number"&&Number.isFinite(value)?String(value):null;
export const safeNumber=(value:unknown)=>{if(typeof value==="number")return Number.isFinite(value)?value:null;if(typeof value==="string"&&value.trim()!==""){const parsed=Number(value);return Number.isFinite(parsed)?parsed:null}return null};
const listAt=(raw:unknown,path:string)=>{const value=valueAt(raw,path);if(!Array.isArray(value))throw new GrowattError("GROWATT_INVALID_RESPONSE",502);return value};
export function mapPlants(raw:unknown,map:GrowattPlantFieldMap):GrowattPlantSummary[]{return listAt(raw,map.plantList).map(item=>{const id=text(valueAt(item,map.plant.id));if(!id)throw new GrowattError("GROWATT_INVALID_RESPONSE",502);return{id,name:text(valueAt(item,map.plant.name)),timezone:text(valueAt(item,map.plant.timezone)),status:text(valueAt(item,map.plant.status))}})}
export function mapDevices(raw:unknown,map:GrowattDeviceFieldMap):GrowattDeviceSummary[]{return listAt(raw,map.deviceList).map(item=>{const id=text(valueAt(item,map.device.id)),serialNumber=text(valueAt(item,map.device.serialNumber));if(!id||!serialNumber)throw new GrowattError("GROWATT_INVALID_RESPONSE",502);return{id,serialNumber,type:text(valueAt(item,map.device.type)),model:text(valueAt(item,map.device.model)),status:text(valueAt(item,map.device.status)),plantId:text(valueAt(item,map.device.plantId))}})}
export function mapLatest(raw:unknown,map:GrowattLatestFieldMap,context:{plantId:string|null;deviceId:string|null;serialNumber:string|null}):GrowattLatestEnergy{if(!object(raw))throw new GrowattError("GROWATT_INVALID_RESPONSE",502);const capabilities=Object.entries(map.latest).filter(([,path])=>valueAt(raw,path)!==undefined&&valueAt(raw,path)!==null).map(([key])=>key),number=(key:keyof GrowattLatestFieldMap["latest"])=>safeNumber(valueAt(raw,map.latest[key])),dateValue=text(valueAt(raw,map.latest.measuredAt));return{plantId:context.plantId,deviceId:context.deviceId,deviceSerialNumber:context.serialNumber,measuredAt:dateValue&&Number.isFinite(Date.parse(dateValue))?new Date(dateValue).toISOString():null,currentPowerW:number("currentPowerW"),todayEnergyKwh:number("todayEnergyKwh"),monthEnergyKwh:number("monthEnergyKwh"),yearEnergyKwh:number("yearEnergyKwh"),lifetimeEnergyKwh:number("lifetimeEnergyKwh"),gridImportPowerW:number("gridImportPowerW"),gridExportPowerW:number("gridExportPowerW"),loadPowerW:number("loadPowerW"),batteryChargePowerW:number("batteryChargePowerW"),batteryDischargePowerW:number("batteryDischargePowerW"),batterySocPercent:number("batterySocPercent"),source:"growatt",rawCapabilities:capabilities}}
