import "server-only";
import { GrowattClient } from "./client";
import { loadGrowattLatestConfig,loadGrowattStatusConfig } from "./config";
import { GrowattError } from "./errors";
import { mapDevices,mapLatest,mapPlants } from "./mapper";
import { GrowattOpenApiV1,GROWATT_V1_BASE_URL,mapV1DeviceEnergy,mapV1Devices,mapV1PlantLatest,mapV1Plants,supportedV1DeviceType } from "./openapi-v1";
import { localIsoDate } from "@/lib/weather/date";
import { validGrowattTimezone } from "./time";
import type { GrowattConnectionStatus,GrowattDeviceConfig,GrowattDeviceSummary,GrowattLatestConfig,GrowattPlantConfig,GrowattLatestEnergy,GrowattPlantSummary,PublicGrowattLatestEnergy } from "./types";

export interface GrowattProvider{plants():Promise<GrowattPlantSummary[]>;devices?(plantId:string):Promise<GrowattDeviceSummary[]>;latest?(plant:GrowattPlantSummary,device:GrowattDeviceSummary):Promise<GrowattLatestEnergy>}
const fill=(template:string,values:Record<string,string>)=>Object.entries(values).reduce((result,[key,value])=>result.replaceAll(`{${key}}`,encodeURIComponent(value)),template);
export class HttpGrowattProvider implements GrowattProvider{constructor(private client:GrowattClient,private plant:GrowattPlantConfig,private device?:GrowattDeviceConfig,private latestConfig?:GrowattLatestConfig){}async plants(){return mapPlants(await this.client.request({method:this.plant.plantsMethod,path:this.plant.plantsPath}),this.plant.plantMap)}async devices(plantId:string){if(!this.device)throw new GrowattError("GROWATT_NOT_CONFIGURED",503);return mapDevices(await this.client.request({method:this.device.devicesMethod,path:fill(this.device.devicesPath,{plantId})}),this.device.deviceMap)}async latest(plant:GrowattPlantSummary,device:GrowattDeviceSummary){if(!this.latestConfig)throw new GrowattError("GROWATT_NOT_CONFIGURED",503);return mapLatest(await this.client.request({method:this.latestConfig.latestMethod,path:fill(this.latestConfig.latestPath,{plantId:plant.id,deviceId:device.id,serialNumber:device.serialNumber})}),this.latestConfig.latestMap,{plantId:plant.id,deviceId:device.id,serialNumber:device.serialNumber})}}
type V1ReadApi=Pick<GrowattOpenApiV1,"plantList"|"deviceList"|"plantEnergyOverview"|"plantPower"|"deviceEnergy">;
const localDateTime=(date:Date,timezone:string)=>{try{return new Intl.DateTimeFormat("sv-SE",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(date)}catch{return new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Budapest",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(date)}};
export class V1GrowattProvider implements GrowattProvider{constructor(private api:V1ReadApi,private now=()=>new Date()){}async plants(){return mapV1Plants(await this.api.plantList())}async devices(plantId:string){return mapV1Devices(await this.api.deviceList(plantId),plantId)}async latest(plant:GrowattPlantSummary,device:GrowattDeviceSummary){const type=supportedV1DeviceType(device.type);if(type===1){const now=this.now(),timezone=validGrowattTimezone(plant.timezone);const[plantData,powerData]=await Promise.all([this.api.plantEnergyOverview(plant.id),this.api.plantPower(plant.id,localIsoDate(now,timezone))]);return mapV1PlantLatest(plantData,powerData,{plantId:plant.id,device},localDateTime(now,timezone),timezone)}return mapV1DeviceEnergy(await this.api.deviceEnergy(type,device.serialNumber),{plantId:plant.id,device})}}

export function publicGrowattLatest(value:GrowattLatestEnergy):PublicGrowattLatestEnergy{return{deviceType:value.deviceType??null,deviceModel:value.deviceModel??null,deviceStatus:value.deviceStatus??null,measuredAt:value.measuredAt,currentPowerW:value.currentPowerW,todayEnergyKwh:value.todayEnergyKwh,monthEnergyKwh:value.monthEnergyKwh,yearEnergyKwh:value.yearEnergyKwh,lifetimeEnergyKwh:value.lifetimeEnergyKwh,gridImportPowerW:value.gridImportPowerW,gridExportPowerW:value.gridExportPowerW,loadPowerW:value.loadPowerW,batteryChargePowerW:value.batteryChargePowerW,batteryDischargePowerW:value.batteryDischargePowerW,batterySocPercent:value.batterySocPercent,source:value.source,rawCapabilities:value.rawCapabilities}}
const clientFor=(token:string,plant:GrowattPlantConfig)=>new GrowattClient({baseUrl:plant.baseUrl,authHeader:plant.authHeader,authValueTemplate:plant.authValueTemplate,token});
const v1Default=()=>{const token=process.env.GROWATT_API_TOKEN?.trim();if(!token)throw new GrowattError("GROWATT_NOT_CONFIGURED",503);const version=process.env.GROWATT_CREDENTIAL_VERSION?.trim()??"",baseUrl=process.env.GROWATT_API_BASE_URL?.trim()||GROWATT_V1_BASE_URL;return{provider:new V1GrowattProvider(new GrowattOpenApiV1(token,{baseUrl})),fingerprint:`v1:${baseUrl}:${version}`}}
export function defaultGrowattStatusProvider(){if(!process.env.GROWATT_FIELD_MAP_JSON?.trim())return v1Default();const config=loadGrowattStatusConfig(),http=new HttpGrowattProvider(clientFor(config.token,config.plant),config.plant,config.device);const provider:GrowattProvider=config.device?http:{plants:()=>http.plants()};return{provider,fingerprint:config.fingerprint}}
export function defaultGrowattLatestProvider(){if(!process.env.GROWATT_FIELD_MAP_JSON?.trim())return v1Default();const config=loadGrowattLatestConfig();return{provider:new HttpGrowattProvider(clientFor(config.token,config.api),config.api,config.api,config.api),fingerprint:config.fingerprint}}
function chooseSingle<T>(rows:T[],none:"GROWATT_NO_PLANT"|"GROWATT_NO_DEVICE"){if(!rows.length)throw new GrowattError(none,404);if(rows.length!==1)throw new GrowattError("GROWATT_UNSUPPORTED_DEVICE",409);return rows[0]}
export async function connectionStatus(provider:GrowattProvider,now=()=>new Date()):Promise<GrowattConnectionStatus>{const plants=await provider.plants();if(!plants.length)throw new GrowattError("GROWATT_NO_PLANT",404);let deviceCount:number|undefined;if(provider.devices){deviceCount=0;for(const plant of plants)deviceCount+=(await provider.devices(plant.id)).length}return{configured:true,connected:true,checkedAt:now().toISOString(),plantCount:plants.length,...(deviceCount===undefined?{}:{deviceCount})}}
export async function latestEnergy(provider:GrowattProvider){if(!provider.devices||!provider.latest)throw new GrowattError("GROWATT_NOT_CONFIGURED",503);const plant=chooseSingle(await provider.plants(),"GROWATT_NO_PLANT"),device=chooseSingle(await provider.devices(plant.id),"GROWATT_NO_DEVICE");return provider.latest(plant,device)}
type CacheItem<T>={expires:number;value:Promise<T>};const cache=new Map<string,CacheItem<unknown>>();
export function cached<T>(key:string,ttlMs:number,loader:()=>Promise<T>,now=Date.now):Promise<T>{const hit=cache.get(key)as CacheItem<T>|undefined;if(hit&&hit.expires>now())return hit.value;const value=loader().catch(error=>{cache.delete(key);throw error});cache.set(key,{expires:now()+ttlMs,value});return value}
export const clearGrowattCache=()=>cache.clear();
