import "server-only";
import { GrowattClient } from "./client";
import { loadGrowattLatestConfig,loadGrowattStatusConfig } from "./config";
import { GrowattError } from "./errors";
import { mapDevices,mapLatest,mapPlants } from "./mapper";
import type { GrowattConnectionStatus,GrowattDeviceConfig,GrowattDeviceSummary,GrowattLatestConfig,GrowattPlantConfig,GrowattLatestEnergy,GrowattPlantSummary } from "./types";

export interface GrowattProvider{plants():Promise<GrowattPlantSummary[]>;devices?(plantId:string):Promise<GrowattDeviceSummary[]>;latest?(plant:GrowattPlantSummary,device:GrowattDeviceSummary):Promise<GrowattLatestEnergy>}
const fill=(template:string,values:Record<string,string>)=>Object.entries(values).reduce((result,[key,value])=>result.replaceAll(`{${key}}`,encodeURIComponent(value)),template);
export class HttpGrowattProvider implements GrowattProvider{constructor(private client:GrowattClient,private plant:GrowattPlantConfig,private device?:GrowattDeviceConfig,private latestConfig?:GrowattLatestConfig){}async plants(){return mapPlants(await this.client.request({method:this.plant.plantsMethod,path:this.plant.plantsPath}),this.plant.plantMap)}async devices(plantId:string){if(!this.device)throw new GrowattError("GROWATT_NOT_CONFIGURED",503);return mapDevices(await this.client.request({method:this.device.devicesMethod,path:fill(this.device.devicesPath,{plantId})}),this.device.deviceMap)}async latest(plant:GrowattPlantSummary,device:GrowattDeviceSummary){if(!this.latestConfig)throw new GrowattError("GROWATT_NOT_CONFIGURED",503);return mapLatest(await this.client.request({method:this.latestConfig.latestMethod,path:fill(this.latestConfig.latestPath,{plantId:plant.id,deviceId:device.id,serialNumber:device.serialNumber})}),this.latestConfig.latestMap,{plantId:plant.id,deviceId:device.id,serialNumber:device.serialNumber})}}
const clientFor=(token:string,plant:GrowattPlantConfig)=>new GrowattClient({baseUrl:plant.baseUrl,authHeader:plant.authHeader,authValueTemplate:plant.authValueTemplate,token});
export function defaultGrowattStatusProvider(){const config=loadGrowattStatusConfig(),http=new HttpGrowattProvider(clientFor(config.token,config.plant),config.plant,config.device);const provider:GrowattProvider=config.device?http:{plants:()=>http.plants()};return{provider,fingerprint:config.fingerprint}}
export function defaultGrowattLatestProvider(){const config=loadGrowattLatestConfig();return{provider:new HttpGrowattProvider(clientFor(config.token,config.api),config.api,config.api,config.api),fingerprint:config.fingerprint}}
function chooseSingle<T>(rows:T[],none:"GROWATT_NO_PLANT"|"GROWATT_NO_DEVICE"){if(!rows.length)throw new GrowattError(none,404);if(rows.length!==1)throw new GrowattError("GROWATT_UNSUPPORTED_DEVICE",409);return rows[0]}
export async function connectionStatus(provider:GrowattProvider,now=()=>new Date()):Promise<GrowattConnectionStatus>{const plants=await provider.plants();if(!plants.length)throw new GrowattError("GROWATT_NO_PLANT",404);let deviceCount:number|undefined;if(provider.devices){deviceCount=0;for(const plant of plants)deviceCount+=(await provider.devices(plant.id)).length}return{configured:true,connected:true,checkedAt:now().toISOString(),plantCount:plants.length,...(deviceCount===undefined?{}:{deviceCount})}}
export async function latestEnergy(provider:GrowattProvider){if(!provider.devices||!provider.latest)throw new GrowattError("GROWATT_NOT_CONFIGURED",503);const plant=chooseSingle(await provider.plants(),"GROWATT_NO_PLANT"),device=chooseSingle(await provider.devices(plant.id),"GROWATT_NO_DEVICE");return provider.latest(plant,device)}
type CacheItem<T>={expires:number;value:Promise<T>};const cache=new Map<string,CacheItem<unknown>>();
export function cached<T>(key:string,ttlMs:number,loader:()=>Promise<T>,now=Date.now):Promise<T>{const hit=cache.get(key)as CacheItem<T>|undefined;if(hit&&hit.expires>now())return hit.value;const value=loader().catch(error=>{cache.delete(key);throw error});cache.set(key,{expires:now()+ttlMs,value});return value}
export const clearGrowattCache=()=>cache.clear();
