import { describe, expect, it, vi } from "vitest";
import { fetchGrowattUiData, formatGrowattEnergy, formatGrowattMeasuredAt, formatGrowattPower, growattErrorMessage, growattFreshness, singleFlight } from "./ui";

describe("Growatt UI számítások", () => {
  it("W és kW értéket olvashatóan formáz", () => { expect(formatGrowattPower(999)).toBe("999 W"); expect(formatGrowattPower(2840)).toBe("2,84 kW"); expect(formatGrowattPower(0)).toBe("0 W"); });
  it("kWh értéket magyar ezres tagolással formáz", () => expect(formatGrowattEnergy(12345.67)).toContain("12\u00a0345,67 kWh"));
  it("UTC mérési időt Budapest időzónában jelenít meg", () => expect(formatGrowattMeasuredAt("2026-08-03T07:30:00.000Z")).toContain("09:30"));
  it("friss, késleltetett, elavult és ismeretlen kategóriát különböztet meg", () => { const now = Date.parse("2026-08-03T10:00:00Z"); expect(growattFreshness("2026-08-03T09:50:00Z", now)).toBe("fresh"); expect(growattFreshness("2026-08-03T09:30:00Z", now)).toBe("delayed"); expect(growattFreshness("2026-08-03T08:00:00Z", now)).toBe("stale"); expect(growattFreshness(null, now)).toBe("unknown"); });
  it.each([[401,"ANY","jelentkezz be"],[403,"GROWATT_AUTH_FAILED","hitelesítés sikertelen"],[403,"FORBIDDEN","nem jogosult"],[503,"GROWATT_NOT_CONFIGURED","nincs teljesen beállítva"],[403,"GROWATT_PERMISSION_DENIED","nem rendelkezik megfelelő"],[429,"GROWATT_RATE_LIMITED","túl sok kérést"],[503,"GROWATT_TIMEOUT","nem válaszolt időben"]] as const)("%s / %s magyar hibaszöveget ad", (status, code, part) => expect(growattErrorMessage({ status, code })).toContain(part));
  it("normál áttekintés-betöltésnél csak latestet kér, külön status feloldás nélkül", async () => { const latest = { measuredAt: null, currentPowerW: 100, todayEnergyKwh: 1, monthEnergyKwh: null, yearEnergyKwh: null, lifetimeEnergyKwh: null, gridImportPowerW: null, gridExportPowerW: null, loadPowerW: null, batteryChargePowerW: null, batteryDischargePowerW: null, batterySocPercent: null, deviceType: "1", deviceModel: null, deviceStatus: null, source: "growatt", rawCapabilities: ["currentPowerW"] }; const fetcher = vi.fn(async (input: string | URL | Request) => { expect(String(input)).toBe("/api/growatt/latest"); return new Response(JSON.stringify(latest), { status: 200 }); }); const result = await fetchGrowattUiData(fetcher as typeof fetch); expect(result).toMatchObject({ status: { configured: true, connected: true }, latest: { currentPowerW: 100 } }); expect(fetcher).toHaveBeenCalledOnce(); });
  it("a latest konfigurálatlan hibáját változatlan kóddal továbbadja", async () => { const fetcher = vi.fn(async () => new Response(JSON.stringify({ error: { code: "GROWATT_NOT_CONFIGURED" } }), { status: 503 })); await expect(fetchGrowattUiData(fetcher as typeof fetch)).rejects.toMatchObject({ status: 503, code: "GROWATT_NOT_CONFIGURED" }); expect(fetcher).toHaveBeenCalledOnce(); });
  it("a kézi frissítés párhuzamos kattintásait egy kérésbe vonja össze", async () => { let resolve!: (value: number) => void; const loader = vi.fn<() => Promise<number>>().mockImplementationOnce(() => new Promise<number>(done => { resolve = done; })).mockResolvedValue(2); const refresh = singleFlight(loader); const first = refresh(), second = refresh(); expect(first).toBe(second); expect(loader).toHaveBeenCalledOnce(); resolve(1); await first; expect(await refresh()).toBe(2); expect(loader).toHaveBeenCalledTimes(2); });
});
