import { describe, expect, it, vi } from "vitest";
import { clearGrowattUiRuntimeCache, fetchGrowattUiData, formatGrowattEnergy, formatGrowattMeasuredAt, formatGrowattPower, formatGrowattRelativeTime, growattDeviceStatusDisplay, growattDeviceTypeLabel, growattErrorMessage, growattFreshness, loadGrowattSessionSnapshot, singleFlight, suppressGrowattLatestRefresh } from "./ui";

describe("Growatt UI számítások", () => {
  it("W és kW értéket olvashatóan formáz", () => { expect(formatGrowattPower(999)).toBe("999 W"); expect(formatGrowattPower(2840)).toBe("2,84 kW"); expect(formatGrowattPower(0)).toBe("0 W"); });
  it("kWh értéket magyar ezres tagolással formáz", () => expect(formatGrowattEnergy(12345.67)).toContain("12\u00a0345,67 kWh"));
  it("UTC mérési időt Budapest időzónában jelenít meg", () => expect(formatGrowattMeasuredAt("2026-08-03T07:30:00.000Z")).toContain("09:30"));
  it("relatív mérési időt magyarul jelenít meg", () => expect(formatGrowattRelativeTime("2026-08-03T09:54:00Z", Date.parse("2026-08-03T10:00:00Z"))).toBe("6 perce"));
  it.each([["1","Hálózatra tápláló inverter"],["2","Energiatároló"],["3","Egyéb Growatt eszköz"],["4","Growatt MAX inverter"],["5","Growatt SPH/MIX hibrid inverter"],["6","Growatt SPA"],["7","Growatt MIN/TLX inverter"],["8","Growatt PCS"],["9","Growatt HPS"],["10","Growatt PBD"]])("a %s device type magyar címkéje %s", (value, label) => expect(growattDeviceTypeLabel(value)).toBe(label));
  it("ismeretlen device type konzervatív fallbacket kap", () => { expect(growattDeviceTypeLabel("99")).toBe("Ismeretlen eszköztípus"); expect(growattDeviceTypeLabel(null)).toBe("Ismeretlen eszköztípus"); });
  it("nem igazolt device statushoz nem talál ki üzemállapotot", () => expect(growattDeviceStatusDisplay("1")).toEqual({ label: "Elérhető adat", technicalCode: "1" }));
  it("friss, késleltetett, elavult és ismeretlen kategóriát különböztet meg", () => { const now = Date.parse("2026-08-03T10:00:00Z"); expect(growattFreshness("2026-08-03T09:50:00Z", now)).toBe("fresh"); expect(growattFreshness("2026-08-03T09:30:00Z", now)).toBe("delayed"); expect(growattFreshness("2026-08-03T08:00:00Z", now)).toBe("stale"); expect(growattFreshness(null, now)).toBe("unknown"); });
  it.each([[401,"ANY","jelentkezz be"],[403,"GROWATT_AUTH_FAILED","hitelesítés sikertelen"],[403,"FORBIDDEN","nem jogosult"],[503,"GROWATT_NOT_CONFIGURED","nincs teljesen beállítva"],[403,"GROWATT_PERMISSION_DENIED","nem rendelkezik megfelelő"],[429,"GROWATT_RATE_LIMITED","túl sok kérést"],[503,"GROWATT_TIMEOUT","nem válaszolt időben"]] as const)("%s / %s magyar hibaszöveget ad", (status, code, part) => expect(growattErrorMessage({ status, code })).toContain(part));
  it("normál áttekintés-betöltésnél csak latestet kér, külön status feloldás nélkül", async () => { const latest = { measuredAt: null, currentPowerW: 100, todayEnergyKwh: 1, monthEnergyKwh: null, yearEnergyKwh: null, lifetimeEnergyKwh: null, gridImportPowerW: null, gridExportPowerW: null, loadPowerW: null, batteryChargePowerW: null, batteryDischargePowerW: null, batterySocPercent: null, deviceType: "1", deviceModel: null, deviceStatus: null, source: "growatt", rawCapabilities: ["currentPowerW"] }; const fetcher = vi.fn(async (input: string | URL | Request) => { expect(String(input)).toBe("/api/growatt/latest"); return new Response(JSON.stringify(latest), { status: 200 }); }); const result = await fetchGrowattUiData(fetcher as typeof fetch); expect(result).toMatchObject({ status: { configured: true, connected: true }, latest: { currentPowerW: 100 } }); expect(fetcher).toHaveBeenCalledOnce(); });
  it("history sync utáni cooldownban a korábbi latest snapshotot adja új API-hívás nélkül", async () => { clearGrowattUiRuntimeCache(); const latest = { measuredAt: null, currentPowerW: 100, todayEnergyKwh: 1, monthEnergyKwh: null, yearEnergyKwh: null, lifetimeEnergyKwh: null, gridImportPowerW: null, gridExportPowerW: null, loadPowerW: null, batteryChargePowerW: null, batteryDischargePowerW: null, batterySocPercent: null, deviceType: "1", deviceModel: null, deviceStatus: null, source: "growatt", rawCapabilities: ["currentPowerW"] }; const fetcher = vi.fn(async () => new Response(JSON.stringify(latest), { status: 200 })); const before = await fetchGrowattUiData(fetcher as typeof fetch); suppressGrowattLatestRefresh(15_000); const after = await fetchGrowattUiData(fetcher as typeof fetch); expect(after).toBe(before); expect(fetcher).toHaveBeenCalledOnce(); clearGrowattUiRuntimeCache(); });
  it("a latest konfigurálatlan hibáját változatlan kóddal továbbadja", async () => { const fetcher = vi.fn(async () => new Response(JSON.stringify({ error: { code: "GROWATT_NOT_CONFIGURED" } }), { status: 503 })); await expect(fetchGrowattUiData(fetcher as typeof fetch)).rejects.toMatchObject({ status: 503, code: "GROWATT_NOT_CONFIGURED" }); expect(fetcher).toHaveBeenCalledOnce(); });
  it("a kézi frissítés párhuzamos kattintásait egy kérésbe vonja össze", async () => { let resolve!: (value: number) => void; const loader = vi.fn<() => Promise<number>>().mockImplementationOnce(() => new Promise<number>(done => { resolve = done; })).mockResolvedValue(2); const refresh = singleFlight(loader); const first = refresh(), second = refresh(); expect(first).toBe(second); expect(loader).toHaveBeenCalledOnce(); resolve(1); await first; expect(await refresh()).toBe(2); expect(loader).toHaveBeenCalledTimes(2); });
});

class MemoryStorage {
  values = new Map<string,string>();
  getItem(key:string){return this.values.get(key)??null} setItem(key:string,value:string){this.values.set(key,value)} removeItem(key:string){this.values.delete(key)}
}
const sessionLatest = { measuredAt:"2026-08-03T07:30:00Z",currentPowerW:100,todayEnergyKwh:1,monthEnergyKwh:2,yearEnergyKwh:3,lifetimeEnergyKwh:4,gridImportPowerW:null,gridExportPowerW:null,loadPowerW:null,batteryChargePowerW:null,batteryDischargePowerW:null,batterySocPercent:null,deviceType:"1",deviceModel:"MIN",deviceStatus:"1",source:"growatt",rawCapabilities:["currentPowerW"] };
describe("Growatt sessionStorage cache",()=>{
  it("history sync és F5-et szimuláló runtime reset után nem kér latestet",async()=>{const storage=new MemoryStorage(),fetcher=vi.fn(async()=>new Response(JSON.stringify(sessionLatest),{status:200}));clearGrowattUiRuntimeCache();await fetchGrowattUiData(fetcher as typeof fetch,{storage,now:1000});suppressGrowattLatestRefresh(15_000,1000,storage);clearGrowattUiRuntimeCache();const restored=await fetchGrowattUiData(fetcher as typeof fetch,{storage,now:2000});expect(restored.latest?.currentPowerW).toBe(100);expect(fetcher).toHaveBeenCalledOnce();clearGrowattUiRuntimeCache()});
  it("a session snapshot közvetlenül visszatölthető",async()=>{const storage=new MemoryStorage(),fetcher=vi.fn(async()=>new Response(JSON.stringify(sessionLatest),{status:200}));clearGrowattUiRuntimeCache();await fetchGrowattUiData(fetcher as typeof fetch,{storage,now:1000});clearGrowattUiRuntimeCache();expect(loadGrowattSessionSnapshot(storage,2000)?.latest).toMatchObject({currentPowerW:100,deviceModel:"MIN"});clearGrowattUiRuntimeCache()});
  it("lejárt cooldown után ismét történik latest kérés",async()=>{const storage=new MemoryStorage(),fetcher=vi.fn(async()=>new Response(JSON.stringify(sessionLatest),{status:200}));clearGrowattUiRuntimeCache();await fetchGrowattUiData(fetcher as typeof fetch,{storage,now:1000});suppressGrowattLatestRefresh(100,1000,storage);clearGrowattUiRuntimeCache();await fetchGrowattUiData(fetcher as typeof fetch,{storage,now:2000});expect(fetcher).toHaveBeenCalledTimes(2);clearGrowattUiRuntimeCache()});
  it("hibás JSON-t töröl",()=>{const storage=new MemoryStorage();storage.setItem("wattmerleg:growatt:latest:v1","not-json");expect(loadGrowattSessionSnapshot(storage,2000)).toBeNull();expect(storage.getItem("wattmerleg:growatt:latest:v1")).toBeNull()});
  it("verzióeltérést töröl",()=>{const storage=new MemoryStorage();storage.setItem("wattmerleg:growatt:latest:v1",JSON.stringify({version:999,savedAt:1000,data:sessionLatest}));expect(loadGrowattSessionSnapshot(storage,2000)).toBeNull();expect(storage.getItem("wattmerleg:growatt:latest:v1")).toBeNull()});
  it("a tárolt DTO explicit allowlistje kizárja az érzékeny azonosítókat",async()=>{const storage=new MemoryStorage(),response={...sessionLatest,plantId:"private",deviceId:"private",deviceSerialNumber:"private",userId:"private",token:"private"};clearGrowattUiRuntimeCache();await fetchGrowattUiData(async()=>new Response(JSON.stringify(response),{status:200}),{storage,now:1000});const stored=[...storage.values.values()].join(" ");expect(stored).not.toMatch(/plantId|deviceId|deviceSerialNumber|userId|token/);clearGrowattUiRuntimeCache()});
  it("kézi force felülírja a cooldownt, 429 után a session snapshot megmarad",async()=>{const storage=new MemoryStorage();clearGrowattUiRuntimeCache();await fetchGrowattUiData(async()=>new Response(JSON.stringify(sessionLatest),{status:200}),{storage,now:1000});suppressGrowattLatestRefresh(15_000,1000,storage);await expect(fetchGrowattUiData(async()=>new Response(JSON.stringify({error:{code:"GROWATT_RATE_LIMITED"}}),{status:429}),{storage,now:2000,force:true})).rejects.toMatchObject({code:"GROWATT_RATE_LIMITED"});expect(loadGrowattSessionSnapshot(storage,2000)?.latest?.currentPowerW).toBe(100);clearGrowattUiRuntimeCache()});
});
