import{accessToken}from"./oauth";import{EonGmailError}from"./errors";import{MAX_MIME_DEPTH,type GmailPart}from"./mime";import{constrainedQuery,type GmailHeader}from"./sender";
export type GmailMessage={id:string;internalDate?:string;sizeEstimate?:number;payload:GmailPart&{headers?:GmailHeader[]}};
export type GmailListResult={ids:string[];truncated:boolean};const API="https://gmail.googleapis.com/gmail/v1/users/me";export const GMAIL_LIST_PAGE_SIZE=10,GMAIL_MAX_LIST_PAGES=5,GMAIL_MAX_CANDIDATE_IDS=50;
const METADATA_FIELDS="id,internalDate,sizeEstimate,payload(headers(name,value))";
const partFields=(depth:number,inline=false):string=>`filename,mimeType,body(${inline?"data,":""}attachmentId,size)${depth>0?`,parts(${partFields(depth-1,inline)})`:""}`;
export const FULL_FIELDS=`id,internalDate,sizeEstimate,payload(${partFields(MAX_MIME_DEPTH)})`;
export const INLINE_FIELDS=`id,internalDate,sizeEstimate,payload(${partFields(MAX_MIME_DEPTH,true)})`;
export class GmailClient{constructor(private fetcher:typeof fetch=fetch,private token=accessToken,private sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms))){}
 private async call(path:string,force=false,retried=false):Promise<Response>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10_000);try{const token=await this.token(force,this.fetcher),r=await this.fetcher(`${API}${path}`,{headers:{authorization:`Bearer ${token}`},signal:controller.signal,cache:"no-store"});if(r.status===401&&!force)return this.call(path,true,retried);if(r.status===401)throw new EonGmailError("EON_GMAIL_TOKEN_INVALID",503,false);if(r.status===400)throw new EonGmailError("EON_GMAIL_NOT_CONFIGURED",503,false);if(r.status===403)throw new EonGmailError("EON_GMAIL_FORBIDDEN",403,false);if(r.status===404)throw new EonGmailError("EON_GMAIL_INVALID_MESSAGE",404,false);if((r.status===429||r.status>=500)&&!retried){const raw=Number(r.headers.get("retry-after")??"1");await this.sleep(Math.min(3000,Math.max(0,raw*1000)));return this.call(path,force,true)}if(r.status===429)throw new EonGmailError("EON_GMAIL_RATE_LIMITED",429,true);if(r.status>=500)throw new EonGmailError("EON_GMAIL_REQUEST_FAILED",503,true);if(!r.ok)throw new EonGmailError("EON_GMAIL_REQUEST_FAILED",503,false);return r}catch(e){if(e instanceof EonGmailError)throw e;if((e as Error).name==="AbortError")throw new EonGmailError("EON_GMAIL_TIMEOUT",504,true);throw new EonGmailError("EON_GMAIL_REQUEST_FAILED",503,true)}finally{clearTimeout(timer)}}
 async profile(){return await(await this.call("/profile")).json() as{emailAddress:string}}
 async list(query:string,allowedFrom:string):Promise<GmailListResult>{const ids:string[]=[];let page="",truncated=false;for(let pages=0;pages<GMAIL_MAX_LIST_PAGES&&ids.length<GMAIL_MAX_CANDIDATE_IDS;pages++){const q=new URLSearchParams({q:constrainedQuery(query,allowedFrom),maxResults:String(GMAIL_LIST_PAGE_SIZE),fields:"messages(id),nextPageToken"});if(page)q.set("pageToken",page);const x=await(await this.call(`/messages?${q}`)).json() as{messages?:{id:string}[];nextPageToken?:string};ids.push(...(x.messages??[]).map(v=>v.id));page=x.nextPageToken??"";if(!page)break;if(pages===GMAIL_MAX_LIST_PAGES-1||ids.length>=GMAIL_MAX_CANDIDATE_IDS)truncated=true}return{ids:ids.slice(0,GMAIL_MAX_CANDIDATE_IDS).reverse(),truncated}}
 async metadata(id:string){const q=new URLSearchParams({format:"metadata",metadataHeaders:"From",fields:METADATA_FIELDS});return await(await this.call(`/messages/${encodeURIComponent(id)}?${q}`)).json() as GmailMessage}
 async message(id:string){const q=new URLSearchParams({format:"full",fields:FULL_FIELDS});return await(await this.call(`/messages/${encodeURIComponent(id)}?${q}`)).json() as GmailMessage}
 async inlineMessage(id:string){const q=new URLSearchParams({format:"full",fields:INLINE_FIELDS});return await(await this.call(`/messages/${encodeURIComponent(id)}?${q}`)).json() as GmailMessage}
 async attachment(messageId:string,id:string){const q=new URLSearchParams({fields:"data,size"}),x=await(await this.call(`/messages/${encodeURIComponent(messageId)}/attachments/${encodeURIComponent(id)}?${q}`)).json() as{data?:string;size?:number};if(!x.data)throw new EonGmailError("EON_GMAIL_INVALID_MESSAGE",422);return{data:x.data,size:x.size}}}
