import{createHash,randomBytes}from"node:crypto";import{gmailConfig,type EonGmailConfig}from"./config";import{EonGmailError}from"./errors";
export const GMAIL_READONLY_SCOPE="https://www.googleapis.com/auth/gmail.readonly";
export const base64url=(value:Buffer)=>value.toString("base64url");
export function oauthChallenge(){const verifier=base64url(randomBytes(48));return{state:base64url(randomBytes(32)),verifier,challenge:base64url(createHash("sha256").update(verifier).digest())}}
export function authorizationUrl(args:{clientId:string;redirectUri:string;state:string;challenge:string}){const q=new URLSearchParams({client_id:args.clientId,redirect_uri:args.redirectUri,response_type:"code",scope:GMAIL_READONLY_SCOPE,access_type:"offline",prompt:"consent",state:args.state,code_challenge:args.challenge,code_challenge_method:"S256"});return`https://accounts.google.com/o/oauth2/v2/auth?${q}`}
type Token={access_token?:string;expires_in?:number;refresh_token?:string};
async function tokenRequest(body:URLSearchParams,fetcher:typeof fetch,timeoutMs=10_000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetcher("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body,cache:"no-store",signal:controller.signal});if(!r.ok)throw new EonGmailError(r.status===400?"EON_GMAIL_TOKEN_INVALID":"EON_GMAIL_REQUEST_FAILED",r.status===400?503:503,r.status!==400);let value:Token;try{value=await r.json() as Token}catch{throw new EonGmailError("EON_GMAIL_TOKEN_INVALID",503)}return value}catch(e){if(e instanceof EonGmailError)throw e;if((e as Error).name==="AbortError")throw new EonGmailError("EON_GMAIL_TIMEOUT",504,true);throw new EonGmailError("EON_GMAIL_REQUEST_FAILED",503,true)}finally{clearTimeout(timer)}}
export async function exchangeCode(config:EonGmailConfig,args:{code:string;redirectUri:string;verifier:string},fetcher:typeof fetch=fetch){return tokenRequest(new URLSearchParams({client_id:config.clientId,client_secret:config.clientSecret,code:args.code,redirect_uri:args.redirectUri,code_verifier:args.verifier,grant_type:"authorization_code"}),fetcher)}
let cached:{token:string;expiresAt:number;version:string}|null=null,flight:Promise<string>|null=null;
export async function accessToken(force=false,fetcher:typeof fetch=fetch,env=process.env){const c=gmailConfig(env),now=Date.now();if(!force&&cached&&cached.version===c.credentialVersion&&cached.expiresAt>now+60_000)return cached.token;if(force)cached=null;if(flight)return flight;flight=(async()=>{const x=await tokenRequest(new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,refresh_token:c.refreshToken,grant_type:"refresh_token"}),fetcher);if(!x.access_token)throw new EonGmailError("EON_GMAIL_TOKEN_INVALID",503);cached={token:x.access_token,expiresAt:Date.now()+Math.max(0,(x.expires_in??3600)*1000),version:c.credentialVersion};return x.access_token})();try{return await flight}finally{flight=null}}
export const resetTokenCache=()=>{cached=null;flight=null};
