import{createHash}from"node:crypto";import{importEonWorkbook,type EonParseResult}from"@/lib/eon-import/import-service";import{EonImportError}from"@/lib/eon-import/errors";import{localIsoDate}from"@/lib/weather/date";import{gmailConfig,type EonGmailConfig}from"./config";import{GmailClient,type GmailListResult}from"./client";import{assertMessageSize,decodeAttachment,findXlsx}from"./mime";import{asGmailError,EonGmailError}from"./errors";import{senderAddress}from"./sender";
type Admin=NonNullable<Awaited<ReturnType<typeof defaultAdmin>>>;type FinishStatus="imported"|"duplicate"|"ignored"|"retry"|"failed";export type IngestionResult={examined:number;claimed:number;imported:number;duplicates:number;ignored:number;retrying:number;failed:number;codes:string[]};type Deps={db?:Admin;gmail?:GmailClient;importWorkbook?:typeof importEonWorkbook;env?:NodeJS.ProcessEnv};
async function defaultAdmin(){return(await import("@/lib/supabase/admin")).createAdminClient()}
export function gmailInternalDate(value:unknown){if(typeof value!=="string"||!/^\d{11,16}$/.test(value))throw new EonGmailError("EON_GMAIL_INVALID_MESSAGE",422);const ms=Number(value);if(!Number.isSafeInteger(ms)||!Number.isFinite(ms))throw new EonGmailError("EON_GMAIL_INVALID_MESSAGE",422);const date=new Date(ms);if(Number.isNaN(date.getTime()))throw new EonGmailError("EON_GMAIL_INVALID_MESSAGE",422);return date.toISOString()}
const day=(iso:string)=>Math.floor(Date.parse(`${iso}T00:00:00Z`)/86_400_000);
export function validateAutomaticPeriod(parsed:EonParseResult,emailInternalDate:string,config:Pick<EonGmailConfig,"maxWorkbookDays"|"maxPeriodLagDays">){if(!parsed.periodStart||!parsed.periodEnd)throw new EonGmailError("EON_GMAIL_PERIOD_REJECTED",422,false);const start=day(parsed.periodStart),end=day(parsed.periodEnd),mail=day(localIsoDate(new Date(emailInternalDate),"Europe/Budapest"));if(!Number.isFinite(start)||!Number.isFinite(end)||end<start||end-start+1>config.maxWorkbookDays||end>mail||mail-end>config.maxPeriodLagDays)throw new EonGmailError("EON_GMAIL_PERIOD_REJECTED",422,false)}
async function finish(db:Admin,userId:string,messageId:string,token:string,status:FinishStatus,error:string|null,hash:string|null,batch:string|null,internalDate:string|null){const response=await db.rpc("finish_eon_gmail_message",{target_user_id:userId,target_gmail_message_id:messageId,target_claim_token:token,target_status:status,target_error_code:error,target_attachment_sha256:hash,target_import_batch_id:batch,target_internal_date:internalDate});if(response.error||!response.data)throw new EonGmailError("EON_GMAIL_DATABASE_ERROR",503,true);return response.data as FinishStatus}
async function existingBatch(db:Admin,userId:string,id:string,hash:string){const response=await db.from("eon_import_batches").select("id").eq("user_id",userId).or(`external_message_id.eq.${id},attachment_sha256.eq.${hash}`).limit(1).maybeSingle();if(response.error)throw new EonGmailError("EON_GMAIL_DATABASE_ERROR",503,true);return response.data?.id as string|undefined}
async function saveState(db:Admin,userId:string,verified:boolean,error:string|null,successful=false){const now=new Date().toISOString(),response=await db.from("eon_gmail_ingestion_state").upsert({user_id:userId,mailbox_verified:verified,last_run_at:now,last_error_code:error,updated_at:now,...(successful?{last_successful_import_at:now}:{})},{onConflict:"user_id"});if(response.error)throw new EonGmailError("EON_GMAIL_DATABASE_ERROR",503,true)}
async function dueRetryIds(db:Admin,userId:string){const table=db.from("eon_gmail_messages") as unknown as{select?:(fields:string)=>unknown};if(typeof table.select!=="function")return[];let chain=table.select("gmail_message_id") as unknown as{eq:(field:string,value:unknown)=>unknown};chain=chain.eq("user_id",userId) as typeof chain;chain=chain.eq("status","retry") as typeof chain;const response=await(((chain as unknown as{lte:(field:string,value:string)=>unknown}).lte("next_retry_at",new Date().toISOString()) as{order:(field:string,options:unknown)=>unknown}).order("internal_date",{ascending:true}) as{limit:(count:number)=>Promise<{data?:{gmail_message_id:string}[];error?:unknown}>}).limit(5);if(response.error)throw new EonGmailError("EON_GMAIL_DATABASE_ERROR",503,true);return(response.data??[]).map(x=>x.gmail_message_id)}
export function classifyProcessingError(raw:unknown):{status:FinishStatus;code:string}{if(raw instanceof EonImportError){if(raw.code==="EON_ALREADY_IMPORTED")return{status:"duplicate",code:raw.code};if(raw.code==="EON_DATABASE_ERROR")return{status:"retry",code:raw.code};return{status:"ignored",code:raw.code}}const e=asGmailError(raw);return{status:e.transient?"retry":e.code==="EON_GMAIL_INVALID_MESSAGE"||e.code==="EON_GMAIL_ATTACHMENT_REJECTED"||e.code==="EON_GMAIL_SENDER_REJECTED"||e.code==="EON_GMAIL_PERIOD_REJECTED"?"ignored":"failed",code:e.code}}
const listResult=(value:GmailListResult|string[]):GmailListResult=>Array.isArray(value)?{ids:value,truncated:false}:value;
export async function runEonGmailIngestion(userId:string,deps:Deps={}):Promise<IngestionResult>{const db=deps.db??await defaultAdmin();if(!db)throw new EonGmailError("EON_GMAIL_NOT_CONFIGURED",503);let verified=false;try{const config=gmailConfig(deps.env),gmail=deps.gmail??new GmailClient(),importWorkbook=deps.importWorkbook??importEonWorkbook,result:IngestionResult={examined:0,claimed:0,imported:0,duplicates:0,ignored:0,retrying:0,failed:0,codes:[]},profile=await gmail.profile();if(profile.emailAddress.toLowerCase()!==config.expectedAddress)throw new EonGmailError("EON_GMAIL_FORBIDDEN",403);verified=true;const listed=listResult(await gmail.list(config.query,config.allowedFrom)),due=await dueRetryIds(db,userId),ids=[...new Set([...due,...listed.ids])];result.examined=ids.length;if(listed.truncated)result.codes.push("EON_GMAIL_SCAN_LIMIT_REACHED");
 for(const id of ids){if(result.claimed>=5)break;const claimResponse=await db.rpc("claim_eon_gmail_message",{target_user_id:userId,target_gmail_message_id:id,target_internal_date:null}),claim=Array.isArray(claimResponse.data)?claimResponse.data[0]:claimResponse.data;if(claimResponse.error)throw new EonGmailError("EON_GMAIL_DATABASE_ERROR",503,true);if(!claim?.claim_token)continue;result.claimed++;let hash:string|null=null,internalDate:string|null=null;
  try{
   const metadata=await gmail.metadata(id);assertMessageSize(metadata.sizeEstimate);internalDate=gmailInternalDate(metadata.internalDate);senderAddress(metadata.payload.headers,config.allowedFrom);
   const message=await gmail.message(id);assertMessageSize(message.sizeEstimate);const ref=findXlsx(message.payload);let encoded:string,declared=ref.declaredSize;
   if(ref.attachmentId){const attachment=await gmail.attachment(id,ref.attachmentId);encoded=attachment.data;declared=attachment.size??declared;if(declared!==ref.declaredSize)throw new EonGmailError("EON_GMAIL_ATTACHMENT_REJECTED",413)}
   else{const inline=await gmail.inlineMessage(id);assertMessageSize(inline.sizeEstimate);const inlineRef=findXlsx(inline.payload);if(inlineRef.filename!==ref.filename||inlineRef.mimeType!==ref.mimeType||inlineRef.declaredSize!==ref.declaredSize||inlineRef.attachmentId||!inlineRef.data)throw new EonGmailError("EON_GMAIL_INVALID_MESSAGE",422);encoded=inlineRef.data}
   const bytes=decodeAttachment(encoded,declared);hash=createHash("sha256").update(bytes).digest("hex");const existing=await existingBatch(db,userId,id,hash);if(existing){await finish(db,userId,id,claim.claim_token,"duplicate",null,hash,existing,internalDate);result.duplicates++;continue}
   try{const imported=await importWorkbook({userId,bytes,source:"eon_portal_export",externalMessageId:id,client:{rpc:db.rpc.bind(db)},validateParsed:parsed=>validateAutomaticPeriod(parsed,internalDate!,config)});await finish(db,userId,id,claim.claim_token,"imported",null,hash,imported.batchId,internalDate);result.imported++}catch(raw){if(raw instanceof EonImportError&&raw.code==="EON_ALREADY_IMPORTED"){const raced=await existingBatch(db,userId,id,hash);if(raced){await finish(db,userId,id,claim.claim_token,"duplicate",null,hash,raced,internalDate);result.duplicates++;continue}}throw raw}}
  catch(raw){const classified=classifyProcessingError(raw),saved=await finish(db,userId,id,claim.claim_token,classified.status,classified.code,hash,null,internalDate);if(saved==="retry")result.retrying++;else if(saved==="ignored")result.ignored++;else result.failed++;result.codes.push(classified.code)}}await saveState(db,userId,true,result.codes.at(-1)??null,result.imported>0);return result}catch(raw){const error=asGmailError(raw);try{await saveState(db,userId,verified,error.code)}catch{}throw error}}
