import {addCalendarDays} from "./date";import type{DailyWeather,WeatherLocation}from"./types";
export interface CachedWeather extends DailyWeather{locationKey:string;fetchedAt:string}
export const weatherLocationKey=(location:WeatherLocation)=>`${location.latitude.toFixed(4)},${location.longitude.toFixed(4)}|${location.timezone}`;
export function dateRange(start:string,end:string){const result:string[]=[];for(let date=start,dateGuard=0;date<=end&&dateGuard++<10000;date=addCalendarDays(date,1))result.push(date);return result}
export function missingWeatherDates(cached:CachedWeather[],start:string,end:string,today:string,refreshRecent=false){const byDate=new Map(cached.map(row=>[row.date,row])),recentStart=addCalendarDays(today,-6);return dateRange(start,end).filter(date=>{const row=byDate.get(date);if(!row)return true;if(date<recentStart)return false;if(refreshRecent)return true;return Date.parse(row.fetchedAt)<Date.parse(`${recentStart}T00:00:00Z`)})}
export function contiguousDateRanges(dates:string[]){if(!dates.length)return[];const sorted=[...new Set(dates)].sort(),result:{start:string;end:string}[]=[];let start=sorted[0],end=start;for(const date of sorted.slice(1)){if(date===addCalendarDays(end,1))end=date;else{result.push({start,end});start=end=date}}result.push({start,end});return result}
export function mergeCachedWeather(cached:CachedWeather[],fresh:DailyWeather[],locationKey:string,fetchedAt=new Date().toISOString()){const map=new Map(cached.map(row=>[`${row.locationKey}|${row.date}`,row]));for(const row of fresh)map.set(`${locationKey}|${row.date}`,{...row,locationKey,fetchedAt});return [...map.values()].filter(row=>row.locationKey===locationKey).sort((a,b)=>a.date.localeCompare(b.date))}
export async function resolveHistoricalWeather(input:{cached:CachedWeather[];start:string;end:string;today:string;locationKey:string;forceRefresh?:boolean;fetchRange:(start:string,end:string)=>Promise<DailyWeather[]>;upsert:(rows:CachedWeather[])=>Promise<void>;now?:string}){const missing=missingWeatherDates(input.cached,input.start,input.end,input.today,input.forceRefresh),ranges=contiguousDateRanges(missing);let combined=input.cached,fetchCount=0;for(const range of ranges){try{const fresh=await input.fetchRange(range.start,range.end);fetchCount++;const rows=mergeCachedWeather([],fresh,input.locationKey,input.now);await input.upsert(rows);combined=mergeCachedWeather(combined,fresh,input.locationKey,input.now)}catch{/* A meglévő cache továbbra is használható. */}}return{weather:combined.filter(row=>row.date>=input.start&&row.date<=input.end).map(({date,meanC,minC,maxC})=>({date,meanC,minC,maxC})),fetchCount,missingCount:missing.length,complete:dateRange(input.start,input.end).every(date=>combined.some(row=>row.locationKey===input.locationKey&&row.date===date))}}
export async function readAllCachePages<T>(fetchPage:(from:number,to:number)=>Promise<T[]>,pageSize=500):Promise<T[]>{const rows:T[]=[];for(let from=0,pageGuard=0;pageGuard++<10000;from+=pageSize){const page=await fetchPage(from,from+pageSize-1);rows.push(...page);if(page.length<pageSize)break}return rows}
