import type { DailyWeather, WeatherLocation, WeatherProvider } from "./types";
const parseDaily = (data: { daily?: { time?: string[]; temperature_2m_mean?: number[]; temperature_2m_min?: number[]; temperature_2m_max?: number[] } }): DailyWeather[] => (data.daily?.time ?? []).map((date, i) => ({ date, meanC: data.daily!.temperature_2m_mean![i], minC: data.daily!.temperature_2m_min![i], maxC: data.daily!.temperature_2m_max![i] })).filter(x => [x.meanC,x.minC,x.maxC].every(Number.isFinite));
async function json(url: URL) { const response = await fetch(url, { cache: "no-store" }); if (!response.ok) throw new Error(`Időjárási szolgáltatási hiba (${response.status}).`); return response.json(); }
function base(path: string, location: WeatherLocation) { const url = new URL(path); url.searchParams.set("latitude", String(location.latitude)); url.searchParams.set("longitude", String(location.longitude)); url.searchParams.set("timezone", location.timezone); return url; }
export class OpenMeteoProvider implements WeatherProvider {
  async getCurrentWeather(location: WeatherLocation) { const url=base("https://api.open-meteo.com/v1/forecast",location); url.searchParams.set("current","temperature_2m"); const data=await json(url) as {current?:{temperature_2m:number;time:string}}; if(!data.current) throw new Error("Nincs aktuális időjárási adat."); return {temperatureC:data.current.temperature_2m,observedAt:data.current.time}; }
  async getDailyWeather(location: WeatherLocation, days=7) { const url=base("https://api.open-meteo.com/v1/forecast",location); url.searchParams.set("daily","temperature_2m_mean,temperature_2m_min,temperature_2m_max"); url.searchParams.set("forecast_days",String(Math.min(16,Math.max(1,days)))); return parseDaily(await json(url)); }
  async getHistoricalWeather(location: WeatherLocation,start:string,end:string) { const url=base("https://archive-api.open-meteo.com/v1/archive",location); url.searchParams.set("start_date",start); url.searchParams.set("end_date",end); url.searchParams.set("daily","temperature_2m_mean,temperature_2m_min,temperature_2m_max"); return parseDaily(await json(url)); }
}
