import { describe, expect, it } from "vitest";
import { analyzeSolarMonth, summarizeSolarPeriod, type SolarMonthInput } from "./consumption-analysis";

const valid = (overrides: Partial<SolarMonthInput> = {}): SolarMonthInput => ({ yearMonth: "2026-07", currentYearMonth: "2026-08", meterTimezone: "Europe/Budapest", pvTimezone: "Europe/Budapest", gridImportKwh: 600, gridExportKwh: 400, meterDataQuality: "complete", pvProductionKwh: 1000, pvExpectedDays: 31, pvStoredDays: 31, pvCompleteDays: 31, pvProvisionalDays: 0, pvMissingDays: 0, pvInvalidDays: 0, pvPeriodStartLocalDate: "2026-07-01", pvPeriodEndLocalDate: "2026-07-31", meterCoverageStartAt: "2026-06-30T22:00:00.000Z", meterCoverageEndAt: "2026-07-31T22:00:00.000Z", meterCoverageStartLocalDate: "2026-07-01", meterCoverageEndLocalDate: "2026-08-01", meterCoversRequiredStart: true, meterCoversRequiredEnd: true, ...overrides });

describe("havi napelem és házfogyasztás elemzés", () => {
  it("érvényes hónapnál a dokumentált képleteket használja", () => { const result = analyzeSolarMonth(valid()); expect(result).toMatchObject({ status: "complete", selfConsumedPvKwh: 600, totalHomeConsumptionKwh: 1200, pvSelfConsumptionRatio: .6, pvCoverageRatio: .5 }); });
  it("0 kWh PV-nél az önfogyasztási arány null, de a házfogyasztás érvényes", () => { const result = analyzeSolarMonth(valid({ pvProductionKwh: 0, gridExportKwh: 0 })); expect(result.status).toBe("complete"); expect(result.pvSelfConsumptionRatio).toBeNull(); expect(result.totalHomeConsumptionKwh).toBe(600); });
  it("0 exportnál minden PV helyben felhasználtnak becsült", () => expect(analyzeSolarMonth(valid({ gridExportKwh: 0 })).selfConsumedPvKwh).toBe(1000));
  it("0 import érvényes pozitív helyi PV mellett", () => expect(analyzeSolarMonth(valid({ gridImportKwh: 0 })).totalHomeConsumptionKwh).toBe(600));
  it.each([{ gridExportKwh: 1001 }, { gridImportKwh: -1 }, { pvProductionKwh: -1 }])("ellentmondásos vagy negatív inputnál null mutatókat ad", values => { const result = analyzeSolarMonth(valid(values)); expect(result.status).toBe("inconsistent_inputs"); expect(result.selfConsumedPvKwh).toBeNull(); expect(result.pvSelfConsumptionRatio).toBeNull(); });
  it("hiányos Growatt coverage nem számol százalékot", () => { const result = analyzeSolarMonth(valid({ pvStoredDays: 30 })); expect(result.status).toBe("incomplete_pv_coverage"); expect(result.pvCoverageRatio).toBeNull(); });
  it("lezárt provisional hónapot elutasítja, az aktuális azonos végpontú hónapot folyamatban lévőnek jelöli", () => { expect(analyzeSolarMonth(valid({ pvCompleteDays: 30, pvProvisionalDays: 1 })).status).toBe("incomplete_pv_coverage"); expect(analyzeSolarMonth(valid({ yearMonth: "2026-08", pvExpectedDays: 3, pvStoredDays: 3, pvCompleteDays: 2, pvProvisionalDays: 1, pvPeriodStartLocalDate: "2026-08-01", pvPeriodEndLocalDate: "2026-08-03", meterCoverageStartAt: "2026-07-31T22:00:00.000Z", meterCoverageEndAt: "2026-08-03T22:00:00.000Z", meterCoverageStartLocalDate: "2026-08-01", meterCoverageEndLocalDate: "2026-08-04" })).status).toBe("in_progress"); });
  it("hiányos lezárt mérőcoverage és aktuális period mismatch minden mutatót nulláz", () => { const incomplete = analyzeSolarMonth(valid({ meterCoversRequiredStart: false })), mismatch = analyzeSolarMonth(valid({ yearMonth: "2026-08", pvPeriodStartLocalDate: "2026-08-01", pvPeriodEndLocalDate: "2026-08-03", meterCoverageEndAt: "2026-08-02T08:00:00.000Z", meterCoversRequiredEnd: false })); expect(incomplete.status).toBe("incomplete_meter_coverage"); expect(incomplete.totalHomeConsumptionKwh).toBeNull(); expect(mismatch.status).toBe("period_mismatch"); expect(mismatch.pvCoverageRatio).toBeNull(); });
  it("period mismatch nem kerül az összesítőbe", () => { const mismatch = analyzeSolarMonth(valid({ yearMonth: "2026-08", meterCoversRequiredEnd: false })); expect(summarizeSolarPeriod([mismatch])).toMatchObject({ includedMonths: 0, excludedMonths: 1 }); });
  it("időarányos mérőhónapot becsültnek jelöl", () => expect(analyzeSolarMonth(valid({ meterDataQuality: "estimated" })).status).toBe("estimated_meter_allocation"));
  it("timezone mismatch és hiányzó források külön állapotot kapnak", () => { expect(analyzeSolarMonth(valid({ pvTimezone: "UTC" })).status).toBe("timezone_mismatch"); expect(analyzeSolarMonth(valid({ gridImportKwh: null })).status).toBe("missing_meter_data"); expect(analyzeSolarMonth(valid({ pvProductionKwh: null, pvStoredDays: 0 })).status).toBe("missing_pv_data"); });
});

describe("időszaki napelemes összesítő", () => {
  it("összegekből súlyozott arányt számol, nem havi százalékátlagot", () => { const months = [analyzeSolarMonth(valid()), analyzeSolarMonth(valid({ yearMonth: "2026-06", gridImportKwh: 100, gridExportKwh: 0, pvProductionKwh: 100 }))]; const result = summarizeSolarPeriod(months); expect(result.pvSelfConsumptionRatio).toBeCloseTo(700 / 1100); expect(result.pvSelfConsumptionRatio).not.toBeCloseTo((.6 + 1) / 2); });
  it("hibás hónapot kizár és becsült hónapot számlál", () => { const result = summarizeSolarPeriod([analyzeSolarMonth(valid({ meterDataQuality: "estimated" })), analyzeSolarMonth(valid({ yearMonth: "2026-06", pvStoredDays: 2 }))]); expect(result).toMatchObject({ includedMonths: 1, excludedMonths: 1, estimatedMeterMonths: 1, fullPvCoverage: false }); });
});
