import { describe, expect, it } from "vitest";
import { analyzeSolarMonth, type SolarMonthInput } from "./consumption-analysis";
import { finalizableMonthlySnapshot, monthlySnapshotFingerprint, relevantMeterRevision, snapshotFingerprintUnchanged, validateSnapshotBackfillRange } from "./monthly-snapshot-service";

const input = (overrides: Partial<SolarMonthInput> = {}): SolarMonthInput => ({ yearMonth: "2026-07", currentYearMonth: "2026-08", meterTimezone: "Europe/Budapest", pvTimezone: "Europe/Budapest", meterYearMonth: "2026-07", pvYearMonth: "2026-07", gridImportKwh: 500, gridExportKwh: 200, meterDataQuality: "complete", pvProductionKwh: 800, pvExpectedDays: 31, pvStoredDays: 31, pvCompleteDays: 31, pvProvisionalDays: 0, pvMissingDays: 0, pvInvalidDays: 0, pvPeriodStartLocalDate: "2026-07-01", pvPeriodEndLocalDate: "2026-07-31", meterCoverageStartAt: "2026-06-30T22:00:00Z", meterCoverageEndAt: "2026-07-31T22:00:00Z", meterCoverageStartLocalDate: "2026-07-01", meterCoverageEndLocalDate: "2026-08-01", meterCoversRequiredStart: true, meterCoversRequiredEnd: true, ...overrides });
const fp = (overrides = {}) => monthlySnapshotFingerprint({ userId: "u", yearMonth: "2026-07", meterReadingCount: 2, meterMaxUpdatedAt: "2026-08-01", growattRecordCount: 31, growattMaxUpdatedAt: "2026-08-02", meterTimezone: "Europe/Budapest", growattTimezone: "Europe/Budapest", ...overrides });
describe("solar monthly snapshots", () => {
  it("stable inputs have a stable fingerprint", () => expect(fp()).toBe(fp()));
  it("uses the unchanged fingerprint fast path", () => { expect(snapshotFingerprintUnchanged(fp(), fp())).toBe(true); expect(snapshotFingerprintUnchanged(fp(), fp({ growattRecordCount: 30 }))).toBe(false); });
  it("only includes readings relevant to the selected month", () => { const rows = [{ id: "start", updated_at: "2026-08-01" }, { id: "end", updated_at: "2026-08-02" }, { id: "other", updated_at: "2099-01-01" }]; expect(relevantMeterRevision(rows, ["start", "end"])).toEqual({ meterReadingCount: 2, meterMaxUpdatedAt: "2026-08-02" }); rows[2].updated_at = "2100-01-01"; expect(relevantMeterRevision(rows, ["start", "end"])).toEqual({ meterReadingCount: 2, meterMaxUpdatedAt: "2026-08-02" }); expect(relevantMeterRevision(rows, ["start"])).toEqual({ meterReadingCount: 1, meterMaxUpdatedAt: "2026-08-01" }); });
  it.each([["meter edit", { meterMaxUpdatedAt: "2026-08-03" }], ["Growatt edit", { growattMaxUpdatedAt: "2026-08-03" }], ["algorithm", { algorithmVersion: 2 }], ["timezone", { growattTimezone: "UTC" }]])("%s changes fingerprint", (_, change) => expect(fp(change)).not.toBe(fp()));
  it("finalizes a complete closed month", () => expect(finalizableMonthlySnapshot({ analysis: analyzeSolarMonth(input()), userId: "u", currentMonth: "2026-08", fingerprint: fp() })).toHaveProperty("snapshot.analysis_status", "complete"));
  it("preserves estimated meter allocation", () => expect(finalizableMonthlySnapshot({ analysis: analyzeSolarMonth(input({ meterDataQuality: "estimated" })), userId: "u", currentMonth: "2026-08", fingerprint: fp() })).toHaveProperty("snapshot.meter_source", "manual_readings"));
  it("does not finalize current or incomplete months", () => { expect(finalizableMonthlySnapshot({ analysis: analyzeSolarMonth(input({ yearMonth: "2026-08", currentYearMonth: "2026-08", meterYearMonth: "2026-08", pvYearMonth: "2026-08" })), userId: "u", currentMonth: "2026-08", fingerprint: fp() })).toHaveProperty("skip"); expect(finalizableMonthlySnapshot({ analysis: analyzeSolarMonth(input({ pvStoredDays: 30 })), userId: "u", currentMonth: "2026-08", fingerprint: fp() })).toHaveProperty("skip", "incomplete_pv_coverage"); });
  it("does not upsert a snapshot with null PV coverage ratio", () => { const analysis = analyzeSolarMonth(input()); analysis.pvCoverageRatio = null; expect(finalizableMonthlySnapshot({ analysis, userId: "u", currentMonth: "2026-08", fingerprint: fp() })).toHaveProperty("skip"); });
  it.each([["2026-07", "2026-07", 1], ["2025-08", "2026-07", 12], ["2024-08", "2026-07", 24]])("accepts a closed backfill range", (start, end, count) => { const result = validateSnapshotBackfillRange(start as string, end as string, "2026-08"); expect(result.ok).toBe(true); if (result.ok) expect(result.months).toHaveLength(count as number); });
  it("rejects 25 months and the current month", () => { expect(validateSnapshotBackfillRange("2024-07", "2026-07", "2026-08")).toEqual({ ok: false, code: "MONTH_RANGE_TOO_LONG" }); expect(validateSnapshotBackfillRange("2026-08", "2026-08", "2026-08")).toEqual({ ok: false, code: "MONTH_NOT_CLOSED" }); });
});
