import{createServer}from"node:http";import{mkdtemp,readFile,writeFile}from"node:fs/promises";import{tmpdir}from"node:os";import{join}from"node:path";import{describe,expect,it,vi}from"vitest";import{isCliEntrypoint,loadLocalEnvironment,replaceRefreshToken,waitForCallback}from"./gmail-authorize";
async function listening(){const server=createServer();await new Promise<void>(ok=>server.listen(0,"127.0.0.1",ok));const address=server.address();if(!address||typeof address==="string")throw new Error();return{server,origin:`http://127.0.0.1:${address.port}`}}
describe("Gmail OAuth CLI",()=>{
 it("loads project .env.local without override",()=>{const loader=vi.fn();loadLocalEnvironment("C:\\repo",loader);expect(loader).toHaveBeenCalledWith({path:expect.stringMatching(/repo[\\/].env\.local$/),override:false})});
 it("recognizes a Windows file URL entrypoint",()=>expect(isCliEntrypoint("C:\\repo\\scripts\\gmail-authorize.ts","file:///C:/repo/scripts/gmail-authorize.ts")).toBe(true));
 it("preserves other lines and replaces token",async()=>{const dir=await mkdtemp(join(tmpdir(),"gmail-auth-")),path=join(dir,".env.local"),key=["GMAIL","REFRESH","TOKEN"].join("_");await writeFile(path,`OTHER=value\n${key}=old\nLAST=kept\n`);await replaceRefreshToken(path,"new-value");expect(await readFile(path,"utf8")).toBe(`OTHER=value\n${key}=new-value\nLAST=kept\n`)});
 it("adds a missing token line",async()=>{const dir=await mkdtemp(join(tmpdir(),"gmail-auth-")),path=join(dir,".env.local");await writeFile(path,"OTHER=value\n");await replaceRefreshToken(path,"new-value");expect(await readFile(path,"utf8")).toContain("new-value")});
 it("rejects state mismatch",async()=>{const{server,origin}=await listening(),waiting=waitForCallback(server,`${origin}/callback`,"right",1000),assertion=expect(waiting).rejects.toThrow("Invalid OAuth callback");await fetch(`${origin}/callback?state=wrong&code=code`);await assertion;server.close()});
 it("ignores favicon and times out",async()=>{const{server,origin}=await listening(),waiting=waitForCallback(server,`${origin}/callback`,"right",20),assertion=expect(waiting).rejects.toThrow("timeout");await fetch(`${origin}/favicon.ico`);await assertion;server.close()});
 it("does not print token values",async()=>{const log=vi.spyOn(console,"log").mockImplementation(()=>{}),error=vi.spyOn(console,"error").mockImplementation(()=>{}),dir=await mkdtemp(join(tmpdir(),"gmail-auth-")),path=join(dir,".env.local"),secret="private-test-value";await replaceRefreshToken(path,secret);expect(JSON.stringify([...log.mock.calls,...error.mock.calls])).not.toContain(secret);log.mockRestore();error.mockRestore()})});
