import{createServer}from"node:http";
import{mkdtemp,readFile,writeFile}from"node:fs/promises";
import{tmpdir}from"node:os";
import{join}from"node:path";
import{describe,expect,it,vi}from"vitest";
import{browserCommand,isCliEntrypoint,loadLocalEnvironment,loopbackRedirectUri,oauthRedirectContract,openBrowser,replaceRefreshToken,waitForCallback}from"./gmail-authorize";

async function listening(){const server=createServer();await new Promise<void>(ok=>server.listen(0,"127.0.0.1",ok));const address=server.address();if(!address||typeof address==="string")throw new Error();return{server,origin:`http://127.0.0.1:${address.port}`}}
const close=(server:ReturnType<typeof createServer>)=>new Promise<void>(done=>server.close(()=>done()));
const flow={state:"state-value",challenge:"challenge-value",verifier:"verifier-value"};

describe("Gmail OAuth CLI",()=>{
 it("loads project .env.local without override",()=>{const loader=vi.fn();loadLocalEnvironment("C:\\repo",loader);expect(loader).toHaveBeenCalledWith({path:expect.stringMatching(/repo[\\/].env\.local$/),override:false})});
 it("recognizes a Windows file URL entrypoint",()=>expect(isCliEntrypoint("C:\\repo\\scripts\\gmail-authorize.ts","file:///C:/repo/scripts/gmail-authorize.ts")).toBe(true));
 it("preserves every OAuth parameter in the Windows URL",()=>{const contract=oauthRedirectContract({clientId:"client-value"},43123,flow),url=new URL(contract.url);expect(Object.fromEntries(url.searchParams)).toMatchObject({response_type:"code",client_id:"client-value",redirect_uri:"http://127.0.0.1:43123",scope:"https://www.googleapis.com/auth/gmail.readonly",access_type:"offline",prompt:"consent",state:flow.state,code_challenge:flow.challenge,code_challenge_method:"S256"});expect(url.searchParams.size).toBe(9)});
 it("passes the complete URL as explorer.exe's single argument and never uses cmd start",()=>{const url=oauthRedirectContract({clientId:"client-value"},43123,flow).url,target=browserCommand(url,"win32");expect(target).toEqual({command:"explorer.exe",args:[url]});expect(JSON.stringify(target)).not.toMatch(/cmd|\/c|start/)});
 it("uses exactly the same root redirect URI for authorization and exchange",()=>{const contract=oauthRedirectContract({clientId:"client-value"},43123,flow);expect(new URL(contract.url).searchParams.get("redirect_uri")).toBe(contract.redirectUri);expect(contract.exchangeArgs("code").redirectUri).toBe(contract.redirectUri);expect(new URL(contract.redirectUri).pathname).toBe("/");expect(loopbackRedirectUri(43123)).not.toMatch(/\/callback/)});
 it("accepts the root callback",async()=>{const{server,origin}=await listening(),waiting=waitForCallback(server,origin,"right",1000);await fetch(`${origin}/?state=right&code=code`);await expect(waiting).resolves.toBe("code");await close(server)});
 it("favicon and foreign paths do not interrupt a later valid callback",async()=>{const{server,origin}=await listening(),waiting=waitForCallback(server,origin,"right",1000);expect((await fetch(`${origin}/favicon.ico`)).status).toBe(404);expect((await fetch(`${origin}/foreign`)).status).toBe(404);await fetch(`${origin}/?state=right&code=code`);await expect(waiting).resolves.toBe("code");await close(server)});
 it("state mismatch rejects before token exchange",async()=>{const{server,origin}=await listening(),exchange=vi.fn(),waiting=waitForCallback(server,origin,"right",1000),flowResult=waiting.then(exchange),assertion=expect(flowResult).rejects.toThrow("Invalid OAuth callback");await fetch(`${origin}/?state=wrong&code=code`);await assertion;expect(exchange).not.toHaveBeenCalled();await close(server)});
 it("keeps callback timeout behavior",async()=>{const{server,origin}=await listening(),assertion=expect(waitForCallback(server,origin,"right",20)).rejects.toThrow("timeout");await assertion;await close(server)});
 it("browser launch failure is redacted and leaves the manual URL unchanged",()=>{const url=oauthRedirectContract({clientId:"client-value"},43123,flow).url,log=vi.spyOn(console,"log").mockImplementation(()=>{}),error=vi.spyOn(console,"error").mockImplementation(()=>{}),launcher=vi.fn(()=>{throw new Error("launch failed with private marker")});expect(openBrowser(url,"win32",launcher)).toBe(false);expect(browserCommand(url,"win32").args).toEqual([url]);expect(JSON.stringify([...log.mock.calls,...error.mock.calls])).not.toContain("private marker");log.mockRestore();error.mockRestore()});
 it("handles asynchronous launcher errors without logging the URL",()=>{const once=vi.fn((event:string,handler:()=>void)=>{expect(event).toBe("error");handler()}),unref=vi.fn(),launcher=vi.fn(()=>({once,unref}));expect(openBrowser("https://example.invalid/oauth?state=safe","win32",launcher as never)).toBe(true);expect(unref).toHaveBeenCalled()});
 it("preserves other lines and replaces token without logging it",async()=>{const dir=await mkdtemp(join(tmpdir(),"gmail-auth-")),path=join(dir,".env.local"),key=["GMAIL","REFRESH","TOKEN"].join("_"),secret="private-test-value",log=vi.spyOn(console,"log").mockImplementation(()=>{}),error=vi.spyOn(console,"error").mockImplementation(()=>{});await writeFile(path,`OTHER=value\n${key}=old\nLAST=kept\n`);await replaceRefreshToken(path,secret);expect(await readFile(path,"utf8")).toBe(`OTHER=value\n${key}=${secret}\nLAST=kept\n`);expect(JSON.stringify([...log.mock.calls,...error.mock.calls])).not.toContain(secret);log.mockRestore();error.mockRestore()});
 it("adds a missing token line",async()=>{const dir=await mkdtemp(join(tmpdir(),"gmail-auth-")),path=join(dir,".env.local");await writeFile(path,"OTHER=value\n");await replaceRefreshToken(path,"new-value");expect(await readFile(path,"utf8")).toContain("new-value")});
});
