import{createServer,type Server}from"node:http";import{writeFile,readFile,rename,unlink}from"node:fs/promises";import{resolve}from"node:path";import{pathToFileURL}from"node:url";import{spawn}from"node:child_process";import{config as loadDotenv}from"dotenv";import{authorizationUrl,exchangeCode,oauthChallenge}from"../lib/eon-gmail/oauth";import type{EonGmailConfig}from"../lib/eon-gmail/config";
export function loadLocalEnvironment(root=process.cwd(),loader=loadDotenv){return loader({path:resolve(root,".env.local"),override:false})}
function openBrowser(url:string){let command:string,args:string[];if(process.platform==="win32"){command="cmd";args=["/c","start","",url]}else if(process.platform==="darwin"){command="open";args=[url]}else{command="xdg-open";args=[url]}try{spawn(command,args,{detached:true,stdio:"ignore"}).unref()}catch{}}
const envValue=(name:string)=>{const value=process.env[name]?.trim();if(!value||value.startsWith("YOUR_"))throw new Error("Missing OAuth configuration");return value};
function oauthConfig():EonGmailConfig{return{clientId:envValue("GMAIL_CLIENT_ID"),clientSecret:envValue(["GMAIL","CLIENT","SECRET"].join("_")),refreshToken:"unused-during-authorization",expectedAddress:process.env.GMAIL_EXPECTED_ADDRESS??"",allowedFrom:process.env.GMAIL_EON_ALLOWED_FROM??"",query:process.env.GMAIL_EON_QUERY??"",credentialVersion:process.env.GMAIL_CREDENTIAL_VERSION??"1",maxWorkbookDays:7,maxPeriodLagDays:14}}
export async function replaceRefreshToken(path:string,token:string){const original=await readFile(path,"utf8").catch(()=>""),key=["GMAIL","REFRESH","TOKEN"].join("_");const line=`${key}=${token}`,pattern=new RegExp(`^${key}=.*$`,"m"),next=pattern.test(original)?original.replace(pattern,line):`${original}${original&&!original.endsWith("\n")?"\n":""}${line}\n`,temp=`${path}.gmail-auth.tmp`;try{await writeFile(temp,next,{encoding:"utf8",mode:0o600});await rename(temp,path)}catch(e){await unlink(temp).catch(()=>{});throw e}}
export function waitForCallback(server:Server,redirectUri:string,state:string,timeoutMs=120_000){return new Promise<string>((ok,fail)=>{const timer=setTimeout(()=>fail(new Error("OAuth callback timeout")),timeoutMs);server.on("request",(req,res)=>{const incoming=new URL(req.url??"/",redirectUri);res.setHeader("content-type","text/html; charset=utf-8");if(incoming.pathname!=="/callback"){res.statusCode=404;res.end("Not found");return}if(incoming.searchParams.get("state")!==state||!incoming.searchParams.get("code")){clearTimeout(timer);res.statusCode=400;res.end("Az engedélyezés nem sikerült. Bezárhatod ezt az ablakot.");fail(new Error("Invalid OAuth callback"));return}clearTimeout(timer);res.end("Az engedélyezés elkészült. Bezárhatod ezt az ablakot.");ok(incoming.searchParams.get("code")!)})})}
export async function main(){loadLocalEnvironment();const config=oauthConfig(),flow=oauthChallenge(),server=createServer();try{await new Promise<void>((ok,fail)=>{server.once("error",fail);server.listen(0,"127.0.0.1",()=>ok())});const address=server.address();if(!address||typeof address==="string")throw new Error("OAuth callback could not start");const redirectUri=`http://127.0.0.1:${address.port}/callback`,url=authorizationUrl({clientId:config.clientId,redirectUri,state:flow.state,challenge:flow.challenge});console.log("Nyisd meg ezt a Google engedélyezési URL-t a böngészőben:");console.log(url);openBrowser(url);const code=await waitForCallback(server,redirectUri,flow.state),token=await exchangeCode(config,{code,redirectUri,verifier:flow.verifier});if(!token.refresh_token)throw new Error("Google did not return a refresh token");await replaceRefreshToken(resolve(".env.local"),token.refresh_token);console.log("A Gmail refresh token biztonságosan frissült a .env.local fájlban.")}finally{await new Promise<void>(done=>server.close(()=>done())).catch(()=>{})}}
export function isCliEntrypoint(argv1=process.argv[1],moduleUrl=import.meta.url){return Boolean(argv1)&&pathToFileURL(resolve(argv1)).href===moduleUrl}
if(isCliEntrypoint())main().catch(()=>{console.error("A Gmail engedélyezés nem sikerült; titkos adat nem került kiírásra.");process.exitCode=1});
