import{createServer,type Server}from"node:http";import{writeFile,readFile,rename,unlink}from"node:fs/promises";import{resolve}from"node:path";import{pathToFileURL}from"node:url";import{spawn,type ChildProcess}from"node:child_process";import{config as loadDotenv}from"dotenv";import{authorizationUrl,exchangeCode,oauthChallenge}from"../lib/eon-gmail/oauth";import type{EonGmailConfig}from"../lib/eon-gmail/config";
type Launcher=(command:string,args:readonly string[],options:{detached:boolean;stdio:"ignore";windowsHide:boolean})=>Pick<ChildProcess,"unref"|"once">;
export function loadLocalEnvironment(root=process.cwd(),loader=loadDotenv){return loader({path:resolve(root,".env.local"),override:false})}
export function browserCommand(url:string,platform:NodeJS.Platform=process.platform){return platform==="win32"?{command:"explorer.exe",args:[url]}:platform==="darwin"?{command:"open",args:[url]}:{command:"xdg-open",args:[url]}}
export function openBrowser(url:string,platform:NodeJS.Platform=process.platform,launcher:Launcher=spawn){try{const target=browserCommand(url,platform),child=launcher(target.command,target.args,{detached:true,stdio:"ignore",windowsHide:true});child.once("error",()=>{});child.unref();return true}catch{return false}}
const envValue=(name:string)=>{const value=process.env[name]?.trim();if(!value||value.startsWith("YOUR_"))throw new Error("Missing OAuth configuration");return value};
function oauthConfig():EonGmailConfig{return{clientId:envValue("GMAIL_CLIENT_ID"),clientSecret:envValue(["GMAIL","CLIENT","SECRET"].join("_")),refreshToken:"unused-during-authorization",expectedAddress:process.env.GMAIL_EXPECTED_ADDRESS??"",allowedFrom:process.env.GMAIL_EON_ALLOWED_FROM??"",query:process.env.GMAIL_EON_QUERY??"",credentialVersion:process.env.GMAIL_CREDENTIAL_VERSION??"1",maxWorkbookDays:7,maxPeriodLagDays:14}}
export function loopbackRedirectUri(port:number){if(!Number.isInteger(port)||port<1||port>65535)throw new Error("Invalid OAuth callback port");return`http://127.0.0.1:${port}`}
export function oauthRedirectContract(config:Pick<EonGmailConfig,"clientId">,port:number,flow:{state:string;challenge:string;verifier:string}){const redirectUri=loopbackRedirectUri(port),url=authorizationUrl({clientId:config.clientId,redirectUri,state:flow.state,challenge:flow.challenge});return{redirectUri,url,exchangeArgs:(code:string)=>({code,redirectUri,verifier:flow.verifier})}}
export async function replaceRefreshToken(path:string,token:string){const original=await readFile(path,"utf8").catch(()=>""),key=["GMAIL","REFRESH","TOKEN"].join("_");const line=`${key}=${token}`,pattern=new RegExp(`^${key}=.*$`,"m"),next=pattern.test(original)?original.replace(pattern,line):`${original}${original&&!original.endsWith("\n")?"\n":""}${line}\n`,temp=`${path}.gmail-auth.tmp`;try{await writeFile(temp,next,{encoding:"utf8",mode:0o600});await rename(temp,path)}catch(e){await unlink(temp).catch(()=>{});throw e}}
export function waitForCallback(server:Server,redirectUri:string,state:string,timeoutMs=120_000){const pending=new Promise<string>((ok,fail)=>{const timer=setTimeout(()=>fail(new Error("OAuth callback timeout")),timeoutMs);server.on("request",(req,res)=>{const incoming=new URL(req.url??"/",redirectUri);res.setHeader("content-type","text/html; charset=utf-8");if(incoming.pathname!=="/"){res.statusCode=404;res.end("Not found");return}if(incoming.searchParams.get("state")!==state||!incoming.searchParams.get("code")){clearTimeout(timer);res.statusCode=400;res.end("Az engedélyezés nem sikerült. Bezárhatod ezt az ablakot.");fail(new Error("Invalid OAuth callback"));return}clearTimeout(timer);res.end("Az engedélyezés elkészült. Bezárhatod ezt az ablakot.");ok(incoming.searchParams.get("code")!)})});void pending.catch(()=>{});return pending}
export async function main(){loadLocalEnvironment();const config=oauthConfig(),flow=oauthChallenge(),server=createServer();try{await new Promise<void>((ok,fail)=>{server.once("error",fail);server.listen(0,"127.0.0.1",()=>ok())});const address=server.address();if(!address||typeof address==="string")throw new Error("OAuth callback could not start");const contract=oauthRedirectContract(config,address.port,flow);console.log("Nyisd meg ezt a Google engedélyezési URL-t a böngészőben:");console.log(contract.url);openBrowser(contract.url);const code=await waitForCallback(server,contract.redirectUri,flow.state),token=await exchangeCode(config,contract.exchangeArgs(code));if(!token.refresh_token)throw new Error("Google did not return a refresh token");await replaceRefreshToken(resolve(".env.local"),token.refresh_token);console.log("A Gmail refresh token biztonságosan frissült a .env.local fájlban.")}finally{await new Promise<void>(done=>server.close(()=>done())).catch(()=>{})}}
export function isCliEntrypoint(argv1=process.argv[1],moduleUrl=import.meta.url){return Boolean(argv1)&&pathToFileURL(resolve(argv1)).href===moduleUrl}
if(isCliEntrypoint())main().catch(()=>{console.error("A Gmail engedélyezés nem sikerült; titkos adat nem került kiírásra.");process.exitCode=1});
