import{randomUUID}from"node:crypto";import{spawnSync}from"node:child_process";
const connection=(process.env.EON_OVERVIEW_TEST_DATABASE_URL??process.env.EON_GMAIL_TEST_DATABASE_URL)?.trim();if(!connection)throw new Error("EON_OVERVIEW_DB_TEST_NOT_CONFIGURED");const parsed=new URL(connection);if(!["localhost","127.0.0.1","::1"].includes(parsed.hostname))throw new Error("EON_OVERVIEW_DB_TEST_REQUIRES_LOCAL_DATABASE");
const base=[connection,"-X","-v","ON_ERROR_STOP=1","-qAt"],run=(sql:string,stage="SQL_EXECUTION")=>{const result=spawnSync("psql",[...base,"-c",sql],{encoding:"utf8",windowsHide:true});if(result.error||result.status!==0)throw new Error(`EON_OVERVIEW_DB_TEST_FAILED:${stage}`);return result.stdout.trim()},assert=(ok:boolean,code:string)=>{if(!ok)throw new Error(code)},user=randomUUID(),other=randomUUID(),period=randomUUID(),instance="00000000-0000-0000-0000-000000000000";
const authRun=(sql:string)=>{const output=run(`select set_config('request.jwt.claim.sub','${user}',false);${sql}`,"RPC_OVERVIEW");return output.split(/\r?\n/).at(-1)??""},overview=()=>JSON.parse(authRun("select public.get_current_eon_period_overview()")),day=run("select (now() at time zone 'Europe/Budapest')::date","CLOCK_TODAY"),yesterday=run("select ((now() at time zone 'Europe/Budapest')::date-1)::date","CLOCK_YESTERDAY"),localUtc=(date:string,time="00:00")=>run(`select ('${date} ${time}'::timestamp at time zone 'Europe/Budapest')::text`,"LOCAL_TIME_CONVERSION");
function reset(start:string,opening:string|null){run(`delete from public.eon_interval_readings where user_id='${user}';update public.settlement_periods set start_date='${start}',opening_reading_at=${opening?`'${opening}'::timestamptz`:"null"} where id='${period}'`)}
function insertRange(start:string,end:string,owner=user){run(`insert into public.eon_interval_readings(user_id,interval_start_utc,local_date,import_kwh,export_kwh,source) select '${owner}',x,(x at time zone 'Europe/Budapest')::date,1,0,'eon_portal_export' from generate_series('${start}'::timestamptz,'${end}'::timestamptz-interval '15 minutes',interval '15 minutes') x on conflict(user_id,interval_start_utc) do nothing`)}
try{
  assert(run("select to_regprocedure('public.get_current_eon_period_overview()') is not null")==="t","MIGRATION_013_MISSING");
  run(`insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,created_at,updated_at) values('${user}','${instance}','authenticated','authenticated','overview-${user}@example.invalid','',now(),now(),now()),('${other}','${instance}','authenticated','authenticated','overview-${other}@example.invalid','',now(),now(),now());insert into public.settlement_periods(id,user_id,start_date,opening_reading_at,opening_consumption_meter_kwh,opening_production_meter_kwh,status) values('${period}','${user}','${yesterday}','${localUtc(yesterday,"14:07")}',0,0,'open')`);
  const first=localUtc(yesterday,"14:15"),midnight=localUtc(day);insertRange(first,midnight);insertRange(localUtc(day),localUtc(day,"00:15"));insertRange(first,midnight,other);
  let value=overview();assert(value.boundaryPrecision==="exact","EXACT_BOUNDARY_FAILED");assert(value.expectedClosedDayIntervals===39&&value.availableIntervals===40,"PARTIAL_DAY_COUNTS_FAILED");assert(value.missingClosedDayIntervals===0&&value.closedDayCoveragePercent===100,"PARTIAL_DAY_COVERAGE_FAILED");assert(value.completeDays===1&&value.incompleteDays===0&&value.provisionalDays===1,"PARTIAL_DAY_STATUS_FAILED");assert(value.gridImportKwh===40,"OWNER_ISOLATION_FAILED");
  run(`delete from public.eon_interval_readings where user_id='${user}' and interval_start_utc='${first}'::timestamptz`);value=overview();assert(value.missingClosedDayIntervals===1&&value.incompleteDays===1,"ONE_MISSING_INTERVAL_FAILED");assert(value.closedDayCoveragePercent===Math.round(1000*38/39)/10,"PARTIAL_DAY_PERCENT_FAILED");
  run(`update public.settlement_periods set opening_reading_at=null where id='${period}'`);value=overview();assert(value.boundaryPrecision==="date_only"&&value.expectedClosedDayIntervals===96,"DATE_ONLY_BOUNDARY_FAILED");
  run(`delete from public.eon_interval_readings where user_id='${user}'`);value=overview();assert(value.stale===true&&value.warnings.includes("NO_EON_DATA"),"NO_DATA_STALE_FAILED");
  const spring=run("select d::date from generate_series((now() at time zone 'Europe/Budapest')::date-800,(now() at time zone 'Europe/Budapest')::date-1,interval '1 day') d where extract(epoch from (((d+interval '1 day')::date::timestamp at time zone 'Europe/Budapest')-(d::date::timestamp at time zone 'Europe/Budapest')))=82800 order by d desc limit 1"),springStart=localUtc(spring),todayStart=localUtc(day);reset(spring,springStart);insertRange(springStart,todayStart);value=overview();assert(value.missingClosedDayIntervals===0&&value.closedDayCoveragePercent===100,"SPRING_92_DAY_FAILED");
  const fall=run("select d::date from generate_series((now() at time zone 'Europe/Budapest')::date-800,(now() at time zone 'Europe/Budapest')::date-1,interval '1 day') d where extract(epoch from (((d+interval '1 day')::date::timestamp at time zone 'Europe/Budapest')-(d::date::timestamp at time zone 'Europe/Budapest')))=90000 order by d desc limit 1"),fallStart=localUtc(fall),fallNext=localUtc(run(`select ('${fall}'::date+1)::date`));reset(fall,fallStart);run(`insert into public.eon_interval_readings(user_id,interval_start_utc,local_date,import_kwh,export_kwh,source) select '${user}',x,(x at time zone 'Europe/Budapest')::date,1,0,'eon_portal_export' from generate_series('${fallStart}'::timestamptz,'${fallStart}'::timestamptz+interval '23 hours 45 minutes',interval '15 minutes') x`);insertRange(fallNext,todayStart);value=overview();assert(value.fallDstLimitedDays===1&&value.missingClosedDayIntervals===4,"FALL_96_OF_100_FAILED");
  console.log("EON_OVERVIEW_DB_INTEGRATION_OK");
}finally{try{run(`delete from auth.users where id in('${user}','${other}')`)}catch{}}
