import {randomUUID} from "node:crypto";
import {spawnSync} from "node:child_process";
import {resolve} from "node:path";
import {config} from "dotenv";
import {runHeatingAnalysisRebuild,type HeatingAnalysisRepository,type HeatingSource} from "../lib/heating/rebuild-service";
import {HEATING_MODEL_VERSION,featureDatabaseRow} from "../lib/heating/analysis-service";
import type {WeatherHour} from "../lib/heating/eon-analysis";

config({path:resolve(".env.local"),quiet:true});
const connection=process.env.HEATING_ANALYSIS_TEST_DATABASE_URL?.trim();
if(!connection)throw new Error("HEATING_ANALYSIS_DB_TEST_NOT_CONFIGURED");
const parsed=new URL(connection);
if(!["localhost","127.0.0.1","::1"].includes(parsed.hostname))throw new Error("HEATING_ANALYSIS_DB_TEST_REQUIRES_LOCAL_DATABASE");

const psqlBase=[connection,"-X","-v","ON_ERROR_STOP=1","-qAt"];
// Bounded above the largest expected 500-day weather / 50k interval JSON response.
const PSQL_MAX_BUFFER_BYTES=32*1024*1024;
const psqlSpawnOptions={encoding:"utf8" as const,windowsHide:true,maxBuffer:PSQL_MAX_BUFFER_BYTES};
type PsqlResult=ReturnType<typeof spawnSync>;
function psqlFailure(stage:string,result:PsqlResult){if(result.error){const raw=(result.error as NodeJS.ErrnoException).code??"UNKNOWN",code=/^[A-Z0-9_]+$/.test(raw)?raw:"UNKNOWN";return new Error(code==="ENOBUFS"?`HEATING_ANALYSIS_DB_TEST_FAILED:${stage}:PSQL_OUTPUT_LIMIT_EXCEEDED`:`HEATING_ANALYSIS_DB_TEST_FAILED:${stage}:PSQL_SPAWN_ERROR:${code}`)}return new Error(`HEATING_ANALYSIS_DB_TEST_FAILED:${stage}:PSQL_EXIT_ERROR:${result.status??"UNKNOWN"}`)}
function resultOutput(result:PsqlResult,stage:string){if(result.error||result.status!==0)throw psqlFailure(stage,result);return String(result.stdout??"").trim()}
function executeArgs(args:string[],stage:string){return resultOutput(spawnSync("psql",[...psqlBase,...args],psqlSpawnOptions),stage)}
function executeSql(sql:string,stage:string){return resultOutput(spawnSync("psql",psqlBase,{...psqlSpawnOptions,input:`${sql}\n`}),stage)}
const run=(sql:string,stage:string)=>executeSql(sql,stage);
const rows=<T>(sql:string,stage:string):T[]=>JSON.parse(run(`select coalesce(json_agg(t),'[]'::json)::text from (${sql}) t`,stage)||"[]") as T[];
const assert=(condition:boolean,code:string)=>{if(!condition)throw new Error(code)};
const json=(value:unknown)=>`$payload$${JSON.stringify(value)}$payload$`;
const userId=randomUUID(),otherUserId=randomUUID(),instanceId="00000000-0000-0000-0000-000000000000";
type EonRow={at:string;localDate:string;importKwh:string|number;exportKwh:string|number};type PvRow={localDate:string;energyKwh:string|number;qualityStatus:string};type PeriodRow={enabledAt:string;disabledAt:string|null};type ValidationRow={localDate:string;label:"definitely_on"|"definitely_off"|"uncertain"};type StoredRow={observed_at:string;quality_status:string};type WeatherRow={at:string;temperatureC:string|number;windSpeedKmh:string|number|null;shortwaveRadiationWm2:string|number|null;cloudCoverPercent:string|number|null};type FeatureRow={local_date:string;detected_grid_heating_kwh:string|number;estimated_heating_kwh:string|number;excess_kwh:string|number|null;daily_heating_excess_kwh:string|number|null;operation_state:string;data_quality_warnings:string[];available_intervals:number;expected_intervals:number};

function preparePowerFixtures(id:string){if(id===userId)run(`update public.eon_interval_readings set import_kwh=.125 where user_id='${id}' and local_date in('2025-10-26','2026-09-01','2026-10-25');update public.eon_interval_readings set import_kwh=1.775 where user_id='${id}' and local_date in('2026-11-01','2026-11-02') and import_kwh>1;update public.eon_interval_readings set import_kwh=82.0/96 where user_id='${id}' and local_date in('2026-11-03','2026-11-04')`,"POWER_FIXTURES");else run(`update public.eon_interval_readings set import_kwh=.125 where user_id='${id}' and local_date in('2026-11-10','2026-11-11');update public.eon_interval_readings set import_kwh=82.0/96 where user_id='${id}' and local_date='2026-11-12';insert into public.heating_day_validations(user_id,local_date,label)values('${id}','2026-11-10','definitely_off'),('${id}','2026-11-11','definitely_off') on conflict(user_id,local_date)do update set label=excluded.label`,"UNKNOWN_FIXTURES")}
class PsqlRepository implements HeatingAnalysisRepository{
 async claim(id:string){return run(`select public.claim_heating_analysis('${id}')`,"CLAIM")==="t"}
 async release(id:string){run(`select public.release_heating_analysis('${id}')`,"RELEASE")}
 async profile(id:string){preparePowerFixtures(id);let configured=rows<{heatSourceType:string;maximumElectricPowerKw:string|number}>(`select heat_source_type as "heatSourceType",maximum_configurable_power_kw as "maximumElectricPowerKw" from public.heat_sources where user_id='${id}'`,"SOURCE_PROFILE")[0];if(!configured){run(`insert into public.heat_sources(user_id,heat_source_type,nominal_power_kw,maximum_configurable_power_kw)values('${id}','electric_boiler',15,7)`,"SOURCE_PROFILE_FIXTURE");configured={heatSourceType:"electric_boiler",maximumElectricPowerKw:7}}return{latitude:47,longitude:19,timeZone:"Europe/Budapest",targetIndoorC:21,heatSourceType:configured.heatSourceType,maximumElectricPowerKw:Number(configured.maximumElectricPowerKw)}}
 async source(id:string,start:string,end:string){const eon=rows<EonRow>(`select interval_start_utc as at,local_date::text as "localDate",import_kwh as "importKwh",export_kwh as "exportKwh" from public.eon_interval_readings where user_id='${id}' and local_date between '${start}' and '${end}' order by interval_start_utc`,"SOURCE_EON").map(x=>({...x,importKwh:Number(x.importKwh),exportKwh:Number(x.exportKwh)})),pv=rows<PvRow>(`select local_date::text as "localDate",energy_kwh as "energyKwh",quality_status as "qualityStatus" from public.growatt_daily_energy where user_id='${id}' and local_date between '${start}' and '${end}'`,"SOURCE_PV").map(x=>({...x,energyKwh:Number(x.energyKwh)})),periods=rows<PeriodRow>(`select enabled_at as "enabledAt",disabled_at as "disabledAt" from public.heating_operation_periods where user_id='${id}'`,"SOURCE_PERIODS"),validations=rows<ValidationRow>(`select local_date::text as "localDate",label from public.heating_day_validations where user_id='${id}'`,"SOURCE_VALIDATIONS"),storedWeather=rows<StoredRow>(`select observed_at,quality_status from public.heating_weather_hourly where user_id='${id}'`,"SOURCE_WEATHER_COVERAGE"),weather=await this.weather(id,start,end);return{eon,pv,periods,validations,storedWeather,weather} as HeatingSource}
 async saveWeather(id:string,values:WeatherHour[]){run(`select public.save_heating_weather_hourly('${id}',${json(values.map(x=>({observed_at:x.at,temperature_c:x.temperatureC,wind_speed_kmh:x.windSpeedKmh,shortwave_radiation_wm2:x.shortwaveRadiationWm2,cloud_cover_percent:x.cloudCoverPercent,source:x.source})))}::jsonb)`,"WEATHER_SAVE")}
 async weather(id:string,start:string,end:string){return rows<WeatherRow>(`select observed_at as at,temperature_c as "temperatureC",wind_speed_kmh as "windSpeedKmh",shortwave_radiation_wm2 as "shortwaveRadiationWm2",cloud_cover_percent as "cloudCoverPercent" from public.heating_weather_hourly where user_id='${id}' and (observed_at at time zone 'Europe/Budapest')::date between '${start}' and '${end}' order by observed_at`,"WEATHER_READ").map(x=>({at:x.at,temperatureC:Number(x.temperatureC),windSpeedKmh:x.windSpeedKmh==null?null:Number(x.windSpeedKmh),shortwaveRadiationWm2:x.shortwaveRadiationWm2==null?null:Number(x.shortwaveRadiationWm2),cloudCoverPercent:x.cloudCoverPercent==null?null:Number(x.cloudCoverPercent)}))}
 async saveAnalysis(id:string,features:ReturnType<typeof featureDatabaseRow>[],model:Record<string,unknown>){return run(`select public.save_heating_analysis('${id}','${HEATING_MODEL_VERSION}',${json(features)}::jsonb,${json(model)}::jsonb)`,"ANALYSIS_SAVE")}
}

const mockWeather:typeof fetch=async input=>{const url=new URL(String(input)),startValue=url.searchParams.get("start_date")??"2026-10-15",endValue=url.searchParams.get("end_date")??"2026-12-02",start=Date.parse(`${startValue}T00:00:00Z`),end=Date.parse(`${endValue}T23:00:00Z`),count=Math.floor((end-start)/3600000)+1,time=Array.from({length:count},(_,i)=>new Date(start+i*3600000).toISOString().slice(0,16));return new Response(JSON.stringify({hourly:{time,temperature_2m:Array(count).fill(5),wind_speed_10m:Array(count).fill(3),shortwave_radiation:Array(count).fill(0),cloud_cover:Array(count).fill(40)}}),{status:200,headers:{"Content-Type":"application/json"}})};
const insertDay=(owner:string,date:string,limit:string="1000",active=false)=>`insert into public.eon_interval_readings(user_id,interval_start_utc,local_date,import_kwh,export_kwh,source) select '${owner}',g,'${date}',case when ${active} and row_number() over(order by g) between 49 and 52 then 1.85 else .2 end,0,'eon_portal_export' from generate_series('${date}'::date::timestamp at time zone 'Europe/Budapest',(('${date}'::date+1)::timestamp at time zone 'Europe/Budapest')-interval '15 minutes',interval '15 minutes') g limit ${limit};`;

async function main(){try{
 const stdinPayload=JSON.stringify({values:Array.from({length:24000},(_,index)=>`fixture-${index.toString().padStart(5,"0")}`)});assert(stdinPayload.length>=100_000,"STDIN_PAYLOAD_TOO_SMALL");assert(Number(run(`select octet_length(${json(JSON.parse(stdinPayload))}::text)`,"STDIN_LARGE_PAYLOAD"))===Buffer.byteLength(stdinPayload),"STDIN_PAYLOAD_CORRUPTED");const largeStdout=run(`select repeat('x',${2*1024*1024})`,"STDOUT_LARGE_PAYLOAD");assert(Buffer.byteLength(largeStdout)>1024*1024&&Buffer.byteLength(largeStdout)===2*1024*1024,"STDOUT_PAYLOAD_CORRUPTED");let outputFailedClosed=false;try{run(`select repeat('x',${PSQL_MAX_BUFFER_BYTES+1024})`,"STDOUT_LIMIT")}catch(error){outputFailedClosed=error instanceof Error&&error.message==="HEATING_ANALYSIS_DB_TEST_FAILED:STDOUT_LIMIT:PSQL_OUTPUT_LIMIT_EXCEEDED"}assert(outputFailedClosed,"STDOUT_LIMIT_NOT_FAIL_CLOSED");let sqlFailedClosed=false;try{run("select from","STDIN_SQL_FAILURE")}catch(error){sqlFailedClosed=error instanceof Error&&error.message.startsWith("HEATING_ANALYSIS_DB_TEST_FAILED:STDIN_SQL_FAILURE:PSQL_EXIT_ERROR:")}assert(sqlFailedClosed,"STDIN_SQL_NOT_FAIL_CLOSED");
 if(run("select to_regclass('public.heating_operation_periods') is not null","SCHEMA_CHECK")!=="t")executeArgs(["-f",resolve("supabase/migrations/014_eon_heating_analysis.sql")],"MIGRATION_014_APPLY");
 assert(run("select exists(select 1 from information_schema.columns where table_schema='public' and table_name='heating_energy_daily_features' and column_name='detected_grid_heating_kwh')","SCHEMA_VERSION")==="t","LOCAL_DATABASE_REBUILD_REQUIRED");
 run(`insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,created_at,updated_at) values('${userId}','${instanceId}','authenticated','authenticated','heating-${userId}@example.invalid','',now(),now(),now()),('${otherUserId}','${instanceId}','authenticated','authenticated','heating-${otherUserId}@example.invalid','',now(),now(),now());insert into public.heating_profiles(user_id,weather_latitude,weather_longitude,weather_timezone,target_indoor_temperature_c)values('${userId}',47,19,'Europe/Budapest',21),('${otherUserId}',47,19,'Europe/Budapest',21);insert into public.heating_operation_periods(user_id,enabled_at,disabled_at,note)values('${userId}','2026-11-01 12:00 Europe/Budapest','2026-11-05 00:00 Europe/Budapest','integration');insert into public.heating_day_validations(user_id,local_date,label)select '${userId}',d,'definitely_on' from unnest(array['2026-11-02'::date,'2026-11-03','2026-11-04'])d;insert into public.growatt_daily_energy(user_id,local_date,energy_kwh,plant_timezone,quality_status)select '${userId}',d,0,'Europe/Budapest','complete' from unnest(array['2025-10-26'::date,'2026-09-01','2026-10-25','2026-11-01','2026-11-03','2026-11-04'])d;insert into public.growatt_daily_energy(user_id,local_date,energy_kwh,plant_timezone,quality_status)select '${otherUserId}',d,0,'Europe/Budapest','complete' from unnest(array['2026-11-10'::date,'2026-11-11','2026-11-12'])d;${insertDay(userId,"2025-10-26")}${insertDay(userId,"2026-09-01")}${insertDay(userId,"2026-10-25","96")}${insertDay(userId,"2026-11-01","1000",true)}${insertDay(userId,"2026-11-02","1000",true)}${insertDay(userId,"2026-11-03")}${insertDay(userId,"2026-11-04")}${insertDay(otherUserId,"2026-11-10","1000",true)}${insertDay(otherUserId,"2026-11-11","1000",true)}${insertDay(otherUserId,"2026-11-12","1000",true)}`,"FIXTURE_CREATE");
 const repository=new PsqlRepository();assert(await repository.claim(userId),"FIRST_CLAIM_FAILED");assert(!(await repository.claim(userId)),"PARALLEL_CLAIM_NOT_BLOCKED");await repository.release(userId);
 assert(run("select not has_function_privilege('authenticated','public.save_heating_analysis(uuid,text,jsonb,jsonb)','execute')","AUTHENTICATED_RPC_PRIVILEGE")==="t","AUTHENTICATED_WRITER_ALLOWED");assert(run("select has_function_privilege('service_role','public.save_heating_analysis(uuid,text,jsonb,jsonb)','execute')","SERVICE_RPC_PRIVILEGE")==="t","SERVICE_WRITER_DENIED");
 await runHeatingAnalysisRebuild({repository,userId,referenceDate:"2026-12-01",fetcher:mockWeather});await runHeatingAnalysisRebuild({repository,userId:otherUserId,referenceDate:"2026-12-01",fetcher:mockWeather});
 const features=rows<FeatureRow>(`select local_date::text,detected_grid_heating_kwh,estimated_heating_kwh,excess_kwh,daily_heating_excess_kwh,operation_state,data_quality_warnings,available_intervals,expected_intervals from public.heating_energy_daily_features where user_id='${userId}' and model_version='${HEATING_MODEL_VERSION}' order by local_date`,"FEATURE_READ"),at=(date:string)=>features.find(x=>x.local_date===date)!;
 assert(Number(at("2026-11-02").detected_grid_heating_kwh)===6.6,"MISSING_PV_GRID_CYCLE_LOST");assert(Number(at("2026-11-02").estimated_heating_kwh)>=6.6,"CERTAIN_GRID_LOWER_BOUND_LOST");assert(at("2026-11-01").operation_state==="mixed"&&Number(at("2026-11-01").detected_grid_heating_kwh)===6.6,"MIXED_INTERVAL_DETECTION_FAILED");assert(at("2026-11-03").data_quality_warnings.includes("MANUAL_HEATING_CONFIRMED"),"MANUAL_SEASON_SIGNAL_MISSING");assert(Math.abs(Number(at("2026-11-03").excess_kwh)-70)<.01&&Math.abs(Number(at("2026-11-03").daily_heating_excess_kwh)-70)<.01,"PHYSICAL_70_KWH_EXCESS_FAILED");assert(at("2025-10-26").available_intervals===100&&at("2025-10-26").expected_intervals===100,"FALL_100_DAY_FAILED");assert(at("2026-10-25").available_intervals===96&&at("2026-10-25").expected_intervals===100&&at("2026-10-25").data_quality_warnings.includes("DST_FALLBACK_SOURCE_96"),"FALL_96_DAY_NOT_EXCLUDED");
 const unknown=rows<FeatureRow>(`select * from public.heating_energy_daily_features where user_id='${otherUserId}'`,"UNKNOWN_FEATURES"),unknownTarget=unknown.find(x=>x.local_date==="2026-11-12")!;assert(unknown.every(x=>x.operation_state==="unknown"&&Number(x.estimated_heating_kwh)===0),"UNKNOWN_DAILY_ESTIMATE_CREATED");assert(Number(unknownTarget.excess_kwh)>0&&unknownTarget.daily_heating_excess_kwh===null,"UNKNOWN_HEATING_EXCESS_NOT_NULL");assert(run(`select excluded_days from public.heating_analysis_models where user_id='${userId}' and model_version='${HEATING_MODEL_VERSION}'`,"EXCLUDED_DAYS")==="1","MANUAL_CONFIRMATION_COUNTED_AS_EXCLUDED");
 run(`update public.heating_energy_daily_features set local_date='2026-09-15' where user_id='${userId}' and local_date='2026-11-04' and model_version='${HEATING_MODEL_VERSION}'`,"STALE_FIXTURE");await runHeatingAnalysisRebuild({repository,userId,referenceDate:"2026-12-01",fetcher:mockWeather});assert(run(`select count(*) from public.heating_energy_daily_features where user_id='${userId}' and local_date='2026-09-15' and model_version='${HEATING_MODEL_VERSION}'`,"STALE_ASSERT")==="0","STALE_FEATURE_NOT_REMOVED");
 assert(run(`begin;set local role authenticated;select set_config('request.jwt.claim.sub','${otherUserId}',true);select count(*) from public.heating_energy_daily_features where user_id='${userId}';commit`,"RLS_OTHER").split(/\r?\n/).filter(Boolean).at(-1)==="0","RLS_FAILED");console.log("HEATING_ANALYSIS_DB_INTEGRATION_OK");
}finally{try{run(`delete from auth.users where id in('${userId}','${otherUserId}')`,"CLEANUP")}catch{}}}
void main();
