import{randomUUID}from"node:crypto";import{spawn,spawnSync}from"node:child_process";import{resolve}from"node:path";
async function main(){
const connection=process.env.EON_GMAIL_TEST_DATABASE_URL?.trim();if(!connection)throw new Error("EON_GMAIL_DB_TEST_NOT_CONFIGURED");const parsed=new URL(connection);if(!["localhost","127.0.0.1","::1"].includes(parsed.hostname))throw new Error("EON_GMAIL_DB_TEST_REQUIRES_LOCAL_DATABASE");
const base=[connection,"-X","-v","ON_ERROR_STOP=1","-qAt"],run=(sql:string)=>{const value=spawnSync("psql",[...base,"-c",sql],{encoding:"utf8",windowsHide:true});if(value.error||value.status!==0)throw new Error("EON_GMAIL_DB_TEST_FAILED");return value.stdout.trim()},assert=(condition:boolean,code:string)=>{if(!condition)throw new Error(code)};
if(run("select to_regclass('public.eon_gmail_messages') is not null")!=="t"){const migrated=spawnSync("psql",[...base,"-f",resolve("supabase/migrations/012_eon_gmail_ingestion.sql")],{encoding:"utf8",windowsHide:true});if(migrated.error||migrated.status!==0)throw new Error("EON_GMAIL_DB_MIGRATION_SETUP_FAILED")}
const user=randomUUID(),prefix=`gmail-db-test-${randomUUID()}`,literal=(value:string)=>`'${value.replaceAll("'","''")}'`;
run(`insert into auth.users(id,instance_id,aud,role,email,encrypted_password,email_confirmed_at,created_at,updated_at) values('${user}','00000000-0000-0000-0000-000000000000','authenticated','authenticated',${literal(`${prefix}@example.invalid`)},'',now(),now(),now())`);
const claim=(message:string)=>run(`select coalesce(claim_token::text,'') from public.claim_eon_gmail_message('${user}',${literal(message)},null)`),finish=(message:string,token:string,status:string,date="null")=>run(`select coalesce(public.finish_eon_gmail_message('${user}',${literal(message)},'${token}',${literal(status)},null,null,null,${date}),'')`);
try{const first=claim(`${prefix}-lease`);assert(Boolean(first),"FIRST_CLAIM_FAILED");assert(!claim(`${prefix}-lease`),"ACTIVE_LEASE_TAKEN_OVER");run(`update public.eon_gmail_messages set claim_expires_at=now()-interval '1 second' where user_id='${user}' and gmail_message_id=${literal(`${prefix}-lease`)}`);const reclaimed=claim(`${prefix}-lease`);assert(Boolean(reclaimed)&&reclaimed!==first,"EXPIRED_LEASE_NOT_RECLAIMED");assert(!finish(`${prefix}-lease`,randomUUID(),"ignored"),"INVALID_TOKEN_FINALIZED");run(`update public.eon_gmail_messages set claim_expires_at=now()-interval '1 second' where user_id='${user}' and gmail_message_id=${literal(`${prefix}-lease`)}`);assert(!finish(`${prefix}-lease`,reclaimed,"ignored"),"EXPIRED_TOKEN_FINALIZED");
 const retryMessage=`${prefix}-retry`;for(let attempt=1;attempt<=5;attempt++){const token=claim(retryMessage);assert(Boolean(token),`RETRY_CLAIM_${attempt}_FAILED`);const saved=finish(retryMessage,token,"retry");if(attempt<5){assert(saved==="retry",`RETRY_${attempt}_NOT_SAVED`);assert(run(`select next_retry_at is not null from public.eon_gmail_messages where user_id='${user}' and gmail_message_id=${literal(retryMessage)}`)==="t","RETRY_BACKOFF_MISSING");run(`update public.eon_gmail_messages set next_retry_at=now()-interval '1 second' where user_id='${user}' and gmail_message_id=${literal(retryMessage)}`);const next=claim(retryMessage);assert(Boolean(next),"DUE_RETRY_NOT_RECLAIMED");assert(run(`select next_retry_at is null from public.eon_gmail_messages where user_id='${user}' and gmail_message_id=${literal(retryMessage)}`)==="t","NEXT_RETRY_NOT_CLEARED");finish(retryMessage,next,"retry");run(`update public.eon_gmail_messages set attempt_count=${attempt},status='retry',claim_token=null,claim_expires_at=null,next_retry_at=now()-interval '1 second' where user_id='${user}' and gmail_message_id=${literal(retryMessage)}`)}else assert(saved==="failed","FIFTH_RETRY_NOT_FAILED")}assert(!claim(retryMessage),"SIXTH_CLAIM_ALLOWED");
 const dateMessage=`${prefix}-date`,dateToken=claim(dateMessage),date="'2026-08-03T12:00:00Z'::timestamptz";assert(!finish(dateMessage,randomUUID(),"ignored",date),"INVALID_FINISH_CHANGED_DATE");assert(run(`select internal_date is null from public.eon_gmail_messages where user_id='${user}' and gmail_message_id=${literal(dateMessage)}`)==="t","INVALID_FINISH_SAVED_DATE");assert(finish(dateMessage,dateToken,"ignored",date)==="ignored","VALID_FINISH_FAILED");assert(run(`select internal_date='2026-08-03T12:00:00Z'::timestamptz from public.eon_gmail_messages where user_id='${user}' and gmail_message_id=${literal(dateMessage)}`)==="t","VALID_FINISH_DATE_MISSING");
 for(const status of["imported","duplicate"]){const message=`${prefix}-${status}`,token=claim(message);assert(!finish(message,token,status),`${status.toUpperCase()}_WITHOUT_BATCH_ALLOWED`)}
 const concurrent=`${prefix}-concurrent`,sql=`select coalesce(claim_token::text,'') from public.claim_eon_gmail_message('${user}',${literal(concurrent)},null)`;const parallel=()=>new Promise<string>((ok,fail)=>{const child=spawn("psql",[...base,"-c",sql],{windowsHide:true});let out="";child.stdout.on("data",chunk=>out+=chunk);child.on("error",fail);child.on("exit",code=>code===0?ok(out.trim()):fail(new Error("CONCURRENT_CLAIM_FAILED")))}),tokens=await Promise.all([parallel(),parallel()]);assert(tokens.filter(Boolean).length===1,"CONCURRENT_CLAIM_NOT_EXCLUSIVE");console.log("EON_GMAIL_DB_INTEGRATION_OK")
}finally{run(`delete from auth.users where id='${user}'`)}}
void main().catch(error=>{console.error(error instanceof Error?error.message:"EON_GMAIL_DB_TEST_FAILED");process.exitCode=1});
