"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { ConfidenceExplanation } from "@/components/confidence-explanation";
import { actualHeatingConfidenceReasons, noHeatingDemandConfidence } from "@/lib/confidence";
import { useEnergyData } from "@/lib/data";
import { useHeatingData } from "@/lib/heating/data";
import { loadAnalysisSnapshot } from "@/lib/heating/analysis-snapshot";
import { heatingCharacteristic } from "@/lib/heating/period-analysis";
import { optimizationTrial, trialSucceeded } from "@/lib/heating/optimization-plan";
import { buildHeatingLog, heatingLogGuard } from "@/lib/heating/log";
import { heatingRecommendation, validateHeatingLog } from "@/lib/heating/recommendation";
import type { ComfortResult } from "@/lib/heating/types";
import type { RetrospectiveSample } from "@/lib/heating/historical-calibration";
import { createClient } from "@/lib/supabase/client";
import { localIsoDate } from "@/lib/weather/date";

export default function HeatingPage() {
  const { profile, source, thermostat, logs, loading, error, refresh } = useHeatingData();
  const energy=useEnergyData();
  const [logDate, setLogDate] = useState(localIsoDate(new Date()));
  const [outdoor, setOutdoor] = useState<number | null>(null);
  const [outdoorRange, setOutdoorRange] = useState<{minC:number;maxC:number}|null>(null);
  const [temperatureSource, setTemperatureSource] = useState<"weather_api" | "manual">("manual");
  const [, setWeatherNote] = useState("");
  const [message, setMessage] = useState("");
  const [historicalSamples,setHistoricalSamples]=useState<RetrospectiveSample[]>([]);

  useEffect(()=>{let active=true;void createClient().auth.getUser().then(async({data:{user}})=>{if(!user)return;const cached=await loadAnalysisSnapshot(user.id);if(active)setHistoricalSamples(cached?.samples??[])});return()=>{active=false}},[]);

  useEffect(() => {
    if (profile?.weather_latitude == null || profile.weather_longitude == null) return;
    const controller = new AbortController(); setOutdoor(null); setOutdoorRange(null); setTemperatureSource("manual"); setWeatherNote("Időjárás betöltése…");
    const url = `/api/weather?lat=${profile.weather_latitude}&lon=${profile.weather_longitude}&timezone=${encodeURIComponent(profile.weather_timezone)}&date=${logDate}`;
    fetch(url,{signal:controller.signal}).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); const daily = body.daily?.[0]; if (!daily) throw new Error("Nincs adat a kiválasztott naphoz."); setOutdoor(daily.meanC); setOutdoorRange({minC:daily.minC,maxC:daily.maxC}); setTemperatureSource("weather_api"); setWeatherNote(body.kind === "historical" ? "Historikus Open-Meteo adat" : "Open-Meteo előrejelzés"); }).catch(caught => { if(caught instanceof DOMException&&caught.name==="AbortError")return;setOutdoor(null);setOutdoorRange(null);setTemperatureSource("manual");setWeatherNote(caught instanceof Error ? caught.message : "Az időjárás nem érhető el."); });return()=>controller.abort();
  }, [profile, logDate]);
  const recommendation = useMemo(() => profile && source && outdoor != null ? heatingRecommendation(profile, source, logs, outdoor) : null, [profile, source, logs, outdoor]);
  const loadContext=useMemo(()=>outdoor==null||!profile?null:heatingCharacteristic(historicalSamples,energy.tariff,profile.target_indoor_temperature_c,profile.weather_timezone,logs).find(row=>{if(outdoor>10)return row.bucket==="> 10 °C";if(outdoor>5)return row.bucket==="5–10 °C";if(outdoor>0)return row.bucket==="0–5 °C";if(outdoor>-5)return row.bucket==="−5–0 °C";return row.bucket==="< −5 °C"})??null,[historicalSamples,logs,outdoor,profile,energy.tariff]);
  const trial=useMemo(()=>profile&&source&&recommendation&&outdoor!=null&&!recommendation.noHeatingDemand?optimizationTrial(profile,source,logs,recommendation,loadContext,outdoor):null,[profile,source,logs,recommendation,loadContext,outdoor]);

  async function addLog(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!profile || !source || !thermostat || outdoor == null) return;
    const client = createClient(); const { data: { user } } = await client.auth.getUser(); if (!user) return setMessage("A mentéshez bejelentkezés szükséges.");
    const data = new FormData(event.currentTarget);const guard=heatingLogGuard(outdoor,profile.target_indoor_temperature_c,String(data.get("comfort")??""),data.get("summerOverride")==="yes");if(guard)return setMessage(guard);const optional = (name: string) => data.get(name) === "" ? null : Number(data.get(name));
    const row = buildHeatingLog({ userId: user.id, date: logDate, outdoorC: outdoor, outdoorMinC:temperatureSource==="weather_api"?outdoorRange?.minC:null, outdoorMaxC:temperatureSource==="weather_api"?outdoorRange?.maxC:null, source: temperatureSource, targetC: profile.target_indoor_temperature_c, indoorMinC: optional("indoorMin"), indoorAvgC: optional("indoorAvg"), flowC: Number(data.get("flow")), powerKw: Number(data.get("power")), pa02:optional("pa02"), sensitivity: thermostat.switching_sensitivity_c, comfort: String(data.get("comfort")) as ComfortResult, notes: String(data.get("notes") ?? "") });
    const errors = validateHeatingLog(row, source.nominal_power_kw,source.maximum_configurable_power_kw); if (errors.length) return setMessage(errors.join(" "));
    const result = await client.from("heating_logs").insert(row); setMessage(result.error ? result.error.message : "A megfigyelés mentve."); if (!result.error) void refresh();
  }
  return <AppShell><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-bold text-emerald-700">DÖNTÉSTÁMOGATÁS</p><h1 className="text-3xl font-black">Fűtésoptimalizálás</h1><p className="mt-1 text-sm text-slate-500">Az alkalmazás csak ajánl; nem vezérli a kazánt vagy a termosztátot.</p></div><div className="flex gap-2"><Link className="secondary" href="/futes/elemzes">Historikus elemzés</Link><Link className="secondary" href="/beallitasok/futes">Rendszerbeállítások</Link></div></div>
  {loading ? <p className="card mt-5 p-5">Betöltés…</p> : error ? <p className="card mt-5 p-5">A 006 migráció még nem érhető el: {error}</p> : !profile || !source || !thermostat ? <div className="card mt-5 p-5"><p className="font-black">Először hozd létre a fűtési profilt.</p><Link href="/beallitasok/futes" className="primary mt-4 inline-block">Profil létrehozása</Link></div> : <>
    <section className="mt-5 grid gap-3 lg:grid-cols-2"><article className="card p-5"><p className="text-xs font-bold text-emerald-700">MAI HELYZET ÉS AJÁNLÁS</p><h2 className="text-xl font-black">{profile.weather_location_name||"Beállított helyszín"}</h2><label className="mt-4 block text-sm font-bold">Külső napi átlag (°C)<input className="field mt-2" type="number" step="0.1" inputMode="decimal" value={outdoor ?? ""} onChange={event => { setOutdoor(Number(event.target.value)); setTemperatureSource("manual"); setWeatherNote("Kézzel megadott érték"); }}/></label><p className="mt-2 text-xs text-slate-500">Forrás: {temperatureSource === "manual" ? "kézi" : "Open-Meteo"} · beltéri cél {profile.target_indoor_temperature_c} °C</p><div className="mt-4 grid grid-cols-2 gap-3"><Value label="Becsült hőigény" value={recommendation?.noHeatingDemand?"Nincs fűtési igény":recommendation?.estimatedHeatDemandKw == null ? "Nincs igazolt méretezési adat" : `${recommendation.estimatedHeatDemandKw.toFixed(1)} kW`}/><Value label="Ajánlott előremenő" value={recommendation?.noHeatingDemand?"Fűtés nem szükséges":recommendation?.recommendedFlowTemperatureC == null ? "Még tanulom" : `${recommendation.recommendedFlowTemperatureC} °C`}/><Value label="Javasolt maximum" value={recommendation?.noHeatingDemand?"Fűtés nem szükséges":recommendation?.recommendedBoilerPowerKw == null ? "Nincs adat" : `${recommendation.recommendedBoilerPowerKw} kW`}/><div className="col-span-2 rounded-xl bg-slate-50 p-3">{recommendation?.noHeatingDemand?<NoHeatingDemandConfidence outdoorC={outdoor!} targetIndoorC={profile.target_indoor_temperature_c}/>:recommendation?<ConfidenceExplanation level={recommendation.confidence} context="actual" reasons={actualHeatingConfidenceReasons({similarLogCount:recommendation.similarLogCount,hasReference:!!recommendation.referenceLog,confidence:recommendation.confidence})}/>:<ConfidenceExplanation level="low" context="actual" reasons={["Még nincs kiszámított ajánlás."]}/>}</div></div><p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm">{recommendation?.reason ?? "Adj meg külső hőmérsékletet."}</p></article><article className="card p-5"><h2 className="text-xl font-black">Tanulási állapot</h2><p className="mt-3"><b>{logs.length}</b> valódi heating log</p><p className="mt-2 text-sm text-slate-600">A historikus kalibráció külön elemzésként érhető el, és nem kap mesterséges komfortértéket.</p><Link href="/futes/elemzes" className="secondary mt-4 inline-block">Historikus elemzés</Link></article></section>
    {trial&&<section className="card mt-3 p-5"><p className="text-xs font-bold text-blue-700">OPTIMALIZÁLÁSI TERV</p><h2 className="text-xl font-black">Következő kontrollált próba</h2><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4"><Value label="Jelenlegi előremenő" value={trial.currentFlowC==null?"Nincs adat":`${trial.currentFlowC} °C`}/><Value label="Jelenlegi maximum" value={`${trial.currentPowerKw} kW`}/><Value label="Javasolt előremenő" value={trial.proposedFlowC==null?"Változatlan":`${trial.proposedFlowC} °C`}/><Value label="Javasolt maximum" value={`${trial.proposedPowerKw} kW`}/></div>{loadContext&&<p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm">Historikus terhelési kontextus: {loadContext.medianHeatingExcessKwhDay?.toFixed(1)??"nincs adat"} kWh/nap becsült többlet · ≈ {loadContext.averageElectricalLoadEquivalentKw?.toFixed(1)??"nincs adat"} kW átlagos villamos terhelési megfelelő.</p>}<p className="mt-3 text-sm"><b>Időtartam:</b> {trial.durationHours} óra. Figyeld a nappali minimumot, átlagot, komfortot, kapcsolgatást és hálózati importot.</p><p className="mt-2 rounded-xl bg-amber-50 p-3 text-sm">{trial.reason} A PA02-t nem számítjuk át automatikusan kW-ból; a tényleges Bosch-beállítás manuális feladat.</p><ConfidenceExplanation level={trial.confidence} context={trial.sourcePriority==="actual_log"?"actual":"retrospective"} reasons={trial.reasons}/></section>}
    <section className="card mt-3 p-5"><h2 className="text-xl font-black">Mai megfigyelés</h2>{recommendation?.noHeatingDemand&&<p className="mt-2 rounded-xl bg-amber-50 p-3 text-sm">Ehhez a naphoz az időjárás alapján nem várható fűtési igény.</p>}<form onSubmit={addLog} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Dátum<input className="field mt-2" type="date" value={logDate} onChange={event => setLogDate(event.target.value)}/></label><label className="text-sm font-bold">Külső napi átlag<input className="field mt-2" value={outdoor ?? ""} readOnly/></label><input name="indoorMin" type="number" step="0.1" className="field" placeholder="Nappali minimum °C (opcionális)"/><input name="indoorAvg" type="number" step="0.1" className="field" placeholder="Nappali átlag °C (opcionális)"/><input name="flow" type="number" required className="field" placeholder="Előremenő °C" defaultValue={source.current_flow_temperature_c ?? undefined}/><input name="power" type="number" step="0.5" required className="field" placeholder="Max. teljesítmény kW" defaultValue={source.maximum_configurable_power_kw}/><label className="text-sm font-bold">PA02 — fűtőrudak maximuma<select name="pa02" className="field mt-2" defaultValue={source.boiler_pa02_max_rods ?? ""}><option value="">Nincs megadva</option>{[1,2,3,4,5,6].map(value=><option key={value}>{value}</option>)}</select></label><select name="comfort" required defaultValue="" className="field"><option value="" disabled>Válassz eredményt…</option><option value="too_cold">Túl hideg</option><option value="comfortable">Kényelmes</option><option value="too_warm">Túl meleg</option></select>{recommendation?.noHeatingDemand&&<label className="flex items-center gap-2 rounded-xl bg-amber-50 p-3 text-sm"><input type="checkbox" name="summerOverride" value="yes"/> Ennek ellenére rögzítem</label>}<input name="notes" className="field" placeholder="Megjegyzés"/><button className="primary sm:col-span-2">Megfigyelés mentése</button></form>{message && <p className="mt-3 text-sm">{message}</p>}</section>
    <section className="card mt-3 p-5"><h2 className="text-xl font-black">Korábbi megfigyelések</h2>{logs.length === 0 ? <p className="mt-2 text-sm text-slate-500">Még nincs tanulási adat.</p> : logs.slice(0,10).map((log,index) => <div key={log.id ?? index} className="mt-2 grid grid-cols-2 gap-2 rounded-xl bg-slate-50 p-3 text-sm sm:grid-cols-5"><b>{log.log_date}</b><span>{log.outdoor_temperature_mean_c} °C</span><span>{log.flow_temperature_c} °C</span><span>{log.boiler_max_power_kw} kW</span><span>{trialSucceeded(log)?"✓ Sikeres":log.comfort_result==="too_cold"?"✗ Sikertelen":"Túl meleg"}</span></div>)}</section>
  </>}</AppShell>;
}
function Value({label,value}:{label:string;value:string}) { return <div className="min-w-0 rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words font-black">{value}</p></div>; }
function NoHeatingDemandConfidence({outdoorC,targetIndoorC}:{outdoorC:number;targetIndoorC:number}) { const detail=noHeatingDemandConfidence({outdoorC,targetIndoorC});return <ConfidenceExplanation level="high" context="no_heating_demand" explanation={detail.explanation} reasons={detail.reasons}/>; }
