"use client";
import {useEffect,useRef,useState} from "react";
import {formatKwh} from "@/components/format";
type Preview={sha256:string;periodStart:string|null;periodEnd:string|null;validRows:number;invalidRows:number;completeDays:number;provisionalDays:number;incompleteDays:number;importSumKwh:number;exportSumKwh:number;blockingErrors:string[];warnings:string[]};
type History={id:string;period_start:string;period_end:string;status:string;inserted_rows:number;updated_rows:number;unchanged_rows:number;complete_days:number;provisional_days:number;incomplete_days:number;warning_codes:string[];created_at:string};
export const eonLabel:Record<string,string>={completed:"Sikeres",completed_with_warnings:"Sikeres, figyelmeztetésekkel",failed:"Sikertelen",EON_NO_INTERVAL_DATA:"A munkafüzet nem tartalmaz mérési intervallumokat.",EON_INVALID_DATE:"Érvénytelen dátum található.",EON_INVALID_INTERVAL:"Nem 15 perces időpont található.",EON_NEGATIVE_VALUE:"Negatív energiaérték található.",EON_DUPLICATE_INTERVAL:"Duplikált intervallum található.",EON_PARTIAL_INTERVAL_VALUE:"Az intervallum egyik energiaértéke hiányzik.",EON_FUTURE_INTERVAL_DATE:"Jövőbeli mérési dátum található.",EON_INVALID_SUMMARY_ROW:"Az összesítő sor hibás vagy hiányos.",EON_DUPLICATE_SUMMARY_ROW:"Duplikált összesítő sor található.",INVALID_DAY:"Hibás adatot tartalmazó nap.",PROVISIONAL_DAY:"Az aktuális nap még részleges.",INCOMPLETE_DAY:"Egy lezárt nap adatsora hiányos.",EON_SUMMARY_TOTAL_MISMATCH:"Az Excel összesített értéke eltér az intervallumok összegétől.",EON_SUMMARY_MAX_MISMATCH:"Az Excel maximumértéke eltér az intervallumok maximumától."};
Object.assign(eonLabel,{DST_SPRING_TEMPLATE_ALIGNED:"A tavaszi óraátállítás E.ON-sablonja biztonságosan hozzá lett igazítva a 92 valódi intervallumhoz.",DST_FALLBACK_SOURCE_96:"Az E.ON az őszi óraátállítás napján csak 96 intervallumot szolgáltatott a várt 100 helyett.",EON_DST_TEMPLATE_AMBIGUOUS:"A tavaszi óraátállítási sablon nem igazítható biztonságosan."});
export const budapestImportInstant=(value:string)=>new Intl.DateTimeFormat("hu-HU",{dateStyle:"long",timeStyle:"short",timeZone:"Europe/Budapest"}).format(new Date(value));
export function EonIntervalImportCard(){
  const[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<Preview|null>(null),[history,setHistory]=useState<History[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const inputRef=useRef<HTMLInputElement>(null);
  async function load(){try{const r=await fetch("/api/eon/imports",{cache:"no-store"}),x=r.ok?await r.json():{imports:[]};setHistory(x.imports??[])}catch{setHistory([])}}
  useEffect(()=>{void load()},[]);function choose(next:File|null){setFile(next);setPreview(null);setMessage("")}
  async function runPreview(){if(!file)return;setBusy(true);setMessage("");try{const form=new FormData();form.set("file",file);const response=await fetch("/api/eon/import/preview",{method:"POST",body:form,cache:"no-store"}),body=await response.json();if(!response.ok){setMessage(body.error?.message??"Az előnézet nem sikerült.");return}setPreview(body)}catch{setMessage("Hálózati hiba miatt az előnézet nem sikerült.")}finally{setBusy(false)}}
  async function commit(){if(!file||!preview||preview.blockingErrors.length)return;setBusy(true);try{const form=new FormData();form.set("file",file);form.set("expectedSha256",preview.sha256);const response=await fetch("/api/eon/import/commit",{method:"POST",body:form,cache:"no-store"}),body=await response.json();if(!response.ok){setMessage(body.error?.message??"Az import nem sikerült.");return}setMessage(`Import kész: ${body.insertedRows} új, ${body.updatedRows} frissített, ${body.unchangedRows} változatlan intervallum.`);setPreview(null);setFile(null);if(inputRef.current)inputRef.current.value="";await load()}catch{setMessage("Hálózati hiba miatt az import nem sikerült.")}finally{setBusy(false)}}
  return <section className="card mt-5 p-5"><p className="text-xs font-black uppercase tracking-wider text-emerald-700">E.ON-adatok</p><h2 className="mt-1 text-xl font-black">E.ON 15 perces adatok importálása</h2><p className="mt-1 text-sm text-slate-600">Az E.ON portál XLSX exportjának ellenőrzött, idempotens importja.</p><label className="mt-4 block rounded-xl border-2 border-dashed border-slate-300 p-5 text-center text-sm font-bold">XLSX kiválasztása<input ref={inputRef} className="sr-only" type="file" accept=".xlsx" onChange={e=>choose(e.target.files?.[0]??null)}/></label><button className="secondary mt-3 w-full sm:w-auto" disabled={!file||busy} onClick={()=>void runPreview()}>{busy?"Ellenőrzés…":"Előnézet"}</button>{preview&&<div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><div className="grid grid-cols-2 gap-2"><span>Időszak</span><b className="text-right">{preview.periodStart} – {preview.periodEnd}</b><span>Vételezés (+A)</span><b className="text-right">{formatKwh(preview.importSumKwh)}</b><span>Betáplálás (-A)</span><b className="text-right">{formatKwh(preview.exportSumKwh)}</b><span>Teljes / részleges / hiányos nap</span><b className="text-right">{preview.completeDays} / {preview.provisionalDays} / {preview.incompleteDays}</b><span>Valid / hibás sor</span><b className="text-right">{preview.validRows} / {preview.invalidRows}</b></div>{preview.warnings.map(x=><p key={x} className="mt-2 rounded-lg bg-amber-50 p-2 text-amber-900">{eonLabel[x]??x}</p>)}{preview.blockingErrors.map(x=><p key={x} role="alert" className="mt-2 rounded-lg bg-red-50 p-2 font-bold text-red-800">{eonLabel[x]??x}</p>)}<button className="primary mt-4 w-full sm:w-auto" disabled={busy||preview.blockingErrors.length>0} onClick={()=>void commit()}>Importálás</button></div>}{message&&<p className="mt-3 rounded-xl bg-slate-100 p-3 text-sm">{message}</p>}<h3 className="mt-6 font-black">Importelőzmények</h3><div className="mt-2 space-y-2">{history.length?history.map(x=><div key={x.id} className="rounded-xl border p-3 text-sm"><p className="font-bold">{eonLabel[x.status]??x.status}</p><p>{budapestImportInstant(x.created_at)}</p><p>{x.period_start} – {x.period_end}</p><p>{x.inserted_rows} új · {x.updated_rows} frissített · {x.unchanged_rows} változatlan intervallum</p><p>{x.complete_days} teljes · {x.provisional_days} részleges · {x.incomplete_days} hiányos nap</p>{x.warning_codes.map(code=><p key={code} className="text-amber-800">{eonLabel[code]??code}</p>)}</div>):<p className="text-sm text-slate-500">Még nincs E.ON-import.</p>}</div></section>
}
