-- Additív fűtésoptimalizálási séma. Meglévő energiaadatot nem módosít.
create table public.heating_profiles (
  id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade,
  heated_area_m2 numeric check (heated_area_m2 > 0), conditioned_volume_m3 numeric check (conditioned_volume_m3 > 0), specific_heat_loss_w_m3k numeric check (specific_heat_loss_w_m3k >= 0), target_indoor_temperature_c numeric not null default 21 check (target_indoor_temperature_c between 5 and 35),
  design_heat_loss_kw numeric check (design_heat_loss_kw > 0), design_heat_loss_is_estimate boolean not null default true, design_indoor_temperature_c numeric check (design_indoor_temperature_c between 5 and 35), design_outdoor_temperature_c numeric check (design_outdoor_temperature_c between -40 and 20),
  building_energy_rating text, specific_heat_demand_kwh_m2_year numeric check (specific_heat_demand_kwh_m2_year >= 0),
  heat_distribution_type text not null default 'radiators' check (heat_distribution_type in ('radiators')),
  weather_location_name text, weather_latitude numeric check (weather_latitude between -90 and 90), weather_longitude numeric check (weather_longitude between -180 and 180),
  weather_timezone text not null default 'Europe/Budapest', optimization_enabled boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.heat_sources (
  id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade,
  manufacturer text not null default 'Bosch', model text not null default 'Tronic Heat 3500', heat_source_type text not null default 'electric_boiler' check (heat_source_type in ('electric_boiler','heat_pump','other')),
  nominal_power_kw numeric not null default 15 check (nominal_power_kw > 0), minimum_configurable_power_kw numeric check (minimum_configurable_power_kw > 0), maximum_configurable_power_kw numeric not null default 15 check (maximum_configurable_power_kw > 0),
  has_buffer_tank boolean not null default false, current_flow_temperature_c numeric check (current_flow_temperature_c between 20 and 90), boiler_pa02_max_rods integer check (boiler_pa02_max_rods between 1 and 6), boiler_pa03_regulation_mode integer check (boiler_pa03_regulation_mode between 0 and 4), control_notes text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (maximum_configurable_power_kw <= nominal_power_kw), check (minimum_configurable_power_kw is null or minimum_configurable_power_kw <= maximum_configurable_power_kw)
);
create table public.thermostat_settings (
  id uuid primary key default gen_random_uuid(), user_id uuid not null unique references auth.users(id) on delete cascade,
  manufacturer text not null default 'COMPUTHERM', model text not null default 'Q7RF', thermostat_type text not null default 'on_off' check (thermostat_type = 'on_off'), location_room text default 'nappali', location_floor text default 'földszint', target_temperature_c numeric not null default 21 check (target_temperature_c between 5 and 35), switching_sensitivity_c numeric not null default 0.2 check (switching_sensitivity_c in (0.1,0.2,0.3)), calibration_offset_c numeric not null default 0 check (calibration_offset_c between -3 and 3), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.radiators (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, room_name text not null, floor text, radiator_type text, width_mm integer check (width_mm > 0), height_mm integer check (height_mm > 0), quantity integer not null default 1 check (quantity > 0), nominal_output_w numeric check (nominal_output_w > 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.heating_logs (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, log_date date not null,
  outdoor_temperature_mean_c numeric check (outdoor_temperature_mean_c between -50 and 50), outdoor_temperature_min_c numeric check (outdoor_temperature_min_c between -50 and 50), outdoor_temperature_max_c numeric check (outdoor_temperature_max_c between -50 and 50), temperature_source text not null check (temperature_source in ('weather_api','manual')),
  target_indoor_temperature_c numeric not null check (target_indoor_temperature_c between 5 and 35), actual_indoor_temperature_c numeric check (actual_indoor_temperature_c between 5 and 40), actual_indoor_min_temp_c numeric check (actual_indoor_min_temp_c between 5 and 40), actual_indoor_avg_temp_c numeric check (actual_indoor_avg_temp_c between 5 and 40), flow_temperature_c numeric not null check (flow_temperature_c between 20 and 90), boiler_max_power_kw numeric not null check (boiler_max_power_kw > 0), boiler_pa02_max_rods integer check (boiler_pa02_max_rods between 1 and 6), thermostat_switching_sensitivity_c numeric not null check (thermostat_switching_sensitivity_c in (0.1,0.2,0.3)), comfort_result text not null check (comfort_result in ('too_cold','comfortable','too_warm')), notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check (outdoor_temperature_min_c is null or outdoor_temperature_max_c is null or outdoor_temperature_min_c <= outdoor_temperature_max_c), check (actual_indoor_min_temp_c is null or actual_indoor_avg_temp_c is null or actual_indoor_min_temp_c <= actual_indoor_avg_temp_c)
);
create or replace function public.validate_heating_log_power() returns trigger language plpgsql security definer set search_path = public as $$ declare nominal numeric; configured_max numeric; begin select nominal_power_kw, maximum_configurable_power_kw into nominal, configured_max from public.heat_sources where user_id = new.user_id; if nominal is not null and new.boiler_max_power_kw > nominal then raise exception 'A kazánteljesítmény nem lépheti túl a névleges teljesítményt.'; end if; if configured_max is not null and new.boiler_max_power_kw > configured_max then raise exception 'A naplózott teljesítmény nem lépheti túl a profilban jelenleg engedélyezett maximumot.'; end if; return new; end $$;
create trigger validate_heating_log_power_before_write before insert or update on public.heating_logs for each row execute function public.validate_heating_log_power();
do $$ declare table_name text; begin foreach table_name in array array['heating_profiles','heat_sources','thermostat_settings','radiators','heating_logs'] loop execute format('alter table public.%I enable row level security',table_name); execute format('create policy %I on public.%I for select using (auth.uid() = user_id)',table_name||'_select_own',table_name); execute format('create policy %I on public.%I for insert with check (auth.uid() = user_id)',table_name||'_insert_own',table_name); execute format('create policy %I on public.%I for update using (auth.uid() = user_id) with check (auth.uid() = user_id)',table_name||'_update_own',table_name); execute format('create policy %I on public.%I for delete using (auth.uid() = user_id)',table_name||'_delete_own',table_name); end loop; end $$;
